### ISSUE TITLE
Could not configure server

### ISSUE THREAD

**Issue by Ham3D** [vpnhood/VpnHood#100]
cannot start server

2022/02/12 14:22:02.453 | Info | Server
 Configuring by the Access Server...

2022/02/12 14:22:07.983 | Error | Server
 Could not configure server! Retrying after 60 seconds. Message: Index was outside the bounds of the array.

**Comment by bobvhood** [comment]
Are you sure you are using the latest version?
We are committed to finding this issue. Please send us the entire log and keep in contact with us at support@vpnhood.com
