### ISSUE TITLE
prerequisites not satisfiying 

### ISSUE THREAD

**Issue by ironeagle-ir** [vpnhood/VpnHood#101]
ProductVersion = 2.4.295
windows 10-21H2-B:19044.1526
as title suggests
![Screenshot 2022-02-13 003543](https://user-images.githubusercontent.com/24396208/153728545-17e97125-94bd-41d9-b326-901501c653d7.jpg)

**Comment by bobvhood** [comment]
Can you tell me whether your Windows is 32 bit or 64?

Meanwhile, you can download webview2 from the following it. Please install via the "Evergreen Bootstrapper" link
https://developer.microsoft.com/en-us/microsoft-edge/webview2/

**Comment by ironeagle-ir** [comment]
thank you for answering.
of course, my bad, it's X64, I already did try manually installing standalone installer, which didn't work, will try boot strap installer and let you know the result.

**Comment by ironeagle-ir** [comment]
"Evergreen Bootstrapper" link or installer didn't work either, still same error.

**Comment by bobvhood** [comment]
OK, have you failed to install VpnHood after installing "WebView2," or you couldn't install WebView2 at the first step?

**Comment by ironeagle-ir** [comment]
failed to install VpnHood after installing "WebView2,"

**Comment by ironeagle-ir** [comment]
all WebView2 install instances (I mean all 3 given download options install fine.

**Comment by bobvhood** [comment]
I installed our latest version on fresh Windows and couldn't simulate the issue. Another user had same issue before, are you sure you have installed VpnHood from the following link?
https://github.com/vpnhood/VpnHood/releases/latest/download/VpnHoodClient-Win.exe

Please check the following issue too:
https://github.com/vpnhood/VpnHood/issues/84

**Comment by ironeagle-ir** [comment]
this is so odd, according to file checksums these files are both the same, but the whole installation and some interfaces was some how different, anyhow, the link you send did the job, but I'll attache checksum for you to further investigation, by the way, I'd downloaded the file from latest release page and link, and if it helps, Ive downloaded your sent link with VPN.
![Screenshot 2022-02-14 123855](https://user-images.githubusercontent.com/24396208/153838335-c7fdc324-fed1-4cd3-90ee-91322e863bd7.jpg)

**Comment by bobvhood** [comment]
That's weird for us too, Would you let me know where did you download VpnHood for windows in the first place?

**Comment by ironeagle-ir** [comment]
as I mentioned before : https://github.com/vpnhood/VpnHood/releases/download/v2.4.295/VpnHoodClient-win.exe
