### ISSUE TITLE
Several connection attempts needed before it succeeds (Windows 11)

### ISSUE THREAD

**Issue by rwenzlofsky** [vpnhood/VpnHood#105]
Hi. When I use the windows client I always need a couple of attempts to connect before the connection succeeds. In the logs I see the following error when the connection fails:

[22:43:09.6745] fail: [0]
      Ein Socketvorgang bezog sich auf ein nicht verfügbares Netzwerk.
which means : "a socket activity is related to a not available network"

**Comment by trudyhood** [comment]
Sorry, but the error does not give us much information. Please let us know if the problem persists.
