### ISSUE TITLE
The program cannot be installed under Windows 10 professional edition

### ISSUE THREAD

**Issue by Fun-L** [vpnhood/VpnHood#108]
The program cannot be installed under Windows 10 professional edition.
Show webview2 installation failed:

![123](https://user-images.githubusercontent.com/101727315/158761909-533cbeee-640a-46c3-87d7-7a65ec2af780.png)

After the manual installation, view the installed program to show that it is installed. However, it is still not installed and Webview2 needs to be installed for display
![123123](https://user-images.githubusercontent.com/101727315/158762295-7caed439-9a5b-494b-8fb0-d489d6a92be5.png)
![234](https://user-images.githubusercontent.com/101727315/158762780-03fb2808-e418-44fb-bca0-9bd36a7229d1.png)

I found that the new version of webview2 can't work normally. I use the old version of VPN hood to work normally
![微信截图_20220318000552](https://user-images.githubusercontent.com/101727315/158843004-1d88865e-dd60-451e-98ca-20949de9f8be.png)

**Comment by trudyhood** [comment]
Few others have this issue. I couldn't simulate the problem yet. Is is the evergreen version? Where can I find that version?
This one works in our clean environment.
![image](https://user-images.githubusercontent.com/72891124/159091778-28474afe-1935-43ac-baee-e0b1027ed7ec.png)

**Comment by Fun-L** [comment]
If it is a Windows 10 with vs2022 installed, it can run normally. Because vs2022 is installed with webview2 version 96.0.1054.

If it is a pure computer, webview2 has not been installed. Is unable to install successfully. Because he downloaded the latest version 99.0.1150 from the official website by default, I need to uninstall this version and reinstall version 96.0.1054.

My continuous research has found that if vs is installed on a new computer, VPN hood can be installed normally no matter what version of webview2 is.

Puzzling...

If you need version 96.0.1054, I can send it to your email.

**Comment by trudyhood** [comment]
Thank you for your contribution. I have found the issue! The problem was that WebView does not install for all users when there is no privilege. If you run the setup "As Administrator", the issue will be solved. By the way, I've fixed the setup, and let's hope we never see this issue again.
