### ISSUE TITLE
VpnHood does not work properly

### ISSUE THREAD

**Issue by Fun-L** [vpnhood/VpnHood#109]
#108 
Sorry, maybe I didn't express it clearly. I expressed two problems, one is that it can't be installed and the other is that it can't run normally.

If it is under windows10, the 96.0.1054 version of webview2 can run VpnHood normally. If it is the latest webview2, the browser will be opened when VpnHood starts, and then visit 127.0.0.1

**Comment by trudyhood** [comment]
Yes, got it. Please wait for our next release. We have solved this issue.

**Comment by Fun-L** [comment]
Thank you. Will the fix of the problem be seen in branch development?

**Comment by trudyhood** [comment]
> Thank you. Will the fix of the problem be seen in branch development?

No, The fix has been applied to its installation package. Meanwhile, you can run setup (VpnHoodClient-Win.exe) "as administrator". I think it would solve the issue. Let me know if it doesn't help.

**Comment by trudyhood** [comment]
Please download the new version (2.4.296) and let me know the result.
