### ISSUE TITLE
VpnHood Access Server is not working

### ISSUE THREAD

**Issue by NimaEagle** [vpnhood/VpnHood#110]
After logining with email the loading indicator spins forever and at the bottom of screen a message appeares that says "An unhandled error has occurred. Reload".
I've tried with other browsers too but same thing happens.

**Comment by trudyhood** [comment]
We were upgrading our service. Sorry for this inconvenience. I hope we can reduce the maintenance time. 
We are still working on it but it should be available now.
Thank you for using our AccessServer
