### ISSUE TITLE
Linux version?

### ISSUE THREAD

**Issue by NiiightmareXD** [vpnhood/VpnHood#113]

**Comment by bobvhood** [comment]
Hi, VpnHood Server can run on Linux, but I think you asked about the client. VpnHood client can easily support Linux by adding a packet filter driver. However, I'm afraid to say that it is not on our priority list.

**Comment by bizzbyster** [comment]
Can VpnHood client also potentially run on Mac? Assuming the redirection is done via Mac filtering?

**Comment by bobvhood** [comment]
It should be if a filtering driver is created for it.  Creating a filter driver for VpnHood is easy. Here is for Windows; it is just two files
https://github.com/vpnhood/VpnHood/tree/main/VpnHood.Client.Device.WinDivert

The other issue is the UI. If no specific UI is implemented for Mac, VpnHood can open the browser and shows the UI on localhost host

![image](https://user-images.githubusercontent.com/92276967/167017031-5799c342-568f-48ea-823d-f8883c1bc367.png)

**Comment by realsifocopypaste333** [comment]
please make vpnhood client for linux gui and cli. thanks :)

**Comment by bobvhood** [comment]
> please make vpnhood client for linux gui and cli. thanks :)

Sorry, it is not planned yet.

**Comment by demon740** [comment]
sorry but I cannot find any installation procedure for Linux (as server)

**Comment by trudyhood** [comment]
> sorry but I cannot find any installation procedure for Linux (as server)

https://github.com/vpnhood/VpnHood/wiki/How-to-run-VpnHood-Server-on-Linux
