### ISSUE TITLE
Can't install to Ubuntu 20.01

### ISSUE THREAD

**Issue by pursiyanov** [vpnhood/VpnHood#115]
Please, help me, i can't install hood to my new clean server on ubuntu 20.01

VpnHood Installation for linux
Install .NET 6.0 (y/n)?y
Auto Start (y/n)?y
dotnet-sdk removed
dotnet-sdk (6.0/stable) 6.0.201 from Microsoft .NET Core (dotnetcore✓) installed
Downloading VpnHoodServer...
--2022-04-04 00:55:23--  https://github.com/vpnhood/VpnHood/releases/download/v2.4.297/VpnHoodServer.tar.gz
Resolving github.com (github.com)... 52.64.108.95
Connecting to github.com (github.com)|52.64.108.95|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-04-04 00:55:24 ERROR 404: Not Found.

Stop VpnHoodServer if exists...
Extracting to /opt/VpnHoodServer

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
creating autostart service. Name: VpnHoodService...
run VpnHoodServer service...

**Comment by bobvhood** [comment]
Thank you for reporting it. I've fixed it. Please try again.
