### ISSUE TITLE
Vpnhood server does not work properly on windows server 2012

### ISSUE THREAD

**Issue by Mahdi0024** [vpnhood/VpnHood#116]
Server starts correctly but when I try connecting, it will write this to the console and cannot connect:
`2022/04/06 04:18:37.261 | Error | Server`
`An unknown, invalid, or unsupported option or level was specified in a getsockopt or setsockopt call.`
`2022/04/06 04:18:37.277 | Info | Server`
`Stop listening on 0.0.0.0:443`
Server version is: `2.4.297.0` and I'm using default settings.

**Comment by bobvhood** [comment]
Sorry, but I am afraid to say that we don't have a plan to support windows 2012. I am sorry for this inconvenience.
