### ISSUE TITLE
When I Change The Tunnel Traffic For Countries To No, My IP Isnt Changed 

### ISSUE THREAD

**Issue by cwz6h** [vpnhood/VpnHood#120]

**Comment by trudyhood** [comment]
Hi,

How do you check your public IP? If the server shows your public resides in your country, you will see your IP is not changed. For example, if you are in the US and set "Exclude My Country," then if you query your IP from google, you will see that your IP is not changed. 
Let me know if you see different behavior so I will reopen the issue

**Comment by cwz6h** [comment]
I Use: whatismyip.com

**Comment by trudyhood** [comment]
Can we have your public IP address? You can send it to support@vpnhood.com
I need to make sure your Public IP is not marked as the US in the IP Location Database. 
 whatismyip.com is located in the US, so if you are in the US and select exclude your country, any server in the US will see your actual public address.
