### ISSUE TITLE
Работоспособность на Windows 10

### ISSUE THREAD

**Issue by YustasStirlic** [vpnhood/VpnHood#124]
Hello! client VpnHood refuses to work on Windows 10. When I try to run: 1) via a shortcut on the desktop 2) from the start menu 3) from Program Fies(VpnHoodClient.exe)
A gray window pops up on the side. What do you advise?
Screenshots attached.
<img width="960" alt="Безымянный" src="https://user-images.githubusercontent.com/108677033/177187213-f2034cc8-3712-4378-9037-735105bff331.png">
.

**Comment by bobvhood** [comment]
Please reinstall the latest version, and let me know does it fix the issue or not.
In most cases reinstalling this issue should solve this problem.
