### ISSUE TITLE
What ports should be open?

### ISSUE THREAD

**Issue by AliKhadivi** [vpnhood/VpnHood#127]
Hello
What ports should be open?

**Comment by bobvhood** [comment]
Hi, Do you use Access Server or Manual Install?

**Comment by AliKhadivi** [comment]
Manual Install

**Comment by AliKhadivi** [comment]
I built the program myself

**Comment by bobvhood** [comment]
The default is TCP 443. And if you want to use UDP mode, you need to open all UDP ports. You can specify the port of the server in command line too

**Comment by Onair-santa** [comment]
open all input udp ports linux server?
manual install
Is it possible to register only one port udp both on the server and in the Windows client?

**Comment by bobvhood** [comment]
Yes, in recent version only one UDP port is used. You can go to access server and manage that.

**Comment by Onair-santa** [comment]
How to write a rule in nftables for all incoming for udp?
My table now 
table inet filter { # handle 112
	chain input { # handle 1
		type filter hook input priority filter; policy drop;
		iifname "lo" accept # handle 5
		iifname "enp3s0" tcp dport 22 accept # handle 6
		iifname "enp3s0" tcp dport { 80, 443 } accept # handle 7
		ct state established,related accept # handle 9
		iifname "enp3s0" udp dport 1-50000 accept # handle 10
		
OK? Or 1-50000 are wrong?

**Comment by bobvhood** [comment]
I am afraid to tell you that I don't know how nftables works. I recommend you to let VpnHood server listen on a fixed UDP port. That's all. I can't understandwhy you need to work with nftables unless you have a specific network configuration.

**Comment by Onair-santa** [comment]
1.Install app in linux server
2. nano /opt/VpnHoodServer/storage/appsettings.json
`{
  "HttpAccessManager": null,
  "FileAccessManager": {
    "TcpEndPoints": [ "77.77.77.77:443" ],
    "UdpEndPoints": [ "77.77.77.77:65432" ],
    "SslCertificatesPassword": null,
    "Tracking": {
      "TrackClientIp": false,
      "TrackLocalPort": false,
      "TrackDestinationIp": false,
      "TrackDestinationPort": false
    },
    "Session": {
      "Timeout": "01:00:00",
      "UdpTimeout": "00:01:00",
      "TcpTimeout": "00:15:00",
      "IcmpTimeout": "00:30:00",
      "MaxDatagramChannelCount": 8,
      "MaxUdpClientCount": null,
      "MaxIcmpClientCount": null,
      "TcpBufferSize": 8192,
      "TcpKernelSendBufferSize": null,
      "TcpKernelReceiveBufferSize": null
    },
    "NetFilter": {
      "ExcludeLocalNetwork": true,
      "PacketCaptureIncludeIpRanges": ["0.0.0.0/0", "[::]/0"],
      "PacketCaptureExcludeIpRanges": [],
      "IncludeIpRanges": ["0.0.0.0/0", "[::]/0"],
      "ExcludeIpRanges": []
    }
  },
  "IsDiagnoseMode": false
}`
3. Restart VpnHood
4. allow 443 tcp and 65432 udp port in firewall
4. sudo /opt/VpnHoodServer/vhserver gen
5. add link in windpws app.

All OK?
