### ISSUE TITLE
The "simple VPN Client for Window" has poor performance

### ISSUE THREAD

**Issue by AmirHosseinCV** [vpnhood/VpnHood#131]
I'm trying to create a VPN client. I have tried to run [this project](https://github.com/vpnhood/VpnHood/tree/main/Samples/VpnHood.Samples.SimpleClient.Win). When I run it, It connects to my server and when I google "what is my IP address", I can see my server's IP address in the result.
But the problem is that I can't open almost any other website (ipinfo.io, speedtest.net, ...). At first, I thought that might be a DNS issue, so I tried to run a simple webserver on my server and open it by its IP. It took too long to be opened. However, everything works well when I use your windows client application. 
I have noticed that when it connects, I can't open almost any website, but the problem solves if I use a socks proxy (which runs on the same server as VPN) in my browser.

**Comment by trudyhood** [comment]
Hi, 
We need to have your server and client log file.
Please make sure you don't run multiple VPN or proxies at the same time. 

> However, everything works well when I use your windows client application
Do you mean the connection to our test public servers?

**Comment by AmirHosseinCV** [comment]
@trudyhood
Sorry I don't understand which files do you mean.

No, I mean my own server in both situations.

**Comment by trudyhood** [comment]
Please double-check and make sure you are using the latest version and setting your server Accesskey in the project. You can also send us your AccessKey to support@vpnhood.com so we can check it out.

**Comment by AmirHosseinCV** [comment]
I've checked everything I could. I'll send you an email.

Thank you for your quick response ❤️.
