### ISSUE TITLE
Linux Client

### ISSUE THREAD

**Issue by AliKhadivi** [vpnhood/VpnHood#132]

**Comment by trudyhood** [comment]
Sorry, there is no plan for Linux Client yet. However, VpnHood is very portable, it just needed a packet, and other parts are ready.

**Comment by AliKhadivi** [comment]
A package like WinDivert but for Linux?

**Comment by AliKhadivi** [comment]
You can use it https://github.com/dotpcap/sharppcap
Supported Windows, Linux and Mac

**Comment by trudyhood** [comment]
> You can use it https://github.com/dotpcap/sharppcap Supported Windows, Linux and Mac

We already use sharppcap, just need someone to implement and test a LinuxDevice same as the following project. It is isolated from the rest of VpnHood
https://github.com/vpnhood/VpnHood/tree/main/VpnHood.Client.Device.WinDivert

Unfortunately, it is not our priority list.

**Comment by trudyhood** [comment]
Duplicate of #113
