### ISSUE TITLE
Using domain name instead of IP address

### ISSUE THREAD

**Issue by AmirHosseinCV** [vpnhood/VpnHood#133]
I change my server every week to keep it undetectable, so I tried to edit configs to replace the IP address with a domain (by decoding and editing the base64 access key). But when I want to import the edited access key, it fails with the following error message: `Failed to call the addAccessKey api. status: 500`

The edited access key is something like:
```vh://eyJuYW1lIjpudWxsLCJ2IjozLCJzaWQiOjAsInRpZCI6ImZiMjQ2YzBiLTAwMDAtMDAwMC0wMDAwLWFjMmQ5MzM4YTM2MSIsInNlYyI6ImFwWFhIaG5sTVFoMkJLYU1VQy9rWUE9PSIsImlzdiI6ZmFsc2UsImhuYW1lIjoiYmEuc2h5cmF3YXNodS5uZXQiLCJocG9ydCI6NDQzLCJjaCI6InJVUWp6QmRSZ1QrakVsTFQ0MGVaV1g0dThMRT0iLCJwYiI6ZmFsc2UsInVybCI6bnVsbCwiZXAiOlsiZXhhbXBsZS5jb206NDQzIl19```

Decoded:
```{"name":null,"v":3,"sid":0,"tid":"fb246c0b-0000-0000-0000-ac2d9338a361","sec":"apXXHhnlMQh2BKaMUC/kYA==","isv":false,"hname":"ba.shyrawashu.net","hport":443,"ch":"rUQjzBdRgT+jElLT40eZWX4u8LE=","pb":false,"url":null,"ep":["example.com:443"]}```

I think it is possible by editing the "url" field, but I couldn't find anything about it on the wiki page.

**Comment by trudyhood** [comment]
Hi,

I am not sure how did you generate that token, but ep (IPEndPoint) is just IP and port, you can not set hostname for it
![image](https://user-images.githubusercontent.com/72891124/192638522-28bb48d1-a94b-43f6-97f2-3bfa101d2bbe.png)

If you want to use hostname instead of IP, then you should set IsValidHostName (isv) to true, but in this case, you need a valid certificate too.

By the way, blocking HostName may be easier than IP in some cases. Another approach is using "url" in the token field. You can upload your new tokens in some cloud services such as DropBox, VpnHood will look for it and update its token. The new token can have different IP.

**Comment by trudyhood** [comment]
To fix me: You don't need a valid certificate, just use hname and hport and isv. Leave ep to null

**Comment by AmirHosseinCV** [comment]
Thanks a lot! It's working.

> By the way, blocking HostName may be easier than IP in some cases.

When I use a domain name to discover the server, isn't there an option to use a fake hostname for the fake TLS?

> If you want to use hostname instead of IP, then you should set IsValidHostName (isv) to true.

>  Another approach is using "url" in the token field. You can upload your new tokens in some cloud services such as DropBox, VpnHood will look for it and update its token.

Have you documented these somewhere? I couldn't find them on the wiki page.

**Comment by trudyhood** [comment]
> Thanks a lot! It's working.
We feel proud if it is helpful.

> When I use a domain name to discover the server, isn't there an option to use a fake hostname for the fake TLS?
No, we think it would be useless because you already rely on a domain, fake TLS is useful for IP. you can discuss it if you have another point of view.

> Have you documented these somewhere? I couldn't find them on the wiki page.
Not much actually, only the basic. I think you wouldn't get that issue if you create the token by the command line unless there is a bug there.

**Comment by AmirHosseinCV** [comment]
> No, we think it would be useless because you already rely on a domain, fake TLS is useful for IP. you can discuss it if you have another point of view.

I'm not sure if it helps. I have seen that projects usually use a different domain name for fake TLS. For example, in telegram's MTProto proxies. In this case, if the government could figure out that you are using a fake TLS, it may block the domain used in the fake TLS. But I think it's harder to find all domain names pointing to your server's IP address, which makes it harder to get blocked.

And about the documentation...
Yes, you are right. But I found some useful options in your project that are not on the wiki page. It's ok. I just wanted to know if there is complete documentation somewhere else.

**Comment by trudyhood** [comment]
> > No, we think it would be useless because you already rely on a domain, fake TLS is useful for IP. you can discuss it if you have another point of view.
> 
> I'm not sure if it helps. I have seen that projects usually use a different domain name for fake TLS. For example, in telegram's MTProto proxies. In this case, if the government could figure out that you are using a fake TLS, it may block the domain used in the fake TLS. But I think it's harder to find all domain names pointing to your server's IP address, which makes it harder to get blocked.

But detecting and Blocking the valid domain is much easier. They should be crazy to try blocking the fake domain instead the real one. Also when you use a valid domain, you have the chance to use secure DNS. However, I think they have already blocked that protocol too.
Anyway, I believe they can't find your IP if you don't publish it to the public and use it for personal/family/friend use. We tried our best to make sure the VpnHood protocol doesn't have any fingerprints.

**Comment by AmirHosseinCV** [comment]
> But detecting and Blocking the valid domain is much easier.

That's what I'm saying. I don't want to use my real domain for the "hname" parameter. I want to use a fake domain for fake TLS. I want my real domain to be used only for discovering the server.

**Comment by trudyhood** [comment]
> > But detecting and Blocking the valid domain is much easier.
> 
> That's what I'm saying. I don't want to use my real domain for the "hname" parameter. I want to use a fake domain for fake TLS. I want my real domain to be used only for discovering the server.

I meant if you use a fake domain for TLS and a real domain for IP resolving, the blocker will/can go for a real domain, it is easier for them to block that.

**Comment by trudyhood** [comment]
So what will be happened if the firewall blocks the fake TLS handshake? It renders the real hostname useless.

**Comment by AmirHosseinCV** [comment]
It has happened to me before. I was using a fake domain for the fake TLS handshake and used my real domain only to discover the server. After two months of usage, the firewall blocked the fake TLS. I just changed the server, and everything got fixed. There was no need to ask my users to change their configs. 
I think this approach is more secure than using a URL for updating the configs, or using the real domain in every TLS handshake.
Another option is securing the approach of using a URL to get a new access key. A better way could be sending the current access key in a POST request.
Using the existing method, everyone who has the link can get the access key.

**Comment by trudyhood** [comment]
> I was using a fake domain for the fake TLS handshake and used my real domain only to discover the server. After two months of usage, the firewall blocked the fake TLS.
So how was it working after the firewall detected the fake TLS? Fake TLS does not change after you change the server, so if they blocked the fake TLS, it should not work for the new server too. I might encounter a double issue or coincidence.

**Comment by AmirHosseinCV** [comment]
I don't know. Maybe the government only inspects traffic to suspicious servers.
I was thinking of using the hostname alongside a DNS over HTTPS instead of the URL parameter. But I realized that DNS over HTTPS is blocked in my country (for popular servers). So, I will use the "URL" parameter instead.
Thank you for your time and your kind support.

**Comment by free-keyboards** [comment]
Hi. Thanks for your great work.
Is there any solution for domains behind CDN?
I use cloudflare CDN and its [proxies](https://developers.cloudflare.com/fundamentals/get-started/reference/network-ports/) ports to bass traffic to vpn server **BUT** when using android client, it turned domain into ip using DNS and tried to connect to cloudflare's servers...

**Comment by trudyhood** [comment]
> when using android client, it turned domain into ip using DNS and tried to connect to cloudflare's server

It is the the basic of network and DNS. It happens always, you can't connect to site with domain, it is always by IP. The domain will be validated next layer called TLS, which provided by VpnHood too.

>I use cloudflare CDN and its [proxies](https://developers.cloudflare.com/fundamentals/get-started/reference/network-ports/) ports to bass traffic to vpn server BUT when using android client, it turned domain into ip using DNS and tried to connect to cloudflare's servers

You can not use VpnHood (at least now), for any CDN like Cloudflare, they are HTTP proxies while VpnHood is a socks proxy. We may support HTTP in the future but it is not supported. short answer: it doesn't work. Thank you for considering VpnHood.

**Comment by trudyhood** [comment]
We have added support for reverse proxies such as CloudFlare to VpnHood version 725
