### ISSUE TITLE
Disposing. Error! SharpPcap.PcapException: Failed to open

### ISSUE THREAD

**Issue by PtDragon** [vpnhood/VpnHood#134]
Hello!
Client app does not work
Error from log:
Disposing. Error! SharpPcap.PcapException: Failed to open
An object with that GUID or LUID already exists. (Error Code: -2144206839)

**Comment by trudyhood** [comment]
Hi,
Would you submit the log file here or to our support: support@vpnhood.com

**Comment by PtDragon** [comment]
Sent the log

**Comment by trudyhood** [comment]
Thank you,
It looks like there is a problem with the WinDivert installation. Could you delete the following folder and try it again:
Quit VpnHood and run.

rd "%localappdata%\Temp\VpnHood-WinDivertDevice" /S

**Comment by PtDragon** [comment]
The system cannot find the file specified.

чт, 29 сент. 2022 г. в 22:27, Trudy ***@***.***>:

**Comment by trudyhood** [comment]
Have you tried this:
rd "%localappdata%\Temp\VpnHood-WinDivertDevice" /S
