### ISSUE TITLE
Subnet Mask

### ISSUE THREAD

**Issue by TheArshiyan** [vpnhood/VpnHood#137]
Hello , i did a complete review on documentation page but i couldn't find that which subnet mask does vpn hood use?
is it 127.0.0.1 or something else, and is there any feature about setting custom subnet masks?

**Comment by bobvhood** [comment]
Hi,
Subnet mask! Are you talking about the server or client? Please describe your need more.

**Comment by TheArshiyan** [comment]
@bobvhood I'm talking about the server side, for example if i want to specify the ip range for connected clients to be 192.168.1.0/24 , how can i do it, and is there any default subnet for this service?

**Comment by bobvhood** [comment]
There is no mask, you can give an array of IPS or listen to all IPs (0.0.0.0).
https://github.com/vpnhood/VpnHood/wiki/VpnHood-Server-Configuration

**Comment by TheArshiyan** [comment]
can i use the array like this?
"TcpEndPoints": [ "127.1.0.0/24" ],

**Comment by bobvhood** [comment]
No, That's not possible
