### ISSUE TITLE
security vulnerability

### ISSUE THREAD

**Issue by Wjxfi** [vpnhood/VpnHood#138]
open ports – 80

**Comment by trudyhood** [comment]
Hi, would you elaborate more on this issue? Are you talking about clients or servers?  And what is the security concern?
Thank you

**Comment by trudyhood** [comment]
OK, thank you.

**Comment by trudyhood** [comment]
I read the article you sent and checked the server. The port in our public server is open to the default listener of Linux so we didn't care about it. I created a task for the network admin to shut it down or close it with firewalls. We mainly focus on VpnHood software and features, maintaining the servers perform by others. 

You are welcome to mention any other problem you can find in our solution, especially in software code.
Thank you for checking VpnHood
