### ISSUE TITLE
Access Server

### ISSUE THREAD

**Issue by krovlinsergey** [vpnhood/VpnHood#139]
Always when adding a server to the console of the access server, the vpn server has the status "idle"
What I have tried:
- Change the server.
- Load configuration via script
- Upload configuration manually
- Load configuration via console.
- Tried on versions 2.4.304 and 2.4.310
- Tried on different OS (win10 and ubuntu20.04)

screenshot: [https://prnt.sc/EQgKsxiPGRvP](https://prnt.sc/EQgKsxiPGRvP)

**Comment by trudyhood** [comment]
Idle means the server is ready but no one has connected to it.
Can you connect to the server?

**Comment by krovlinsergey** [comment]
No, i cant
@trudyhood 
> 
Info 
| 00:06:22.4409 |  | AppVersion: 2.4.310.0

Info 
| 00:06:22.4411 |  | Time: 2022-10-14 21:06:22Z

Info 
| 00:06:22.4411 |  | OS: Microsoft Windows NT 10.0.19044.0, 64-bit

Info 
| 00:06:22.4411 |  | UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36 Edg/106.0.1370.42

Info 
| 00:06:26.2381 |  | Country: Russian Federation

Info 
| 00:06:26.2382 |  | TokenId: **-9271-f04e553b8582, SupportId: **01

Trac 
| 00:06:26.2397 |  | Checking the Internet connection...

Info 
| 00:06:26.2397 |  | HttpTest: Started, Uri: https://www.google.com/, Timeout: 10000...

Info 
| 00:06:26.2399 |  | HttpTest: Started, Uri: https://www.quad9.net/, Timeout: 10000...

Info 
| 00:06:26.2399 |  | HttpTest: Started, Uri: https://www.microsoft.com/, Timeout: 10000...

Info 
| 00:06:26.8217 |  | HttpTest: Succeeded, Started, Uri: https://www.google.com/.

Trac 
| 00:06:26.8222 |  | Checking the VpnServer ping...

Info 
| 00:06:26.8222 |  | PingTest: Started, RemoteAddress: 79.137.202.27, Timeout: 10000...

Info 
| 00:06:26.8670 |  | PingTest: Succeeded. RemoteAddress: 79.*.*.27.

Trac 
| 00:06:26.8673 |  | Pinging server is OK.

Info => Client
| 00:06:26.8679 |  | UseUdpChannel: True, MinWorkerThreads: 4, CompletionPortThreads: 4

Info => Client
| 00:06:26.8679 |  | Client Version: 2.4.310.0, ClientId: **-b1a1-231367de22c5

Info => Client
| 00:06:26.8679 |  | Client is Connecting

Trac => Client
| 00:06:26.8681 | Session | Connecting to Server: 79.*.*.27:443...

Info 
| 00:06:27.1191 |  | HttpTest: Succeeded, Started, Uri: https://www.microsoft.com/.

Info 
| 00:06:27.3490 |  | HttpTest: Succeeded, Started, Uri: https://www.quad9.net/.

Erro => Client
| 00:06:36.8850 |  | Disposing. Error! System.TimeoutException: The operation has timed out.
   at VpnHood.Common.Util.RunTask(Task task, TimeSpan timeout, CancellationToken cancellationToken) in C:\Users\krovl\source\repos\VpnHood\VpnHood.Common\Util.cs:line 106
   at VpnHood.Client.VpnHoodClient.GetSslConnectionToServer(EventId eventId, CancellationToken cancellationToken) in C:\Users\krovl\source\repos\VpnHood\VpnHood.Client\VpnHoodClient.cs:line 605
   at VpnHood.Client.VpnHoodClient.ConnectInternal(CancellationToken cancellationToken, Boolean redirecting) in C:\Users\krovl\source\repos\VpnHood\VpnHood.Client\VpnHoodClient.cs:line 666
   at VpnHood.Client.VpnHoodClient.Connect() in C:\Users\krovl\source\repos\VpnHood\VpnHood.Client\VpnHoodClient.cs:line 210

Trac => Client
| 00:06:36.8850 |  | Disconnecting...

Info => Client
| 00:06:36.8850 |  | Client is Disconnecting

Trac => Client
| 00:06:36.8850 |  | Shutting down...

Trac => Client
| 00:06:36.8850 |  | Disposing TcpProxyHost...

Trac => Client
| 00:06:36.8851 |  | Disposing Tunnel...

Trac => Client
| 00:06:36.8851 |  | Disposing ProxyManager...

Trac => Client
| 00:06:36.8851 |  | Disposing Nat...

Info => Client
| 00:06:36.8851 |  | Client is Disposed

Info => Client
| 00:06:36.8851 |  | Bye Bye!

Erro 
| 00:06:36.8864 |  | The operation has timed out.

**Comment by trudyhood** [comment]
Can you give us an accessToken so I can try it out?
Please send it to support@vpnhood.com

**Comment by krovlinsergey** [comment]
Problem solved

**Comment by trudyhood** [comment]
Would you share it with us? Is it for the firewall?

**Comment by krovlinsergey** [comment]
I decided to take a detour. I created a new account in console.vpnhood.com and it worked.
