### ISSUE TITLE
Certificate file name inconsistency

### ISSUE THREAD

**Issue by varatalu** [vpnhood/VpnHood#14]
Hi, i was testing the project and i found that there's a ssl error, which comes from the server using local ip instead of the public ip for the cert file.

e.g. if you generate the certificate and tokens using
`gen -name "vpn" -ep [server-public-ip] -maxClient 6`
the pfx file will be created using the provided public ip endpoint, but on every connection the server checks for a file named with the local ip and throws an ssl error because of the missing file.
![image](https://user-images.githubusercontent.com/36763595/104217040-896b8880-5443-11eb-84d5-2a53394db6cc.png)

renaming the file to the local ip solves the issue, i thought this would help.

**Comment by trudyhood** [comment]
Hi,
Sorry I missed the issue notification.
It has been fixed and will be released soon.
Meanwhile you can use -p switch

dotnet VpnHoodServer.dll run -p 5555

Thank you for reporting

**Comment by trudyhood** [comment]
Sorry for such delay, I had little problem in getting github issue notification. I will look at it and will get back to you.

**Comment by trudyhood** [comment]
@varatalu Would you let me know that did your server have a Amazon Elastic IP or something like that?

**Comment by trudyhood** [comment]
Fixed

**Comment by varatalu** [comment]
> 
> 
> @varatalu Would you let me know did your server has an Amazon Elastic IP or something like that?

sorry for answering so late, i just used a static public ip and a linux container built from source

**Comment by trudyhood** [comment]
I am not sure about your case, but this happen when the internal IP -that server is listening, is different than its public IP. By the way, this issue has been solved in version v1.1.187 and it is available for download. 
Thank you for evaluating VpnHood!
