### ISSUE TITLE
android app is connect then disconnect

### ISSUE THREAD

**Issue by eleguni** [vpnhood/VpnHood#143]
Hello
First off, I want to explain what I did do. I used VpnHood.Samples.SimpleClient.Droid source code as my client app and used my clientId(accessKey/public in https://console.vpnhood.com/ ) instead of the example source clientId. I purchased a windows server. I extracted the VpnHoodServer.zip file and got accessKey("vh://....." ) with Cmd. I copied the accessKey on the example source code, but it changes to disconnect whenever I click on connect. Please guide me on what I should have done.
should I do anything on the vpnHood dashboard?
this is the Apk file:
https://easyupload.io/q3pcog

**Comment by bobvhood** [comment]
Hi,
Can you connect to your server with our official VpnHood Client?

**Comment by eleguni** [comment]
I added a new server on the VpnHood windows version, and also deactivated my windows server's firewall.
but I faced "No connection could be made because the target machine actively refused it" error.
server error message :
[https://ibb.co/8YGVTZ0](url)

**Comment by bobvhood** [comment]
Is Windows 2012 server? If yes, it doesn't work.

**Comment by eleguni** [comment]
its 2016 - 64 bit

**Comment by eleguni** [comment]
I can share my server specification so that you to find the problem. If you agree, share your email or discord Id.

**Comment by bobvhood** [comment]
First, we have to test it on Windows Server 2016. If that works we will get back to you, I recommended you install it on a Linux till we find out the issue.

**Comment by eleguni** [comment]
Ok, I don't have a Linux server. I will wait for your response.

**Comment by eleguni** [comment]
is there any difference that what Linux server I use? I mean centos(7,8,etc... ) or ubntu?

**Comment by trudyhood** [comment]
We constantly check it in ubuntu. It should work on others, too but we don't test with them.

**Comment by eleguni** [comment]
I tried the Vpn app with the ubuntu server I can connect with the windows version but for the android app, I have a previous issue, the connect button connects and then disconnect automatically.

**Comment by trudyhood** [comment]
That's weird, both use a single code base. 
1. Would you share the log of the client?
2. Would you test it with another phone on the same network?

**Comment by eleguni** [comment]
do you have any idea why it happens as you can see I ran this command ` sudo su -c "bash <( wget -qO- https://github.com/vpnhood/VpnHood/releases/latest/download/install-linux.sh)"`
then this command
`sudo dotnet /opt/VpnHoodServer/launcher/run.dll gen`
and as you can see the result is  `sudo: dotnet: command not found` despite I installed the dotnet6 the server is Linux Ubntu 20 - 64 bit.

![Screenshot 2022-11-01 234006](https://user-images.githubusercontent.com/29005428/199337256-14eef591-12ee-4904-a51f-cd2f34d7ebf1.png)

**Comment by trudyhood** [comment]
@eleguni 
What is your Linux distribution and version?
It looks dotnet doesn't register properly. try to install Microsoft .NET Runtime manually:
https://learn.microsoft.com/en-us/dotnet/core/install/linux-ubuntu
