### ISSUE TITLE
Entity Framework - why not?

### ISSUE THREAD

**Issue by krovlinsergey** [vpnhood/VpnHood#147]
I wanted to ask why your project uses a file system to store data? After all, there is a more productive and flexible "entity framework" with sqlite

**Comment by trudyhood** [comment]
Thank you for your comment.

VpnHood Server uses a very simple lightweight built-in FileAccessServer which doesn't support many features to keep the core simple with minimum dependencies.  For advanced User Management, you need to implement a RestAccessServer or our use our VpnHood Access Server.

I close this issue but you can add any note here if you need more information.
