### ISSUE TITLE
domain instead of ip

### ISSUE THREAD

**Issue by alonelove7** [vpnhood/VpnHood#151]
Follow of recent discussion
 https://github.com/vpnhood/VpnHood/discussions/150

add command line for use domain instead of ip on Server

**Comment by Amirali121212** [comment]
> Follow of recent discussion #150
> 
> add command line for use domain instead of ip on Server

سرور ؟

**Comment by bobvhood** [comment]
Hi @Amirali121212 
GitHub doesn't translate issues. What is your question?

**Comment by alonelove7** [comment]
hi dear 
in new update
that option added or not ?

**Comment by trudyhood** [comment]
In progress

**Comment by trudyhood** [comment]
We have implemented this feature on File Access Server if you are still interested. Check version 326 and use -domain options. It uses your certificate domain instead IP. Feel free to ask any questions you may have about it.

**Comment by Amirali121212** [comment]
سلام متاسفانه چیزی اضافه نشده

در تاریخ شنبه ۱۹ نوامبر ۲۰۲۲،‏ ۰۹:۵۲ Alone ***@***.***> نوشت:

**Comment by trudyhood** [comment]
Hi. Would you were in English?

**Comment by Amirali121212** [comment]
I'm looking for a server for a hood app, but if someone can teach me how to
make one, that would be great.

در تاریخ شنبه ۱۹ نوامبر ۲۰۲۲،‏ ۰۲:۲۶ Bob ***@***.***> نوشت:

**Comment by trudyhood** [comment]
It is easy. First, you need to buy a Linux or windows server or VPS from the server. You can go to our access server and add your server there if you already have. 
https://github.com/vpnhood/VpnHood/wiki/VpnHood-Access-Server

We can also install it for you if you have a server. You can send your server credential to us if you are interested: support@vpnhood.com
