### ISSUE TITLE
server config for each 100 CCU user

### ISSUE THREAD

**Issue by eleguni** [vpnhood/VpnHood#152]
Hello
I want to know with the Vpnhood configuration what server configuration I need for each 100 CCU user.
and is there any CCU limitation with the VPNHood?

**Comment by trudyhood** [comment]
He eleguni, Sorry to ask but what is CCU? :)

**Comment by eleguni** [comment]
No that's ok :)
I mean Concurrent users

**Comment by trudyhood** [comment]
Almost any VPS can handle 100 Concurrent Users unless all of them plan to make it down deliberately. I believe you don't need to worry about 100 CCU per server👍

**Comment by eleguni** [comment]
yes, I know I'm thinking about it later if someone had 10k concurrent users is there any limitation by the Vpnhood configuration? 
or
I want to know what server config I need for these quantity users.
I mean how much ram and CPU cores the server needed

**Comment by bobvhood** [comment]
Hi eleguni,
I am afraid to say that we are still evaluating this. The limitation is usually the bandwidth, don't forget that VPN uses twice the bandwidth of users usage. I am sorry that I couldn't give you an answer, It is os depends on your user's culture and usages, such as do they usually use streaming such as Netflix or torrents. It will be great if you share your experience.

**Comment by eleguni** [comment]
sure if I reach that point I will share my experience with you.
as I understood, so the most important thing in the mentioned situation is having an unlimited bandwidth server.
is there any difference between the Linux server and the windows server? I mean in the performance?

**Comment by bobvhood** [comment]
Performance might be the same, but I recommend you Linux because they are cheaper, lighter, and has more memory available at the same price. The most important thing is that we check it on Linux regularly and create the installation package and updater for it.

**Comment by eleguni** [comment]
Ok, thank you for the guidance.
one more thing how do I edit this message?
![photo_2022-11-01_12-39-02](https://user-images.githubusercontent.com/29005428/199205497-9bd83d3f-6f5c-44ac-bea2-be93c4b02541.jpg)

**Comment by trudyhood** [comment]
This is the message of OS and user intent. We don't have access to its content, nor can we skip it. Android shows it for any VPN app before establishing the connection.

**Comment by eleguni** [comment]
I just want to change "VPNHood" and put my app's name instead, the user confuses that using blablaVpn and VPNhood wants to setup...

**Comment by trudyhood** [comment]
I will look at it to find where it comes from and will get back to you; We will put the name as a parameter in VpnHood components so you can change it.

**Comment by trudyhood** [comment]
@eleguni 
I found and remove the ServiceName label from Android Device. Please update the VpnHood.Client.Device.Android from nuget server and rebuild your project. Let me know if it doesn't work.

**Comment by eleguni** [comment]
Great! works perfectly.
