### ISSUE TITLE
google chrome does not work on android

### ISSUE THREAD

**Issue by SphrGhfri** [vpnhood/VpnHood#153]
All applications work. But Google Chrome gives internet connection error. But other browsers work. I tested on several mobile phones. Apparently, they do not work on Android 12 and 11 with the latest version of Chrome. With the same connection, Chrome works on Windows.

**Comment by trudyhood** [comment]
Please make sure that you don't use UDP and let me know. It should be "NO UDP (Slower)"
![image](https://user-images.githubusercontent.com/72891124/200097971-f75221d0-0989-4227-bf7b-8f35dd56fde1.png)

**Comment by SphrGhfri** [comment]
I tested it on no udp, Google Chrome does not work. I tested on another device, it works on a device with Chrome version 105.0 and android version 10. But it does not work on Chrome version 107.0 or 106.0 versions on android 10, 11 and 12.
I think it has nothing to do with the Android version and it is from the Chrome version.
Now, to make sure that the problem is not with the IP of server (That my server ip is not blocked by Google), I requested a new server. I will test it on the new server tomorrow and let you know.

**Comment by trudyhood** [comment]
Please update chrome 106 or 107 again, and let's see if it will work or not. Maybe something in its cache caused the issue.

**Comment by SphrGhfri** [comment]
After update, I cleared cache and all data. but still not working.
Even after changing the dns setting (off, on and on cloudflare), there is still no change...
but with other VPNs or without vpn it works fine.

**Comment by trudyhood** [comment]
Are you using a Private Server or our VpnHood public servers?
Can you send me an AccessKey to your private server if you use a private server? Please send it to me at trudy@vpnhood.com

**Comment by SphrGhfri** [comment]
Yeah i'm using a Private Server. I sent you access key.

**Comment by trudyhood** [comment]
Thank you, The good news is that we could simulate the issue, but we need time to fix it. It does not happen on our servers. Would you send me the log of your Vpnhood server? What is your VpnHood Server version?

**Comment by SphrGhfri** [comment]
Sorry, I don't know where to see the log and version.
I installed vpnhood with the command I got from inside the console.
can you guide me?

**Comment by SphrGhfri** [comment]
here is log file in log-archive:

2022-11-01 21:31:19.2926 | Info |
 Initializing ResetAccessServer. BaseUrl: https://access.vpnhood.com/api/agent/

2022-11-01 21:31:19.5319 | Info |
 VpnHoodServer, Version=2.4.310.0, Culture=neutral, PublicKeyToken=null

2022-11-01 21:31:19.6017 | Info |
 OS: Unix 5.4.0.29, 64-bit
Linux version 5.4.0-29-generic (buildd@lgw01-amd64-035) (gcc version 9.3.0 (Ubuntu 9.3.0-10ubuntu2))>

2022-11-01 21:31:20.9427 | Info | Server
 MinWorkerThreads: 1, MinCompletionPortThreads: 30, MaxWorkerThreads: 32767, MaxCompletionPortThread>

2022-11-01 21:31:20.9939 | Info | Server
 Configuring by the Access Server...

2022-11-01 21:31:34.1991 | Info | Server
 ServerConfig: {"TrackingOptions":{"LogLocalPort":false,"LogClientIp":false},"SessionOptions":{"Time>

2022-11-01 21:31:34.2023 | Info | Server
 Starting TcpHost...

2022-11-01 21:31:34.2066 | Info | Server
 Start listening on 138.*.*.13:443

2022-11-01 21:31:34.2955 | Info | Server
 Set UpdateStatusInterval to 60 seconds.

2022-11-01 21:31:34.3053 | Info | Server
 Server is ready!

2022-11-01 21:33:02.2798 | Info |
 Syncing all sessions and terminating the server...

2022-11-01 21:33:02.2905 | Info | Server
 Shutting down...

2022-11-01 21:33:02.4043 | Info | Server
 Stop listening on 138.*.*.13:443

2022-11-01 21:33:02.4097 | Info | Server
 Bye Bye!

**Comment by SphrGhfri** [comment]
I will email you the entire log folder.

**Comment by trudyhood** [comment]
Hi @SphrGhfri 
We found the issue and the resolution. It looks like your server IPv6 has not been configured properly. Chrome >=106 prefers using IPv6 and VpnHood supports IPv6 too so VpnHood tries to tunnel IPv6 on IPv4 but your server doesn't route IPv6 to the destination. So you need to either disable IPv6 on your server or configure it properly. 
We will also try to find a way to detect this misconfiguration and disable IPv6 on the client side but it takes time. Let me know when you fix this issue.

**Comment by SphrGhfri** [comment]
it works !!
I called my vps provider and they configured the ipv6 for me. Chrome works now.
Thank you. You have guided me very well
