### ISSUE TITLE
Android app disconnects

### ISSUE THREAD

**Issue by eleguni** [vpnhood/VpnHood#154]
Hello
The android build disconnects automatically every about 30 minutes or 1 hour, either if the screen is off or during using the phone, how do I solve this?
tested on android 12,11.

**Comment by trudyhood** [comment]
It should try to reconnect after that. Perhaps your connection is not reliable. I have no idea what happened after 30 min or 60 and didn't get a such report from other users. Let me know if you have any ideas.

**Comment by trudyhood** [comment]
I have got an Idea. Your user may share their tokens and you set the maximum number of clients for a token. So the first ones will be disconnected sooner or later.

**Comment by trudyhood** [comment]
You need to generate a ClientId for each user and save/restore it in the user's device. Each user device clientId must be different. Otherwise, all users are treated as one user.

VpnHood.Client.App library should manage this, but if you use the VpnHoodClient library, you need to handle a bunch of work.

**Comment by eleguni** [comment]
I did something like this could you see if it works or not?
```
       if (!Preferences.ContainsKey("clientId"))
                {
                    string guid = new Guid().ToString();
                    Preferences.Set("clientId", guid);
                  //  clientId = Guid.Parse(guid);

                }
                Console.WriteLine("clientid " + clientId);
                clientId = Guid.Parse(Preferences.Get("clientId", "NotFound"));
```

**Comment by trudyhood** [comment]
Sounds ok. make sure the Preferences are persistent.
