### ISSUE TITLE
Error in SimpleClient Windows

### ISSUE THREAD

**Issue by eleguni** [vpnhood/VpnHood#156]
Hello 
I run the vpnHood source in visual studio 2022 and I face with this error 
`System.AggregateException: 'One or more errors occurred. (Access denied! Could not open WinDivert driver! Make sure the app is running with admin privilege.)'`
![Screenshot 2022-11-10 171621](https://user-images.githubusercontent.com/29005428/201115209-c4a78b3f-f0f2-450a-9d08-78c32e30930b.png)

**Comment by bobvhood** [comment]
Hi, You need to run your Visual Studio as Administrator. 
![image](https://user-images.githubusercontent.com/92276967/201490947-b413eda3-a17b-4de7-ad39-027a4e0dc1f2.png)
