### ISSUE TITLE
Split Tunneling by Apps & Countries

### ISSUE THREAD

**Issue by ErcinDedeoglu** [vpnhood/VpnHood#159]
Hello,
I'm looking for this feature which is mentioned in README:
`Split Tunneling by Apps & Countries`

But when I checked the Windows Client, it doesn't have this option. (by Apps)
I am looking for the same option as ProxyCap app is doing.

I appreciate any help you can provide.

**Comment by bobvhood** [comment]
Hi, 
App filtering is impossible in windows, and you can see this feature on Android Devices.
If you find any packet filtering on windows that support App, please share it with us :)

**Comment by ErcinDedeoglu** [comment]
Hi @bobvhood, 
I appreciate your fast reply.
I checked lots of examples and tried reverse engineer some of them.
The most famous is Proxifier and ProxyCap, which are doing App level redirection.

As I understand, Proxifier is doing DLL injection to change communication during the advantage of Ws2_32.dll. I tried this and working well on my cases.
But the critical side is it's doing DLL injection and memory editing of remote processes. This means Windows Memory Integrity and other antivirus software can be recognized as malware. And also can face other problems like "anti-debugger".

But ProxyCap has a different approach, and it's working great. Which technique are they using? Do you have an idea?
