### ISSUE TITLE
old Docker image

### ISSUE THREAD

**Issue by SSgumS** [vpnhood/VpnHood#161]
Hello
The latest version in docker hub is [v2.4.304](https://hub.docker.com/layers/vpnhood/vpnhoodserver/v2.4.304/images/sha256-efd2922cc7b8b600ee7cf53dbe7b3ea01809bc677c07f7bfd1e890cffa1b57b6?context=explore) that is lagged behind GitHub releases. Is there any issue relating to the docker image that forced the image to lag?

**Comment by trudyhood** [comment]
Hi Everyone. Make sure you have a copy of appsettings.json here. The new version will look for a storage folder and we can't make it compatible with the previous docker image. The servers will stop working if they don't find the appsettings.json
/opt/VpnHoodServer/storage/appsettings.json

**Comment by SSgumS** [comment]
Hello
It has been a long time since docker images in docker hub has been updated. By the recent update of vpnhood client and the deprecation of v3 protocol, docker-based vpnhood servers can't be used anymore.
Is there any reason behind the delayed release of docker images?
Thanks

**Comment by trudyhood** [comment]
It was due to a login problem in the automation process. Check it out again, it must work.

**Comment by SSgumS** [comment]
Thank you very much. 
Is it possible for you to put v3.0.414 on docker hub, in addition to the latest version? That version was a transient bridge between v3 and v4; the version that support both protocols. It would be beneficial to be available on docker hub as an archived important version.

**Comment by trudyhood** [comment]
> Thank you very much. Is it possible for you to put v3.0.414 on docker hub, in addition to the latest version? That version was a transient bridge between v3 and v4; a version that support both protocols. It would be beneficial to be available on docker hub as an archived important version.

I am so sorry, but that version is not available as we don't keep archives of docker images locally.
