### ISSUE TITLE
Using VpnHood on local network

### ISSUE THREAD

**Issue by karnilamit** [vpnhood/VpnHood#166]
Hi,

I am trying to setup VpnHood server on my local network for testing purposes. I am using server and client version 2.4.318. The server is installed using the instructions provided on Wiki. While creating the AccessKey I used -ep option as below

` dotnet /opt/VpnHoodServer/2.4.310/VpnHoodServer.dll gen -ep 10.11.11.66`

For client I am compiling the sample VpnHood Android Application by making the following changes (since I need to test the Vpn only for local network and not for internet traffic)

```
 ClientOptions Options = new ClientOptions();
                Console.WriteLine("Client Options Version " + Options.Version);
                Console.WriteLine("Client Options UseUdpChannel " + Options.UseUdpChannel);
                Console.WriteLine("Client Options UserAgent " + Options.UserAgent);
                Console.WriteLine("Client MaxTcpDatagramChannelCount " + Options.MaxDatagramChannelCount);
                Options.MaxDatagramChannelCount = 1;
                Options.ExcludeLocalNetwork = false;

                Options.PacketCaptureIncludeIpRanges = new[]{
                    VpnHood.Common.Net.IpRange.Parse("10.10.50.30 - 10.10.50.40")
               };
```

10.10.50.30-10.10.50.40 is the range of IP address that I need to be routed through VpnHood, all other request should be direct. I am able to access an http server installed on 10.10.50.35 without VpnHood, however when I use VpnHood sample application compiled to above changes the access does not work. On my http server log I can see a request being hit and response being sent but the response never reaches the client. What could be wrong? I remember testing this long before with older versions of VpnHood and it worked like a charm.

Below is the snippet of the server logs:

```
dotnet /opt/VpnHoodServer/launcher/run.dll start
/opt/VpnHoodServer/publish.json

Launching 2.4.310/VpnHoodServer.dll!

2022/11/18 16:46:51.004 | Info |
 Using FileAccessServer. AccessFolder: /opt/VpnHoodServer/access

2022/11/18 16:46:51.084 | Info |
 VpnHoodServer, Version=2.4.310.0, Culture=neutral, PublicKeyToken=null

2022/11/18 16:46:51.084 | Info |
 OS: Unix 5.4.0.107, 64-bit
Linux version 5.4.0-107-generic (buildd@lcy02-amd64-058) (gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1)) #121-Ubuntu SMP Thu Mar 24 16:04:27 UTC 2022

2022/11/18 16:46:51.490 | Info | Server
 MinWorkerThreads: 8, MinCompletionPortThreads: 240, MaxWorkerThreads: 32767, MaxCompletionPortThreads: 32767,

2022/11/18 16:46:51.492 | Info | Server
 Configuring by the Access Server...

2022/11/18 16:46:51.755 | Info | Server
 ServerConfig: {"TrackingOptions":{"LogLocalPort":false,"LogClientIp":false},"SessionOptions":{"Timeout":"00:10:00","UdpTimeout":"00:01:00","TcpTimeout":"00:15:00","IcmpTimeout":"00:00:30","SyncCacheSize":100000000,"SyncInterval":"00:20:00","MaxDatagramChannelCount":8,"MaxUdpPortCount":0,"TcpBufferSize":8192},"UdpPort":0,"ConfigCode":"00000000-0000-0000-0000-000000000000","TcpEndPoints":["0.0.0.0:443","[::]:443"],"UpdateStatusInterval":"00:02:00"}

2022/11/18 16:46:51.755 | Info | Server
 Starting TcpHost...

2022/11/18 16:46:51.759 | Info | Server
 Start listening on 0.0.0.0:443

2022/11/18 16:46:51.767 | Info | Server
 Start listening on :::443

2022/11/18 16:46:51.767 | Info | Server
 Set UpdateStatusInterval to 120 seconds.

2022/11/18 16:46:51.767 | Info | Server
 Server is ready!

2022/11/18 16:46:59.102 | Info | Server => RemoteEp: 10.*.*.14:43139 Session
 Processing hello request... ClientEp: 10.*.*.14:43139

2022/11/18 16:46:59.114 | Info | Server => RemoteEp: 10.*.*.14:43139 Session
 Creating Session... TokenId: **-ace3-3237f6dc4e78, ClientId: **-90af-b118fe47ed0b, ClientVersion: 2.4.318

2022/11/18 16:46:59.146 | Info | Server => RemoteEp: 10.*.*.14:43139
 New session has been created. SessionId: 1

2022/11/18 16:53:59.509 | Info | Server => RemoteEp: 10.*.*.14:33085 => SessionId: 1
 Session closed by access server. ErrorCode: SessionClosed

2022/11/18 16:55:26.445 | Info | Server => RemoteEp: 10.*.*.14:44715 Session
 Processing hello request... ClientEp: 10.*.*.14:44715

2022/11/18 16:55:26.445 | Info | Server => RemoteEp: 10.*.*.14:44715 Session
 Creating Session... TokenId: **-ace3-3237f6dc4e78, ClientId: **-90af-b118fe47ed0b, ClientVersion: 2.4.318

2022/11/18 16:55:26.445 | Info | Server => RemoteEp: 10.*.*.14:44715
 New session has been created. SessionId: 2


```
Thanks,
AK

**Comment by trudyhood** [comment]
Set PacketCaptureIpRangesFilterMode =FilterMode.Include
Send the client log if it doesn't work

**Comment by karnilamit** [comment]
Thanks for your reply. I am using the Android Sample App (VpnHood.Samples.SimpleClient.Droid) The PacketCaptureIpRangesFilterMode =FilterMode.Include is in UserSettings and not a VpnHood client option. Can you kindly guide me how to use it in the Android Sample App?

**Comment by trudyhood** [comment]
I recommend you use VpnHood.Client.App library. Anyway, for VpnHoodClient you need to set this in VpnHoodClient options:
ClientOptions.PacketCaptureIncludeIpRanges
It only includes; to exclude some IP you need to reverse the IpRanges.
Check VpnHood.Client.App source code to see how it creates VpnHoodClient.
![image](https://user-images.githubusercontent.com/72891124/203153939-c4cb79b8-ed2c-401a-ac8c-5d0aabe34e70.png)

Be aware you can't our may ranges in PacketCaptureIncludeIpRanges due to hardware limitations. Consider using IIpFilter. It is much slower but doesn't have that limitation.

**Comment by karnilamit** [comment]
I suppose that's what I did in the code shared above. Re-posting again. 

 ```
                ClientOptions Options = new ClientOptions();
                Options.MaxDatagramChannelCount = 1;
                Options.ExcludeLocalNetwork = false;

                Options.PacketCaptureIncludeIpRanges = new[]{
                    VpnHood.Common.Net.IpRange.Parse("10.10.50.30 - 10.10.50.40")
               };
```

**Comment by trudyhood** [comment]
Please give me the client log

**Comment by karnilamit** [comment]
Hi @trudyhood 
Sorry for my ignorance. But how can I get detailed logs for client? I can always run it in debug mode and share the console logs but I guess you are looking for a more detailed trace. Also how can I enabled trace logging for server?

**Comment by trudyhood** [comment]
Yes, you need to set up its logger. Are you trying to test the VPN with a domain name or IP address?

**Comment by karnilamit** [comment]
Can you please let me know how to setup the logger instance? I am accessing it using IP address.

**Comment by trudyhood** [comment]
You can create an ILogger and set it to VhLogger.Instance such
such as 
VhLogger.Instance = VhLogger.CreateConsoleLogger(); // or something else

**Comment by karnilamit** [comment]
If I set it up for console logging I get below exception while running the App in simulator
`An error occurred while writing to logger(s). (Operation is not supported on this platform.)
`
Any other way?

**Comment by trudyhood** [comment]
Perhaps Android does not have Console. Try to provide an ILogger like the following one:
https://github.com/vpnhood/VpnHood/blob/d57309be87e47d99d4387344b75be5f1e6d86894/VpnHood.App.Launcher/SimpleLogger.cs

Goodluck

**Comment by karnilamit** [comment]
Below are the required logs. The http server is running on 10.10.50.35:12913 The packet capture on client is working fine (which is shown in the logs). I can see the http request reaching my server but the response never gets to the client.

`> am start -a "android.intent.action.MAIN" -c "android.intent.category.LAUNCHER" -n "com.vpnhood.samples.simpleclient.droid/crc645e76e89519cc4178.MainActivity"
> Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.vpnhood.samples.simpleclient.droid/crc645e76e89519cc4178.MainActivity }
[pleclient.droi] Late-enabling -Xcheck:jni
[pleclient.droi] Unquickening 12 vdex files!
[pleclient.droi] Unexpected CPU variant for X86 using defaults: x86_64
[NetworkSecurityConfig] No Network Security Config specified, using platform default
[NetworkSecurityConfig] No Network Security Config specified, using platform default
[debug-app-helper] Checking if libmonodroid was unpacked to /data/app/~~ZeDz9aWO5VxpPsqmxTLoqA==/com.vpnhood.samples.simpleclient.droid-RB1PWxh7zpiFIHmHFHz4Tw==/lib/x86_64/libmonodroid.so
[debug-app-helper] Native libs extracted to /data/app/~~ZeDz9aWO5VxpPsqmxTLoqA==/com.vpnhood.samples.simpleclient.droid-RB1PWxh7zpiFIHmHFHz4Tw==/lib/x86_64, assuming application/android:extractNativeLibs == true
[debug-app-helper] Setting up for DSO lookup in app data directories
[debug-app-helper] Added filesystem DSO lookup location: /data/app/~~ZeDz9aWO5VxpPsqmxTLoqA==/com.vpnhood.samples.simpleclient.droid-RB1PWxh7zpiFIHmHFHz4Tw==/lib/x86_64
[debug-app-helper] Using runtime path: /data/app/~~ZeDz9aWO5VxpPsqmxTLoqA==/com.vpnhood.samples.simpleclient.droid-RB1PWxh7zpiFIHmHFHz4Tw==/lib/x86_64
[debug-app-helper] checking directory: `/data/user/0/com.vpnhood.samples.simpleclient.droid/files/.__override__/lib`
[debug-app-helper] directory does not exist: `/data/user/0/com.vpnhood.samples.simpleclient.droid/files/.__override__/lib`
[debug-app-helper] Checking whether Mono runtime exists at: /data/user/0/com.vpnhood.samples.simpleclient.droid/files/.__override__/libmonosgen-2.0.so
[debug-app-helper] Checking whether Mono runtime exists at: /data/app/~~ZeDz9aWO5VxpPsqmxTLoqA==/com.vpnhood.samples.simpleclient.droid-RB1PWxh7zpiFIHmHFHz4Tw==/lib/x86_64/libmonosgen-2.0.so
[debug-app-helper] Mono runtime found at: /data/app/~~ZeDz9aWO5VxpPsqmxTLoqA==/com.vpnhood.samples.simpleclient.droid-RB1PWxh7zpiFIHmHFHz4Tw==/lib/x86_64/libmonosgen-2.0.so
[pleclient.droi] Attempt to remove non-JNI local reference, dumping thread
[monodroid] Creating public update directory: `/data/user/0/com.vpnhood.samples.simpleclient.droid/files/.__override__`
[pleclient.droi] Attempt to remove non-JNI local reference, dumping thread
[monodroid-debug] Trying to initialize the debugger with options: --debugger-agent=transport=dt_socket,loglevel=0,address=10.0.2.2:65269,embedding=1
[monodroid-gc] GREF GC Threshold: 46080
Loaded assembly: /data/data/com.vpnhood.samples.simpleclient.droid/files/.__override__/VpnHood.Samples.SimpleClient.Droid.dll
Loaded assembly: /data/data/com.vpnhood.samples.simpleclient.droid/files/.__override__/VpnHood.Tunneling.dll
Loaded assembly: /data/data/com.vpnhood.samples.simpleclient.droid/files/.__override__/Microsoft.Bcl.AsyncInterfaces.dll [External]
Loaded assembly: /data/data/com.vpnhood.samples.simpleclient.droid/files/.__override__/Microsoft.Extensions.Configuration.Abstractions.dll [External]
Loaded assembly: /data/data/com.vpnhood.samples.simpleclient.droid/files/.__override__/Microsoft.Extensions.Configuration.Binder.dll [External]
Loaded assembly: /data/data/com.vpnhood.samples.simpleclient.droid/files/.__override__/Microsoft.Extensions.Configuration.dll [External]
Loaded assembly: /data/data/com.vpnhood.samples.simpleclient.droid/files/.__override__/Microsoft.Extensions.DependencyInjection.Abstractions.dll [External]
Loaded assembly: /data/data/com.vpnhood.samples.simpleclient.droid/files/.__override__/Microsoft.Extensions.DependencyInjection.dll [External]
Loaded assembly: /data/data/com.vpnhood.samples.simpleclient.droid/files/.__override__/Microsoft.Extensions.Logging.Abstractions.dll [External]
Loaded assembly: /data/data/com.vpnhood.samples.simpleclient.droid/files/.__override__/Microsoft.Extensions.Logging.Configuration.dll [External]
Loaded assembly: /data/data/com.vpnhood.samples.simpleclient.droid/files/.__override__/Microsoft.Extensions.Logging.Console.dll [External]
Loaded assembly: /data/data/com.vpnhood.samples.simpleclient.droid/files/.__override__/Microsoft.Extensions.Logging.dll [External]
Loaded assembly: /data/data/com.vpnhood.samples.simpleclient.droid/files/.__override__/Microsoft.Extensions.Options.ConfigurationExtensions.dll [External]
Loaded assembly: /data/data/com.vpnhood.samples.simpleclient.droid/files/.__override__/Microsoft.Extensions.Options.dll [External]
Loaded assembly: /data/data/com.vpnhood.samples.simpleclient.droid/files/.__override__/Microsoft.Extensions.Primitives.dll [External]
Loaded assembly: /data/data/com.vpnhood.samples.simpleclient.droid/files/.__override__/PacketDotNet.dll [External]
Loaded assembly: /data/data/com.vpnhood.samples.simpleclient.droid/files/.__override__/System.Diagnostics.DiagnosticSource.dll [External]
Loaded assembly: /data/data/com.vpnhood.samples.simpleclient.droid/files/.__override__/System.Text.Encodings.Web.dll [External]
Loaded assembly: /data/data/com.vpnhood.samples.simpleclient.droid/files/.__override__/System.Text.Json.dll [External]
Loaded assembly: /data/data/com.vpnhood.samples.simpleclient.droid/files/.__override__/VpnHood.Client.Device.Android.dll
Loaded assembly: /data/data/com.vpnhood.samples.simpleclient.droid/files/.__override__/VpnHood.Client.Device.dll
Loaded assembly: /data/data/com.vpnhood.samples.simpleclient.droid/files/.__override__/VpnHood.Client.dll
Loaded assembly: /data/data/com.vpnhood.samples.simpleclient.droid/files/.__override__/VpnHood.Common.dll
Loaded assembly: /data/data/com.vpnhood.samples.simpleclient.droid/files/.__override__/Xamarin.AndroidX.Annotation.dll [External]
Loaded assembly: /data/data/com.vpnhood.samples.simpleclient.droid/files/.__override__/Xamarin.AndroidX.Arch.Core.Common.dll [External]
Loaded assembly: /data/data/com.vpnhood.samples.simpleclient.droid/files/.__override__/Xamarin.AndroidX.Browser.dll [External]
Loaded assembly: /data/data/com.vpnhood.samples.simpleclient.droid/files/.__override__/Xamarin.AndroidX.Collection.dll [External]
Loaded assembly: /data/data/com.vpnhood.samples.simpleclient.droid/files/.__override__/Xamarin.AndroidX.Core.dll [External]
Loaded assembly: /data/data/com.vpnhood.samples.simpleclient.droid/files/.__override__/Xamarin.AndroidX.Lifecycle.Common.dll [External]
Loaded assembly: /data/data/com.vpnhood.samples.simpleclient.droid/files/.__override__/Xamarin.AndroidX.Lifecycle.Runtime.dll [External]
Loaded assembly: /data/data/com.vpnhood.samples.simpleclient.droid/files/.__override__/Xamarin.AndroidX.MultiDex.dll [External]
Loaded assembly: /data/data/com.vpnhood.samples.simpleclient.droid/files/.__override__/Xamarin.AndroidX.VersionedParcelable.dll [External]
Loaded assembly: /data/data/com.vpnhood.samples.simpleclient.droid/files/.__override__/Xamarin.Essentials.dll [External]
Loaded assembly: /data/data/com.vpnhood.samples.simpleclient.droid/files/.__override__/Xamarin.Google.Guava.ListenableFuture.dll [External]
Loaded assembly: /data/data/com.vpnhood.samples.simpleclient.droid/files/.__override__/Mono.Android.dll [External]
Loaded assembly: /data/data/com.vpnhood.samples.simpleclient.droid/files/.__override__/Java.Interop.dll [External]
Loaded assembly: /data/data/com.vpnhood.samples.simpleclient.droid/files/.__override__/System.dll [External]
Loaded assembly: /data/data/com.vpnhood.samples.simpleclient.droid/files/.__override__/Mono.Security.dll [External]
[pleclient.droi] Attempt to remove non-JNI local reference, dumping thread
[libEGL] loaded /vendor/lib64/egl/libEGL_emulation.so
[libEGL] loaded /vendor/lib64/egl/libGLESv1_CM_emulation.so
[libEGL] loaded /vendor/lib64/egl/libGLESv2_emulation.so
Loaded assembly: /data/data/com.vpnhood.samples.simpleclient.droid/files/.__override__/netstandard.dll [External]
[HostConnection] HostConnection::get() New Host Connection established 0x7de89bb95b50, tid 6594
[HostConnection] HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache ANDROID_EMU_vulkan_ignored_handles ANDROID_EMU_has_shared_slots_host_memory_allocator ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit ANDROID_EMU_sync_buffer_data ANDROID_EMU_read_color_buffer_dma GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_3_0 
[OpenGLRenderer] Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
[EGL_emulation] eglCreateContext: 0x7de88bba9930: maj 3 min 0 rcv 3
[EGL_emulation] eglMakeCurrent: 0x7de88bba9930: ver 3 0 (tinfo 0x7de82be86530) (first time)
[Gralloc4] mapper 4.x is not supported
[HostConnection] createUnique: call
[HostConnection] HostConnection::get() New Host Connection established 0x7de89bb968d0, tid 6594
[goldfish-address-space] allocate: Ask for block of size 0x100
[goldfish-address-space] allocate: ioctl allocate returned offset 0x3f3ffe000 size 0x2000
[HostConnection] HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_vulkan ANDROID_EMU_deferred_vulkan_commands ANDROID_EMU_vulkan_null_optional_strings ANDROID_EMU_vulkan_create_resources_with_requirements ANDROID_EMU_YUV_Cache ANDROID_EMU_vulkan_ignored_handles ANDROID_EMU_has_shared_slots_host_memory_allocator ANDROID_EMU_vulkan_free_memory_sync ANDROID_EMU_vulkan_shader_float16_int8 ANDROID_EMU_vulkan_async_queue_submit ANDROID_EMU_sync_buffer_data ANDROID_EMU_read_color_buffer_dma GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_host_side_tracing ANDROID_EMU_gles_max_version_3_0 
[OpenGLRenderer] Davey! duration=1473ms; Flags=1, IntendedVsync=5326230294952, Vsync=5326230294952, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=5326239136600, AnimationStart=5326239160400, PerformTraversalsStart=5326239190100, DrawStart=5327141263100, SyncQueued=5327154499100, SyncStart=5327193043800, IssueDrawCommandsStart=5327193127000, SwapBuffers=5327678743200, FrameCompleted=5327742080800, DequeueBufferDuration=586900, QueueBufferDuration=3540000, GpuCompleted=0, 
[Choreographer] Skipped 94 frames!  The application may be doing too much work on its main thread.
[OpenGLRenderer] Davey! duration=1583ms; Flags=0, IntendedVsync=5326246955504, Vsync=5327813622108, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=5327820591700, AnimationStart=5327820645300, PerformTraversalsStart=5327820956900, DrawStart=5327822819100, SyncQueued=5327823130900, SyncStart=5327823664100, IssueDrawCommandsStart=5327823752700, SwapBuffers=5327825221900, FrameCompleted=5327831155200, DequeueBufferDuration=470100, QueueBufferDuration=3983400, GpuCompleted=8589934594, 
Thread started: <Thread Pool> #2
Thread started: <Thread Pool> #3
Thread started: <Thread Pool> #4
Thread started: <Thread Pool> #5
Resolved pending breakpoint at 'MainActivity.cs:98,1' to void VpnHood.Samples.SimpleClient.Droid.MainActivity.<ConnectTask>d__9.MoveNext () [0x00048].
Starting APp ...
Client Options Version 2.4.318.0
Client Options UseUdpChannel False
Client Options UserAgent Unix 5.4.86.11
Client MaxTcpDatagramChannelCount 4
Loaded assembly: /data/data/com.vpnhood.samples.simpleclient.droid/files/.__override__/System.Memory.dll [External]
Loaded assembly: /data/data/com.vpnhood.samples.simpleclient.droid/files/.__override__/System.Buffers.dll [External]
Loaded assembly: /data/data/com.vpnhood.samples.simpleclient.droid/files/.__override__/System.Core.dll [External]
Loaded assembly: /data/data/com.vpnhood.samples.simpleclient.droid/files/.__override__/System.Numerics.Vectors.dll [External]
Loaded assembly: /data/data/com.vpnhood.samples.simpleclient.droid/files/.__override__/System.Runtime.CompilerServices.Unsafe.dll [External]
Resolved pending breakpoint at 'Tunnel.cs:266,1' to void VpnHood.Tunneling.Tunnel.Channel_OnPacketReceived (object sender, VpnHood.Tunneling.ChannelPacketReceivedEventArgs e) [0x00029].
Thread started:  #6
Thread started: <Thread Pool> #7
UseUdpChannel: False, MinWorkerThreads: 4, CompletionPortThreads: 4
Client Version: 2.4.318.0, ClientId: **-90af-b118fe47ed0b
Client is Connecting
Connecting to Server: 10.*.*.66:443...
Thread started: <Thread Pool> #8
TLS Authenticating. HostName: **fexa.com...
Thread started: <Thread Pool> #9
Loaded assembly: /data/data/com.vpnhood.samples.simpleclient.droid/files/.__override__/System.Numerics.dll [External]
Sending a request... RequestCode: Hello
Loaded assembly: /data/data/com.vpnhood.samples.simpleclient.droid/files/.__override__/System.Threading.Tasks.Extensions.dll [External]
Received a response... ErrorCode: Ok
Client is Connected
Connecting to Server: 10.*.*.66:443...
TLS Authenticating. HostName: **fexa.com...
Thread started: <Thread Pool> #10
Sending a request... RequestCode: TcpDatagramChannel
Received a response... ErrorCode: Ok
A TcpDatagramChannel has been added. ChannelCount: 1
Hurray! Client has connected! SessionId: **1, ServerVersion: 2.4.310.0, ClientIp: 10.*.*.17
Starting TcpProxyHost...
Starting TcpProxyHost...
TcpProxyHost is listening on 0.0.0.0:32831
TcpProxyHost is listening on :::40293
PacketCapture Include Networks: 10.10.50.30/31, 10.10.50.32/29, 10.10.50.40/32, 11.0.0.0/32, 2000::/128
Thread finished: <Thread Pool> #3
The thread 0x3 has exited with code 0 (0x0).
Thread finished: <Thread Pool> #7
The thread 0x7 has exited with code 0 (0x0).
New NAT record. Tcp:8001, LocalEp: 192.*.*.100:51508, RemoteEp: 10.*.*.35:12913
Thread finished: <Thread Pool> #2
Thread started: <Thread Pool> #11
The thread 0x2 has exited with code 0 (0x0).
New NAT record. Tcp:8002, LocalEp: 192.*.*.100:51510, RemoteEp: 10.*.*.35:12913
New NAT record. Tcp:8003, LocalEp: 192.*.*.100:51516, RemoteEp: 10.*.*.35:12913
New NAT record. Tcp:8004, LocalEp: 192.*.*.100:51518, RemoteEp: 10.*.*.35:12913
NatItem has been removed. Tcp:8003, LocalEp: 192.*.*.100:51516, RemoteEp: 10.*.*.35:12913
New NAT record. Tcp:8005, LocalEp: 192.*.*.100:51516, RemoteEp: 10.*.*.35:12913
NatItem has been removed. Tcp:8004, LocalEp: 192.*.*.100:51518, RemoteEp: 10.*.*.35:12913
New NAT record. Tcp:8006, LocalEp: 192.*.*.100:51518, RemoteEp: 10.*.*.35:12913
[pleclient.droi] Background concurrent copying GC freed 1232(185KB) AllocSpace objects, 34(1224KB) LOS objects, 49% free, 1980KB/3960KB, paused 1.114ms total 365.004ms
New NAT record. Tcp:8007, LocalEp: 192.*.*.100:51526, RemoteEp: 10.*.*.35:12913
New NAT record. Tcp:8008, LocalEp: 192.*.*.100:51528, RemoteEp: 10.*.*.35:12913
Thread started: <Thread Pool> #12
Resolved pending breakpoint at 'TcpProxyHost.cs:215,1' to void VpnHood.Client.TcpProxyHost.<ProcessClient>d__21.MoveNext () [0x00079].
Resolved pending breakpoint at 'C:\Amol\cpptest\VpnHood_11_Nov_2022\v2.4.318\VpnHood\VpnHood.Client\TcpProxyHost.cs:215,1' to void VpnHood.Client.TcpProxyHost.<ProcessClient>d__21.MoveNext () [0x00079].
Thread started: <Thread Pool> #13
New TcpProxy Request.
Connecting to Server: 10.*.*.66:443...
TLS Authenticating. HostName: **fexa.com...
Thread started: <Thread Pool> #14
New TcpProxy Request.
Connecting to Server: 10.*.*.66:443...
TLS Authenticating. HostName: **fexa.com...
Sending a request... RequestCode: TcpProxyChannel
Sending a request... RequestCode: TcpProxyChannel
Received a response... ErrorCode: Ok
Received a response... ErrorCode: Ok
Adding a channel to session **1...
Adding a channel to session **1...
A TcpProxyChannel has been added. ChannelCount: 2
A TcpProxyChannel has been added. ChannelCount: 2
New NAT record. Tcp:8009, LocalEp: 192.*.*.100:51536, RemoteEp: 10.*.*.35:12913
New TcpProxy Request.
Connecting to Server: 10.*.*.66:443...
TLS Authenticating. HostName: **fexa.com...
Sending a request... RequestCode: TcpProxyChannel
Received a response... ErrorCode: Ok
Adding a channel to session **1...
A TcpProxyChannel has been added. ChannelCount: 3
Thread finished: <Thread Pool> #11
Thread started: <Thread Pool> #15
The thread 0xb has exited with code 0 (0x0).
Disconnecting...
Client is Disconnecting
Sending the Bye request!
Connecting to Server: 10.*.*.66:443...
TLS Authenticating. HostName: **fexa.com...
Thread started: <Thread Pool> #16
Shutting down...
Disposing TcpProxyHost...
The operation was canceled.
TcpProxyHost Listener on [::]:40293 has been closed.
The operation was canceled.
TcpProxyHost Listener on 0.0.0.0:32831 has been closed.
Disposing Tunnel...
A TcpProxyChannel has been removed. ChannelCount: 2
A TcpProxyChannel has been removed. ChannelCount: 1
A TcpProxyChannel has been removed. ChannelCount: 0
A TcpDatagramChannel has been removed. ChannelCount: 0
[pleclient.droi] Background young concurrent copying GC freed 792(232KB) AllocSpace objects, 46(1656KB) LOS objects, 46% free, 2131KB/3960KB, paused 1.068ms total 228.864ms
Disposing ProxyManager...
Disposing Nat...
NatItem has been removed. Tcp:8001, LocalEp: 192.*.*.100:51508, RemoteEp: 10.*.*.35:12913
NatItem has been removed. Tcp:8002, LocalEp: 192.*.*.100:51510, RemoteEp: 10.*.*.35:12913
NatItem has been removed. Tcp:8005, LocalEp: 192.*.*.100:51516, RemoteEp: 10.*.*.35:12913
NatItem has been removed. Tcp:8006, LocalEp: 192.*.*.100:51518, RemoteEp: 10.*.*.35:12913
NatItem has been removed. Tcp:8007, LocalEp: 192.*.*.100:51526, RemoteEp: 10.*.*.35:12913
NatItem has been removed. Tcp:8008, LocalEp: 192.*.*.100:51528, RemoteEp: 10.*.*.35:12913
NatItem has been removed. Tcp:8009, LocalEp: 192.*.*.100:51536, RemoteEp: 10.*.*.35:12913
Disposing the PacketCapture...
Closing VpnService...
Closing VpnService...
Client is Disposed
Bye Bye!
VpnService has been destroyed!
[TetheringManager] registerTetheringEventCallback:com.vpnhood.samples.simpleclient.droid
`

**Comment by trudyhood** [comment]
Thank you for sharing this. Unfortunately couldn't find the issue. So busy these days so had to schedule for the future. 
Please share it with us if you find the issue sooner.

**Comment by karnilamit** [comment]
No worries. I will keep looking. How can I enable logs on the server side? I am running it on Linux hence can't use VS debugger.

**Comment by trudyhood** [comment]
> No worries. I will keep looking. How can I enable logs on the server side? I am running it on Linux hence can't use VS debugger.

Server Logging is enabled by default. We use nlog. You can see nlog for more information.

**Comment by karnilamit** [comment]
@trudyhood I did test this with version 2.5.324 and it seems to be working fine in the limited test that I did. Closing this for now.
