### ISSUE TITLE
Server ignoring appsettings port

### ISSUE THREAD

**Issue by patil-vaibhav** [vpnhood/VpnHood#17]
"appsettings.json" have port 5003 mentioned but server still binding on 443. While generating access token server endpoint is 192.168.0.101:5003  but while running server it's showing 443.  **"appsettings.json"** in the root folder of VpnHood server beside "publish.json".

Please check logs attached below. Thanks !

[logs.zip](https://github.com/vpnhood/VpnHood/files/5820057/logs.zip)

**Comment by trudyhood** [comment]
Hi,
Sorry I missed the issue notification.
It has been fixed and will be released soon.
Meanwhile you can use -p switch

dotnet VpnHoodServer.dll run -p 5555

Thank you for reporting

**Comment by patil-vaibhav** [comment]
It's working with -p switch.

**Comment by kodsu** [comment]
Hi, I just installed a vpnhood access server and changed the port in appsettings.json. The server still ignores the port.

**Comment by bobvhood** [comment]
Hi,
Can you share your appsettings? Please remove the IP, if any.

**Comment by kodsu** [comment]
Thank you for your quick reply, I just realised that when you set a REST server, it takes the parameters from there. So I set the restserver to null and everything went well.
