### ISSUE TITLE
serve idle

### ISSUE THREAD

**Issue by kazemim99** [vpnhood/VpnHood#170]
why is my server idle for a long time?

![image](https://user-images.githubusercontent.com/14816958/203250642-5aecbcec-02ec-4bc5-81cc-818a88676674.png)
 I can not connect with the client
I config an ubuntu server on AWS and all ports are open

![image](https://user-images.githubusercontent.com/14816958/203251055-a5cdbd43-dd0f-45d5-97d3-47a0757a3cc3.png)

**Comment by trudyhood** [comment]
Amazon has ELASTIC IP, meaning private IP differs from Public IP. Ensure your server listens to private IP and sets its PublicToken to be PublicInToken.
You can send us the AccessPoint Configuration of the Access Server Console so we can check it out. support@vpnhood.com.

The server is IDLE until someone connects to it.
