### ISSUE TITLE
How to create a personal server????

### ISSUE THREAD

**Issue by noya1917** [vpnhood/VpnHood#171]

**Comment by trudyhood** [comment]
Hi, you need a linux or windows server. Please read the following document:
https://github.com/vpnhood/VpnHood/wiki/How-to-run-VpnHood-Server-on-Windows

Ask an IT expert if you are not familiar with this area.

**Comment by noya1917** [comment]
Thank 🔥✨

**Comment by noya1917** [comment]
> Hi, you need a linux or windows server. Please read the following document:
> https://github.com/vpnhood/VpnHood/wiki/How-to-run-VpnHood-Server-on-Windows
> 
> Ask an IT expert if you are not familiar with this area.

Thank ⭐
