### ISSUE TITLE
using Custom port in VpnHood Access Server

### ISSUE THREAD

**Issue by Betrisa** [vpnhood/VpnHood#177]
how can we use custom ports in VpnHood Access Server rather than 443
i added this line to appsettings but not working.
"TcpEndPoints": [ "0.0.0.0:40143", "[::]:40143" ]

and is there any plan to build it for iOS too ?

**Comment by trudyhood** [comment]
It must work. Can you share the server log file?

> and is there any plan to build it for iOS too ?
We have prepared everything but have not yet had time to implement and deploy it on iOS.
