### ISSUE TITLE
Server not install from panel

### ISSUE THREAD

**Issue by roozbehsat** [vpnhood/VpnHood#181]
I think there was an bug in your panel today, when I want to setup my second server from vpnhood access server, I try all 4 way, but non of them work,
please help me.

**Comment by trudyhood** [comment]
Ya, Please try it again and let me know if it doesn't work.

**Comment by roozbehsat** [comment]
thank a lot, 
know it's install on server, but status of server is "idle"

**Comment by roozbehsat** [comment]
not active, and not install .net, isthat ok?

**Comment by trudyhood** [comment]
idle means no one has connected at the moment.

**Comment by roozbehsat** [comment]
Thanks a lot for your support. 

Sent from Yahoo Mail on Android 
 
  On Fri, Dec 2, 2022 at 4:47, ***@***.***> wrote:   


idle means no one has connected at the moment.
