### ISSUE TITLE
Can't singup/login to Access Server

### ISSUE THREAD

**Issue by techjoyment** [vpnhood/VpnHood#183]
I can't signup and access to Access Server. I select my google account but I get a "Bad Request" error every time.

**Comment by bobvhood** [comment]
Could you sign in before or it was your first time?
Which address you are trying to log in?

**Comment by techjoyment** [comment]
I didn't sign up before. I just tried multiple times to sign up but faced "Bad Request" error. Just click on "Open VpnHood Access Server Console" on this link: https://www.vpnhood.com/access-server
The error appears after I click on my google account for login/signup.

**Comment by techjoyment** [comment]
Ok. Problem is solved now.

**Comment by bobvhood** [comment]
Would you let me know how did you solve this issue?

**Comment by techjoyment** [comment]
> Would you let me know how did you solve this issue?

I didn't do anything. I think it was a server issue.
