### ISSUE TITLE
2 server limit in access server

### ISSUE THREAD

**Issue by roozbehsat** [vpnhood/VpnHood#185]
Hi guys, why you force this limit?
If anyone needed to have more servers must do what?

**Comment by kothanzaw** [comment]
And also, cannot delete mistaken server.

**Comment by bobvhood** [comment]
@trudyhood The Access Server is not free. However, you can still have the option to keep your server running standalone without our access server with limited functionality.

@kothanzaw 
Yes, we are so busy, but at the moment, we have trouble with the access-server, and we are working hard to fix it.

**Comment by roozbehsat** [comment]
how can I delete server in server list?

**Comment by bobvhood** [comment]
@roozbehsat we have increased the server limit on the free plan to 3

@kothanzaw , @roozbehsat 
We haven't implemented it yet. Meanwhile, you can edit the created one to the new server or just leave it there. We have to add the remove feature.

**Comment by trudyhood** [comment]
#201
