### ISSUE TITLE
Socket Exception - Connection Refused

### ISSUE THREAD

**Issue by patil-vaibhav** [vpnhood/VpnHood#19]
Environment :

Centos 7 - VPS (Contabo)
Port : 9443
Client : latest
Server : latest

Issue :

VPN connects fine, after that warning and error start's throwing at server side. VPN stays connected but unable to access most of the resources on the internet. Server logs showing connection refused for most of the requests. Don't know if it's VPS issue or something else. 

Attached logs below, Please let me know. Thanks!

[2021-01-30.txt](https://github.com/vpnhood/VpnHood/files/5898428/2021-01-30.txt)

**Comment by trudyhood** [comment]
VpnHood does not need a specific server or configuration; it should run on any server without a particular configuration. As far as the IP is reachable and you can navigate the web in your VPS, it should work. Please make sure you have internet access in your VPS. For example, make sure there is no internal firewall in your machine that blocks the outgoing connections.

I checked the log file you sent. It looks VpnHood could not send many UDP packages and get permission denied. I need to evaluate it more in my Linux box and see if I can reproduce the issue. Meanwhile, let me know if you find the problem.
Thank you for reporting.

**Comment by patil-vaibhav** [comment]
It's clean installation (OS) without any firewall or rules. I am able to ping (via putty) the servers/sites which were previously refused connection while using VPN. Server got 200 Mbit/s Port.

**Comment by trudyhood** [comment]
Hi @patil-vaibhav 
I have simulated this issue (UDP Error on a linux CentOS) box. I hope I solve this issue soon.

**Comment by trudyhood** [comment]
Dear @patil-vaibhav,
I have fixed an error for sending some UDP in a Linux box. I see it is working on my Linux CentOS.
Would you please check the latest version (﻿v1.1.197-beta) and let me know about the issue. I hope it solves the problem you reported. If you find it is not solved, please reopen this issue. Feel free to start a new issue or discussion regarding the experience you have.

**Comment by patil-vaibhav** [comment]
Hi @trudyhood,
v1.1.197-beta (Win-Client/Server) seems to have fixed the issue. But server still throwing permission denied and connection refused errors sometimes. To test on Xamarin I'm waiting for package update. Also noticed slow speed. Don't know if because of mentioned errors or something else. Test server you've given in Win-Client works very well though.

Win-Client not showing selected/connected server.
![image](https://user-images.githubusercontent.com/71482238/106608695-b9adcf00-658a-11eb-85ed-4d15a06168ec.png)

**Comment by trudyhood** [comment]
Would you send me the new log of the server so I can check the

We hide the IP address, so you need to rename or give

**Comment by trudyhood** [comment]
> But server still throwing permission denied and connection refused errors sometimes. 
Would you send me the new log.

> Win-Client not showing selected/connected server.
We hide the IP of server, you can rename the server name or set specific name when creating access token. Server IP address is available on "change server" page

**Comment by patil-vaibhav** [comment]
Logs

[2021-02-02.txt](https://github.com/vpnhood/VpnHood/files/5916051/2021-02-02.txt)

> We hide the IP of server, you can rename the server name or set specific name when creating access token. Server IP address is available on "change server" page

My bad , I thought it was a static label and connected/selected server name will come next to it.

**Comment by trudyhood** [comment]
Dear patil;
Unfortunately, we couldn't simulate those errors in our Linux boxes, centos 8 and Ubuntu 20.04.2

But if you like, you can email me a login with a limited access to your server, so we can work on it to find the issue in VpnHood in your server.

**Comment by patil-vaibhav** [comment]
Hi trudyhood,

   I've submitted a bug report from your Android app. It seems problem is not with servers as I've tested both (yours and mine) with win-client and everything works just fine. But in android-client (app you've created and app I've created using NuGet lib), connection always shows unstable with the errors I've mentioned in previous comments.  
 In both cases server works just fine but problem only occurs when using android client. Please look into it, Thanks !

**Comment by trudyhood** [comment]
Dear @patil-vaibhav

The report you have submitted was so beneficial. I have found a severe issue in the UDP processing that causes packet loss. I have solved it in version 1.1.232. I am not sure but hope that it solves the problem you had.

Thank you for your contribution.
