### ISSUE TITLE
persistence to android app

### ISSUE THREAD

**Issue by minamaged095** [vpnhood/VpnHood#191]
On a redmi note 10 the app is not persistent. I'm not sure if this is a feature that does not work for me or the feature is not there.

**Comment by trudyhood** [comment]
Hi,
What do you mean by not persistent?

**Comment by minamaged095** [comment]
Other vpn apps you can close them and they run in the background.
When I close this VpnHood the vpn connection closes and the app does not continue to run in the background

**Comment by trudyhood** [comment]
Please make sure you haven't disabled the VpnHood app notification. You should see the App notification otherwise, Android closes the app in the background without any notification. Let me know the result.

**Comment by trudyhood** [comment]
1. How long does it take to disconnect? 
2. Do you use our public server, or do you have a private token?
3. What is your VpnHood version?

**Comment by minamaged095** [comment]
Latest version on play store
I also sent you a video on the support email

**Comment by trudyhood** [comment]
> Latest version on play store I also sent you a video on the support email

Thank you for the recording. I can see you use bit-defender. Would you stop it temporarily and see the result?

**Comment by minamaged095** [comment]
Still the same behaviour.

**Comment by trudyhood** [comment]
> Still the same behaviour.

Sorry, but it is very tricky for us to simulate this issue :(

**Comment by trudyhood** [comment]
Couldn't simulate the issue
