### ISSUE TITLE
connection 

### ISSUE THREAD

**Issue by koloner** [vpnhood/VpnHood#193]
Hello
The problem with the Windows software is that after using it for a long time, like one or two hours of connection, the data sent and received is interrupted and the program must be reconnected. The internet is not disconnected, the connection to the server is disconnected and needs to be reset

**Comment by trudyhood** [comment]
Would you let me the Client App Version a Server Version?
Are you using VpnHood Public Servers or another server?
Is it windows app or android?

**Comment by koloner** [comment]
I am using the latest version and I had problems on both Android and Windows devices. That I use private servers

**Comment by trudyhood** [comment]
OK, that's very challenging for us to find it out. Let us know if you have any clues.

**Comment by koloner** [comment]
How can I access the logs?

**Comment by koloner** [comment]
[log.txt](https://github.com/vpnhood/VpnHood/files/10175591/log.txt)
log file, when connected but not working

**Comment by trudyhood** [comment]
Thank you, would you disable the UDP on VpnHood and send the log again? It looks like you are using the UDP protocol, which may not work in your country.

**Comment by koloner** [comment]
Hello, today I updated to the latest version and there was no connection problem (without udp). Please add internal updates. Until an alert to update and maybe a forced update is sent to users.
Disruptions increase and decrease on some protocols every day.
Thanks a lot

**Comment by trudyhood** [comment]
We are planning to enable another method of auto downloading

**Comment by trudyhood** [comment]
#200
