### ISSUE TITLE
WARNING: VIRUS/MALWARE IN VPNHOOD

### ISSUE THREAD

**Issue by SMARTSEEU** [vpnhood/VpnHood#194]
DO NOT INSTALL IT HAS MALICIOUS SCRIPT:

Avast: FileRepMalware [Misc]
AVG:   FileRepMalware [Misc]
Symantec: ML.Attribute.HighConfidence

https://www.virustotal.com/gui/file/a363d031f8c199f93860386e4b071002854d22f3d10dbf41a2c7573f4900efe1

**Comment by koloner** [comment]
https://www.virustotal.com/gui/url/72ca55795fb35dfa7608aa28ffb82e4f6cbe16cf5b2090959e7c1611f78d0cbc

https://www.virustotal.com/gui/url/cdc1f6c418d183c7e8cc4dcb54b11305d77b5328317b12d1f1d7688bd2a9c541

**Comment by SMARTSEEU** [comment]
That is a different file you are uploading! 

It is not magic

Check here from https://www.vpnhood.com/


https://www.google.com/url?q=https%3A%2F%2Fgithub.com%2Fvpnhood%2FVpnHood%2Freleases%2Flatest%2Fdownload%2FVpnHoodClient-Win.exe&sa=D&sntz=1&usg=AOvVaw1VtIMdWLJ3x5Ic_FOa9RnE

**Comment by trudyhood** [comment]
Hi All,

I checked it. I can see they Avast & Semantic detect something as malicious code. We will try to fix it.
Thank you for your contribution.

**Comment by trudyhood** [comment]
@SMARTSEEU
We compiled the new version 323 and uploaded it to the site you sent to us. It looks like most security warning has gone but
we couldn't solve "Symantec warning: ML.Attribute.HighConfidence", as we don't understand what it is. do you have any idea?

https://www.virustotal.com/gui/file-analysis/MWZlYzE1ZDMxYmFkYmM2MGU2NTlmMjdhMTQ1N2Q1MTI6MTY3MDQ5NDQwMA==

**Comment by SMARTSEEU** [comment]
ML.Attribute.HighConfidence is 100% True positive malicious script.

Just compare the script with the previous version of VPNHood which is CLEAN!

**Comment by trudyhood** [comment]
@SMARTSEEU 
We downloaded Advanced Installer in a fresh sandbox and created an empty project output to exe.
https://www.virustotal.com/gui/file/bc41cf580431407b5f8950f4495effdeb294eda292cafb506345a2995400fdaa?nocache=1

It looks like something is wrong in the Advanced Installer output. I don't think our sandbox is infected because I created many other exe files and tested them. We need to ask Advanced Installer.

**Comment by SMARTSEEU** [comment]
The version 2.4.318.160  was clean... 
Check what is added extra

**Comment by trudyhood** [comment]
> The version 2.4.318.160 was clean... Check what is added extra

We tested Advanced Installer without any code or script and got the same issue. Anyway, we contacted Advanced Installer, so we should just wait till they find out how to solve this issue.

Here is the Advanced Installer support team's response for anyone interested:

**** ADVANCED INSTALLER RESPONSE ****
>As it looks like, the antivirus program is not able to distinguish between malicious and legitimate software, leading it to flag benign programs as threats.
>
>Overall, false positives can be caused by a variety of factors, including outdated antivirus software, improper configuration, and the use of advanced obfuscation techniques. To avoid false positives, you should consider getting your software certified through a digital certificate. This can help to give users confidence that your software is safe to use and can reduce the risk of it being flagged by antivirus programs.
>
>For details, please check the following article:
https://www.advancedinstaller.com/false-positive-virus-detection.html
>
>We will contact those AV vendors, but not all of them have an easy workflow for uploading resources and whitelisting.
From our experience so far, things are moving faster when the product is signed. However, in the end, it is their product that is not working properly (well know AV companies have no problem with the setup packages created with Advanced Installer.)

**Comment by trudyhood** [comment]
That's because it was created by an older version of Advanced Installer.

Lets hope they fix it soon.

**Comment by trudyhood** [comment]
> I suggest to compile it again with the older version of Advanced Installer.

I have tried version 19.0, which is pretty old, still have the same issue
It looks like we need to return to a very older version to solve this issue!

**Comment by SMARTSEEU** [comment]
Whatever it takes no one can install it with the virus codes.

**Comment by MHSanaei** [comment]
your 2 last versions don't work on android 
everything is working fine on the v2.4.321 android version

and Kaspersky remove your 2 last versions immediately 
and again everything is working fine on the v2.4.321 windows version

Event: Object deleted
User type: Active user
Application name: explorer.exe
Application path: C:\Windows
Component: File Anti-Virus
Result Description: Deleted
Type: Trojan
Name: HEUR:Trojan-Downloader.Win32.Upatre.gen
Precision: Heuristic Analysis
Threat level: High
Object type: File
Object name: VpnHoodClient-win.exe
Object path: D:\download
MD5: C3AE14EAAB8EEC9B4355413A65F672CB

**Comment by SMARTSEEU** [comment]
Leave it!
It's not worth to jeopardize your security by a virus

**Comment by trudyhood** [comment]
We are working on it.

**Comment by trudyhood** [comment]
We have tried to change many things, such as changing mixed x32/64, changing compress to LZMA compression, and different things. Advanced Installer released an update too. Now just an antivirus "Rising" detect it as a virus. The only option is to choose msi instead exe but we will lose a lot of features. here is the result:
https://www.virustotal.com/gui/file/ef1ac6db645b3211d925bc0a6871b48ba9f22d3de35f415222967c48ffacea8e

Thank you for your contribution

**Comment by SMARTSEEU** [comment]
What features will you lose in MSI?

**Comment by trudyhood** [comment]
It gets 30 MB bigger, and there is no prerequisite check. I really think the "Rising" false error is unimportant; the Major AV and all other security software couldn't find any problem. Perhaps it is the Rising issue, as I am sure it reports the same error with all other Advanced Installer Setup.

**Comment by SMARTSEEU** [comment]
Thanks,

Then it is great that you put 2 versions of MSI and EXE so the user has the option to choose from.

Best

**Comment by trudyhood** [comment]
> Then it is great that you put 2 versions of MSI and EXE so the user has the option to choose from.

Handling its auto-update takes us time. 

>And please provide the links so we can test it again.

We have already uploaded the new version. You can find it in the releases section

**Comment by SMARTSEEU** [comment]
where are the two versions?

https://www.google.com/url?q=https%3A%2F%2Fgithub.com%2Fvpnhood%2FVpnHood%2Freleases%2Flatest%2Fdownload%2FVpnHoodClient-Win.exe&sa=D&sntz=1&usg=AOvVaw1VtIMdWLJ3x5Ic_FOa9RnE



https://github.com/vpnhood/VpnHood#

**Comment by trudyhood** [comment]
Ooops! I forgot to update the links. The links are all updated. You can also find all releases here:
https://github.com/vpnhood/VpnHood/releases

**Comment by SMARTSEEU** [comment]
Thanks.

Please update with the MSI version as well.

Best regards

**Comment by trudyhood** [comment]
Hi, We have released the MSI version. It doesn't have the false virus detection issue:
https://github.com/vpnhood/VpnHood/releases/latest/download/VpnHoodClient-win-x64.msi
