### ISSUE TITLE
Connection doesn't close after ssh-client exits

### ISSUE THREAD

**Issue by karnilamit** [vpnhood/VpnHood#195]
Hi,
I am testing the Vpnhood server and client in my local setup. I try to access a server using ssh through VpnHood.The connection goes through the VPN tunnel successfully. However when I close the ssh client on my windows machine the target server still shows an active ssh connection from the VpnHood server.

The Setup is

A ==> B ==> C

A is my Windows machine which has ssh client(putty) and VpnHood Client installed. B is a Linux server running VpnHood Server. C is the target machine which has ssh server installed.

Do let me know if you need more details on this issue.

-AK

**Comment by trudyhood** [comment]
Thank you for reporting this. I believe we've found a serious issue, and we solved it. It caused a huge impact on VpnHood performance. We are still working on it.

**Comment by karnilamit** [comment]
Thank you @trudyhood Is the patch available for this fix?

**Comment by trudyhood** [comment]
We have fixed an important issue that left many TCP connections open. I haven't had time to test it with ssh-client, so it would be great if you test that and share the result with me. 
Let me know if the problem still exists, so I have to go more deeply into that case.

**Comment by karnilamit** [comment]
Thanks @trudyhood . I will test it with version 2.5.324

**Comment by karnilamit** [comment]
Hi @trudyhood 

I did verified with the latest release and it seems to be working fine. Will test it more and re-open this if I find anything wrong.
