### ISSUE TITLE
Problem with max client

### ISSUE THREAD

**Issue by roozbehsat** [vpnhood/VpnHood#198]
Hi guys, I set the max client in one, then if I connect another device with same access token this message will shown:
You have been disconnected because another device connected with your access key!

but all devices is connect to vpnhood and all of them worked...
please checked.

**Comment by bobvhood** [comment]
The old client should be disconnected in 20 minutes; they may not see any error if they run an old client version. 
However, there is a known issue in managing the MaxClient, and it is an item of our priority tasks.

**Comment by bobvhood** [comment]
The problem should not exist anymore. The old devices should be disconnected in 15 minutes or less. Please let me know if the issue exists.
Thank you.
