### ISSUE TITLE
Update server to new version?

### ISSUE THREAD

**Issue by roozbehsat** [vpnhood/VpnHood#199]
Hi, How can I update my server to new version?
my current version is 2.4.321.

**Comment by bobvhood** [comment]
It must be updated automatically after a day. There is an automatic updater, please check and send me the result
`> systemctl status VpnHoodUpdater`

**Comment by roozbehsat** [comment]
I Got this massage after the command:
● VpnHoodUpdater.service - VpnHood Server Updater
     Loaded: loaded (/etc/systemd/system/VpnHoodUpdater.service; enabled; preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Tue 2022-12-13 11:18:33 UTC; 9h >
    Process: 25529 ExecStart=/opt/VpnHoodServer/vhupdate (code=exited, status=203/EXEC)
   Main PID: 25529 (code=exited, status=203/EXEC)
        CPU: 915us

Dec 13 11:18:33 ubuntu-s-1vcpu-1gb-intel-ams3-01 systemd[1]: VpnHoodUpdater.service: Main process>
Dec 13 11:18:33 ubuntu-s-1vcpu-1gb-intel-ams3-01 systemd[1]: VpnHoodUpdater.service: Failed with >
lines 1-9/9 (END)

Is that ok?
But my server version is still 2.4.321

**Comment by trudyhood** [comment]
Thank you for reporting this. I found the issue. Working for it

**Comment by trudyhood** [comment]
@roozbehsat We have fixed the issue, but this time you need to update your server manually. Just re-install it; you don't need to config it again.
