### ISSUE TITLE
Feature: Removing a Server from Access Server

### ISSUE THREAD

**Issue by trudyhood** [vpnhood/VpnHood#201]

**Comment by trudyhood** [comment]
We will fix it. At the moment you can simply modify the access-points of a server. It is like you removed that server and install another one. Just make sure the old server stop working.

**Comment by roozbehsat** [comment]
Ok and thanks a lot, I will rechecked and telling you.

**Comment by roozbehsat** [comment]
Only one question: The ex_client key is worked in this solution?

**Comment by trudyhood** [comment]
> Only one question: The ex_client key is worked in this solution?

ex_client key is dependent on your Server EndPoints. We are going to implement the domain soon.
At the moment, if you change the IP, which is (PublicInToken), then the ex-access key will stop working.

**Comment by trudyhood** [comment]
It is done. Refresh the Access Server page. You can find it in the Servers page.
Thank you for using VpnHood!
