### ISSUE TITLE
Error In Access Points!!!

### ISSUE THREAD

**Issue by roozbehsat** [vpnhood/VpnHood#203]
Hi guys,  I have a problem in my panel. I have 3 server but I can manage only one server access point.
Please Help me...)
![Screenshot (98)](https://user-images.githubusercontent.com/119633123/207465918-5132db34-df6a-4ef9-a52a-b214527a173f.png)

against: 
![Screenshot (99)](https://user-images.githubusercontent.com/119633123/207466180-17b9a362-f00f-4dce-9a8d-418b6ea7098a.png)
you can see in second picture (server2) i can edit but in first image (server3) i can't edit!!!

**Comment by trudyhood** [comment]
Hi,
Edit server and set the group to Manual.

**Comment by roozbehsat** [comment]
Thank A lot sir,
