### ISSUE TITLE
[Feature Request]: support multiple similar access keys in client

### ISSUE THREAD

**Issue by SSgumS** [vpnhood/VpnHood#204]
Hello

It could be great if we could add multiple access keys with a similar TokenId to our client app. Curre tly, the client application replaces the other access key if the TokenId is the same.

For example, imagine we need an access key for Europe servers with the name "Username - EU" and another for US servers with the name "Username - US". And both have the same TokenId as they are for the same username.

I don't know the purpose of SupportId, but can it be combined with TokenId as a distinguishment element in this situation?

Thanks in advance.

**Comment by trudyhood** [comment]
It means you need an access key with a different region or tag. So users can select a region or (tag), then they will be redirected to one of those servers. Is that right?

**Comment by SSgumS** [comment]
Yes, exactly.
This way I can give the user multiple access keys with different purposes and end points. And when the user adds these access keys to his client, he can choose that which he wants to connect.
Like the picture bellow:
![Screenshot_2022_12_14_04_39_49_150_com_vpnhood_client_android](https://user-images.githubusercontent.com/25867589/207481653-e417c3ae-c444-49ec-819b-c8221d2c45d4.jpg)

**Comment by trudyhood** [comment]
I was thinking of giving a single access key, so users will have the option to choose the server group among those groups. for example:
SSgumS servers ===> Dropdown Menu Ask users to choose from the following servers 
💻 Gaming 💻 EU 💻 Torrent ....

In this case, you will give them only one access-key.

### Advantage 
- You and your client won't be confused by managing multiple access keys.
- You can manage how many clients can use the access token simultaneously.

### Disadvantages
- if you give them an access-key, they will have access to all those servers.

Is that OK?

**Comment by SSgumS** [comment]
Yes. Your idea is great and ideal.
At first, I just wanted to propose the simplest option in the terms of development efforts. But for the convenience of users, your idea is the best.

**Comment by SSgumS** [comment]
Hello!
I was wondering if there's been any progress regarding the issue we encountered earlier?
I suggest implementing a non-overwriting import policy on the client app to resolve the problem. It's a simple fix that can be done quickly. If you're too busy, I'm happy to help with the implementation of this solution.
For the time being, let's concentrate on resolving the problem and leave aside the previously discussed improvement feature for a future occasion.
Thank you for your attention to this matter.

**Comment by trudyhood** [comment]
We have made improvements to VpnHood AccessServer ServerFarm and are working on adding ServerProfiles to enhance its functionality. While the feature you request is not our top priority, it is on our agenda for future implementation. Additionally, our non-overwriting import policy may pose issues for some users. While we plan to add this feature, unfortunately, we cannot provide a timeline for its availability. We suggest exploring alternative solutions until this feature becomes available.

**Comment by trudyhood** [comment]
VpnHood AccessServer ServerFarm and ServerProfiles help were required for the feature we discussed so we get closer to implementing that.

**Comment by trudyhood** [comment]
> I was thinking of giving a single access key, so users will have the option to choose the server group among those groups. for example:
> 
> ```
> SSgumS servers ===> Dropdown Menu Ask users to choose from the following servers 
> 💻 Gaming 💻 EU 💻 Torrent ....
> ```
> 
> In this case, you will give them only one access-key.
> 
> ### Advantage
> * You and your client won't be confused by managing multiple access keys.
> * You can manage how many clients can use the access token simultaneously.
> 
> ### Disadvantages
> * if you give them an access-key, they will have access to all those servers.
> 
> Is that OK?

Just for information. We are working on this as we hope to release it soon

**Comment by trudyhood** [comment]
We have implemented this, but now it is just for countries, and everything is automated. I agree we need more work on it to support custom tags like torrents and games, but let's postpone it as another feature. 
The United States is also managed differently, and we may need to do the same for Asia, Europe, and a few other exceptions. The good news is that you don't need to do anything to arrange countries; all settings are automatic.
