### ISSUE TITLE
upload speed problem

### ISSUE THREAD

**Issue by Ghost56314** [vpnhood/VpnHood#205]
hello 
I started using your Vpn service two weeks ago, in the first days the download and upload speed was good, but after a few days it was detected by the government(iran) and the upload was almost zero, then to solve this problem, I used tunneling between two vps, the download and upload speed was fine again, but for the past few days the upload speed has been close to zero again, do you have any ideas how to fix this problem?
-I using tcp protocol

**Comment by trudyhood** [comment]
Many people from Iran reported that they have poor upload connections. VpnHood can not increase the original upload speed. Try to check your speed without VPN connection to a server node from US. You can use speedtest.net and make sure to select a server in the US

**Comment by trudyhood** [comment]
Feel free to add comments to this issue if you believe your internet connection is reliable without VPN.
