### ISSUE TITLE
VpnHood Client connecting to multiple VPNHood Servers

### ISSUE THREAD

**Issue by karnilamit** [vpnhood/VpnHood#208]
Hello,

I have a use case where the same Client needs to connect to multiple VpnHood Servers for different IP access. This can be viewed as below
       
A == B == C
A == D == E

Here A is a Android device trying to access servers C and E which are accessible through VpnHood Servers B and Server D. I can have the client connect to B and D separately i.e. login using B's Token to access Server C and after logout login using D's token to access Server E. Is it possible to have multiple VPN-Session's open from a single Client?

-AK

**Comment by trudyhood** [comment]
We had a discussion about having multiple connections to a different server on a client to achieve multiple IPs at the same time. Theoretically, it is possible in VpnHood, but to be honest, it is not on our table. We have plenty high priority tasks. I am afraid to say that we don't have any plan to implement this feature. 😞

**Comment by karnilamit** [comment]
@trudyhood No worries Thanks for your reply. Good to know that its possible.
