### ISSUE TITLE
Network Traffic

### ISSUE THREAD

**Issue by wanoghoco** [vpnhood/VpnHood#21]
Please how can I intercept the network to get the packet or url my app is making request to when the vpnhood is active

**Comment by trudyhood** [comment]
Sorry, I couldn't understand what you are trying to do with VpnHood! Would you describe it more?

**Comment by wanoghoco** [comment]
Am trying to create an antivirus, but one of the feature am looking for is
to get all request made by all apps in an Android de ice.. the only way to
do it is to intercept the network using VPN and all the request goes
through the VPN network....

**Comment by trudyhood** [comment]
In this case VpnHood doesn't do anything for you, unless you see its source and just find how it captures packet. also nowadays all packets encrypted via HTTPS and you might need to register a certificate a root certificate same as fiddler which is far beyond this topic. 

Good luck.
