### ISSUE TITLE
Empty Blank/blue screen

### ISSUE THREAD

**Issue by SMARTSEEU** [vpnhood/VpnHood#210]
After running the VPNHOOD it shows a blank screen either grey or Blue.
<img width="310" alt="blue error" src="https://user-images.githubusercontent.com/120019712/207873760-05c03b19-68c9-4805-b6a6-2874083551d5.png">

**Comment by trudyhood** [comment]
Aha, This is the error caused by Microsoft WebView2, and it really goes on my nerves. Would you do the following steps and let me know which may solve the issue? Please don't do that all at once so we can understand, which may help.
I believe the WebView process didn't close properly so 

1. Restart your computer and try again
2. Reinstall VpnHood and try again
3. Delete the following folder and try again. %USERPROFILE%\AppData\Local\VpnHood\Temp\EBWebView

**Comment by SMARTSEEU** [comment]
I just uninstalled the webview2 and now it shows in the browser, however, does not connect to any Vh keys that were working previously.
![server error](https://user-images.githubusercontent.com/120019712/208165563-8f732e55-906b-43de-9f13-e0633dd3c5ca.JPG)

The only working version was 2.4 and the rest were screwed up...

**Comment by SMARTSEEU** [comment]
I just uninstalled the webview2 and now it shows in the browser, however, does not connect to any Vh keys that were working previously.
![server error](https://user-images.githubusercontent.com/120019712/208165563-8f732e55-906b-43de-9f13-e0633dd3c5ca.JPG)

The only working version was 2.4 and the rest were screwed up...

**Comment by trudyhood** [comment]
Have you updated the server?
Can you connect to VpnHood Public Servers?

**Comment by SMARTSEEU** [comment]
Can you connect to VpnHood Public Servers? ...... NO!

**Comment by SMARTSEEU** [comment]
anyway Microsoft WebView2 is required for other software and could not be uninstalled for ever.

**Comment by trudyhood** [comment]
> Can you connect to VpnHood Public Servers? ...... NO!

I can see many users have connected with the recent version. Do you have installed any firewall? Would you share a log file via diagnostic? We haven't changed that part in this version, Do you have any idea that may help? 

> anyway Microsoft WebView2 is required for other software and cannot be uninstalled forever.

Yes, actually, I didn't ask you to remove it; I believed if you just restart your computer, it might work.

**Comment by SMARTSEEU** [comment]
I have a firewall but it is not blocking anything.. and I had this firewall on the previous versions....
<img width="330" alt="blue error" src="https://user-images.githubusercontent.com/120019712/208292367-084bdb3f-a0e6-4a1b-9b39-aab25130a885.png">

It is blue no log can be shown...

**Comment by trudyhood** [comment]
It must be in the coding, and I am trying to find it. What I said was for the other issue. Let's not mix these two issues with each other. 
The first Issue is the blue screen. 
The second issue is that you are not able to connect.

For the first issue (blue screen):
Please restart your computer, then Delete the following folder and let me know the result.
%USERPROFILE%\AppData\Local\VpnHood\Temp\EBWebView

**Comment by SMARTSEEU** [comment]
Per you saying

I restarted and deleted that folder but the same blue screen...

**Comment by trudyhood** [comment]
Dear SMARTSEEU,
Unfortunately, I couldn't simulate the issue, but I tried to change something blindly about WebView2. Please update to version 328 and let me know the result.

**Comment by SMARTSEEU** [comment]
Hi,

I used the updated version, 

It does not show the webview and instead opens in the browser and again does not connect.
[diagnosis file.txt](https://github.com/vpnhood/VpnHood/files/10258910/diagnosis.file.txt)


here the bug report.

**Comment by trudyhood** [comment]
Ok. At least it opens the browser when webview doesn't work.

Regarding to connection error. Are you sure you can reach your server? I can see in the log that the simple ping has been failed. Also your server 443 is not reachable. It doesn't relate to any VPN protocol. Double check your firewalls at your client and your server.

**Comment by SMARTSEEU** [comment]
I have a few public servers that were working before but now do not work.

**Comment by SMARTSEEU** [comment]
If you can give a working key I can try it.

**Comment by trudyhood** [comment]
Our public servers are working at my end. Maybe your servers ips have been blocked. I recommend you not to create public servers in restricted countries. Create private servers for limited group of people to keep ips secret.

**Comment by SMARTSEEU** [comment]
IT IS WEIRD ALL 4 DO NOT WORK..
Can you send one to my email: Nomad6456@proton.me

thanks

**Comment by trudyhood** [comment]
We just develop the software and run public servers for test purposes. I'm afraid to say that we don't offer any private server on our end.

**Comment by SMARTSEEU** [comment]
The other problem with your console is that it only accepts google mail.

Can you provide other emails?

**Comment by SMARTSEEU** [comment]
I have a windows server but don;t know how to get the Vh key.
All is written Linux, what should I do?
![Capture](https://user-images.githubusercontent.com/120019712/208675552-8bb6df3a-48b8-4a4a-8fa8-af3d16925a9d.JPG)

**Comment by trudyhood** [comment]
I have added the Windows item to the list for you. Refresh the Console and try again. Let me know if there is any issue.

**Comment by SMARTSEEU** [comment]
thanks
How should the code used? where should I put the code?

**Comment by trudyhood** [comment]
It is a powershell command. Login to your server, start a PowerShell console as admin, and put it there.

**Comment by SMARTSEEU** [comment]
gave error:
![image](https://user-images.githubusercontent.com/120019712/208876740-3936486a-824a-4675-a024-87ecb5f97bb5.png)

**Comment by trudyhood** [comment]
Oops! It is a bug.
Meanwhile, you can create a folder named storage in the following path and try it again.
There are few other bugs too for Windows that we are working on it
C:\Program Files\VpnHood\VpnHoodServer\storage

**Comment by SMARTSEEU** [comment]
stuck!
![image](https://user-images.githubusercontent.com/120019712/208879419-cd336b39-b935-49f5-8886-672398c0ce55.png)

**Comment by SMARTSEEU** [comment]
![image](https://user-images.githubusercontent.com/120019712/208888726-6669c682-4233-421c-a599-8a2f3c1138f5.png)

**Comment by trudyhood** [comment]
Make sure another service on your server doesn't listen to 443 or try to use another port.

**Comment by SMARTSEEU** [comment]
how?

**Comment by SMARTSEEU** [comment]
How??

By the way despite saying configuring.. a vh: key has been created but does not work...

**Comment by trudyhood** [comment]
You can't create a token unless the server is initialized properly because the endpoint must be established.
If you are interested, you can give me your server credential so I can look at it. support@vpnhood.com
Please update the new version too.

**Comment by SMARTSEEU** [comment]
It's kind of you.
I can give you the credentials , But every time it is not possible to give you the confidential user/pass and it is not professional as well.

There should be guidelines on how to do it

and I cannot believe all of a suddent all 4 public keys stopped working.... they were working on previous versions with WEBVIEW2.... 

at least you should provide a temporary key as a positive control... so I can test your software.

**Comment by trudyhood** [comment]
No problem. You need to solve that socket-forbidden issue first. Check the server log. This issue does not relate to the webview. I believe these are coincided issues and don't relate to each other.

**Comment by SMARTSEEU** [comment]
OK
Here are the files for the windows server log:

https://filepost.io/d/54rA7LGKTw

**Comment by trudyhood** [comment]
Thank you,

I checked it out. As I mentioned, it raised an error that the server can't listen to 443. Here is the resolution:

1. Make sure you are running the server as Administrator, sometimes OS requires admin access to listen on the 443
2. Stop the other service that is listening on 443. It is usually IIS; perhaps you need to disable it or configure IIS not to listen on 443 (HTTPS)
3. You can leave the 443 port and configure the VpnHood server to listen on another port, such as 4443

I see you don't use our VpnHood Access Server so that you can configure your File Access Server by appsettings.json
https://github.com/vpnhood/VpnHood/wiki/VpnHood-Server-Configuration
