### ISSUE TITLE
High CPU usage bursts on a low end server which causes the termination of VpnHood

### ISSUE THREAD

**Issue by alphajoza** [vpnhood/VpnHood#211]
Tested various releases (including [v2.6.326](https://github.com/vpnhood/VpnHood/releases/tag/v2.6.326)) on a low end server (one core with 512mb of ram); after running the main binary with the following command:

`VpnHoodServer start`

I can successfully connect to the server and browse the internet but CPU usage of server increases dramatically (100% usage) and after some minutes of not-responding, the kernel terminates the main binary of the VpnHood. (there's no such issue on a two core, 2gb ram server).

Is there a minimum system requirement for running VpnHood or some parameters that I can change?

**Comment by trudyhood** [comment]
Hi, Can you provide the following information?

- What is your OS version?
- Does it happen every time?
- How many users were connected to your server?
- Is it possible to share your server with our team so we can evaluate it? (support@vpnhood.com)

> Is there a minimum system requirement for running VpnHood or some parameters I can change?

It should work on 500 MB, but it depends on how many users are connected. if it is less than 100, it should be a problem that we have to find.
