### ISSUE TITLE
ssl domin

### ISSUE THREAD

**Issue by koloner** [vpnhood/VpnHood#212]
hi how can connect with ssl & domin?
i use this command
sudo /opt/VpnHoodServer/vhserver gen -domain
but not conncet in windows
log file 
[log.txt](https://github.com/vpnhood/VpnHood/files/10239839/log.txt)

**Comment by trudyhood** [comment]
You need a valid domain or subdomain. You can register a free subdomain and create a self-certificate for it and replace the default.pfx. I can also add a command to create a self-certificate for a given domain, but in the first step, you need to acquire a domain or subdomain.

**Comment by koloner** [comment]
add self-certificate, that is very good.

**Comment by trudyhood** [comment]
Use SslCertificatesPassword in appsettings.json in FileAccessServerOptions
![image](https://user-images.githubusercontent.com/72891124/208083561-de44a9d9-51ea-4564-ae65-1a7ac6a7ef76.png)

**Comment by abolfazl6** [comment]
Hello
How to place your domain?

**Comment by trudyhood** [comment]
> Hello How to place your domain?

Are you using Central Access Server or File Access Server?

**Comment by abolfazl6** [comment]
I use Central Access Serve

**Comment by trudyhood** [comment]
go to Server Farms > Select your Farm. There you can create a SelfSigned certificate with your desired domain or upload your own. 
![image](https://github.com/vpnhood/VpnHood/assets/72891124/df386d80-5701-4818-8955-9b86bf957b64)

If you want to have valid domain change the "Access Point Type"

**Comment by mfat** [comment]
Can I use a domain and hide it behind a cloudflare IP? My server has already been blocked.

**Comment by trudyhood** [comment]
> Can I use a domain and hide it behind a cloudflare IP? My server has already been blocked.

Cloudflare is not supported. more info: #316
