### ISSUE TITLE
Android doesn't work on browser

### ISSUE THREAD

**Issue by erfandiakoo** [vpnhood/VpnHood#216]
when vpnhood connected on android browsers(chrome, etc) cannot open any pages.

**Comment by trudyhood** [comment]
Hi, Did you check with a private server or our public server?

**Comment by erfandiakoo** [comment]
yes, setup vpnhood on my own server

**Comment by trudyhood** [comment]
This issue is usually related to IP6, which we have solved. 
One option is to set up IP6 on your server.  
Another option is to ensure you are using the latest version of both the client and server.

Let me know if it solves the issue.
