### ISSUE TITLE
Just Blue window

### ISSUE THREAD

**Issue by akshayalix** [vpnhood/VpnHood#224]
Hi, I had the version before todays pre-release and whenever I open the app it just shows a blue window. So, I tried todays release too, but same thing happens.(Just a Blue Window) 
![8](https://user-images.githubusercontent.com/57768355/210137981-891dc270-c4fc-4c49-934d-ab335a239fcd.jpg)

**Comment by trudyhood** [comment]
That is a known issue that we couldn't find its problem. We hoped it open the browser when web view doesn't work, but it looks like the issue still exists. 

* Exit VpnHood
* Delete the following folder and try again. %USERPROFILE%\AppData\Local\VpnHood\Temp\EBWebView
* Restart your windows 
* Would you tell me the version you installed for confirmation?
*  Wha is the Version of your Windows?

Let me know the result.

**Comment by akshayalix** [comment]
ok, I will try this fix, My windows version is Win11 Pro 22H2 (OS Build 22621.963) Kinda latest 😁. Thanks for replying.

**Comment by akshayalix** [comment]
Hi bro, I was trying the fix you mentioned but there is no "EBWebView" Folder. There is only  "SPA" Folder, And to try I  deleted the "SPA" folder and re-opened VPNHOOD, but same thing (blue window) and the "SPA" folder is re-created on launch.

**Comment by trudyhood** [comment]
Would you reinstall Microsoft WebView2 from here:
[gen -domain](https://go.microsoft.com/fwlink/p/?LinkId=2124703)

We have to work on this issue. I will let you know after we do something.

**Comment by akshayalix** [comment]
Hi, I download and tried to install WebView2 but it failed as it says "It's already installed". Thank you for replying.

**Comment by trudyhood** [comment]
Did it solve the issue?

**Comment by akshayalix** [comment]
No, I accidentally marked it closed.

**Comment by nikorn** [comment]
The same problem. Windows 10 22H2 (19045.2604).
There is no "EBWebView" folder, WebView2 is "already installed"

**Comment by trudyhood** [comment]
Please update the latest pre-release version 355: 
https://github.com/vpnhood/VpnHood/releases

Unfortunately, we couldn't find why Microsoft WebView does not work properly on some Windows. However, we tried to fix it with this workaround: 
An "Open in Browser" has been added to the notification menu. Also, it automatically opens the browser if VpnHood detects that the WebView is not initialized properly. Please let me know if you can still see the blue screen. It should open your default browser instead.

**Comment by akshayalix** [comment]
Nice, the pre-release version 355 solved the problem👌. Thank You.
