### ISSUE TITLE
not change server in vpn hood access server

### ISSUE THREAD

**Issue by amir-shabani12** [vpnhood/VpnHood#226]
hi,
My server is blocked. I am trying to add another server. But in the Access Points section, the panel shows the address of the previous vps and is constantly being configured

**Comment by roozbehsat** [comment]
hi, add new group, set the server in new group.

**Comment by amir-shabani12** [comment]
> hi, add new group, set the server in new group.

I'm sorry
This did not solve my problem.
I think this can be solved by completely deleting a server and then adding it

**Comment by roozbehsat** [comment]
you can edit your Ip in server Access Points

**Comment by trudyhood** [comment]
@amir-shabani12  I admit that we have to implement removing the server; however, it wouldn't solve the issue of the "configuring..." state. I believe you are facing another issue; try to assign a group for your server so it tries to set their access points (IPs) automatically. If it doesn't work, you need to configure the IPs manually. Check the error on your server log. We are here for you to solve the issue if the problem persists.

Again we will implement "removing server", but I am sure it won't solve this issue. Let me know the result.

**Comment by trudyhood** [comment]
You can Delete a Server from the access server now. However, I think it wouldn't solve the issue. Feel free to comment here if the problem still exits.

**Comment by amir-shabani12** [comment]
very very good. Thanks. The problem was solved. Thanks for fixing the
server deletion issue. Please add the ability to delete the name of the
server group

در تاریخ چهارشنبه ۴ ژانویهٔ ۲۰۲۳،‏ ۴:۲۳ Trudy ***@***.***>
نوشت:
