### ISSUE TITLE
Question about protocol and encryption of data

### ISSUE THREAD

**Issue by francescovigot** [vpnhood/VpnHood#231]
Hello
sometimes users concern about their information over the network when they are using our VPN and they ask what the encryption  system that we have used for the VPN app or they ask about the protocol and security of the app
what is your answer for these users?

**Comment by trudyhood** [comment]
Simple, it is HTTPS (actually TLS), Also, nowadays, most connections are already HTTPS, so VpnHood somehow is TLS over TLS.
For ordinary users, it makes no difference, they need to trust the server owner in some respect which is beyond this topic.

You may be interested in the following topic too:
https://github.com/vpnhood/VpnHood/discussions/77
