### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by lolminerxmrig** [vpnhood/VpnHood#232]
Hi All.

A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

**Comment by trudyhood** [comment]
Hi, 
Do you use Public Servers or Private Servers?

**Comment by lolminerxmrig** [comment]
Only for me

**Comment by lolminerxmrig** [comment]
Not config pv or pu.
Install win server and client win.
Send error :

A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

**Comment by trudyhood** [comment]
perhaps 443 is unreasonable. make sure the server firewall does not block it. 
Please send me your server log file.

**Comment by lolminerxmrig** [comment]
server firewall disable.
Log file whare ?

**Comment by trudyhood** [comment]
The logs exist in the following locations:

Windows:
```
C:\Program Files\VpnHood\VpnHoodServer\storage\logs\log.txt
```

Linux:
```
/opt/VpnHoodServer/storage/logs/log.txt
```

**Comment by trudyhood** [comment]
Feel free to add comments to this issue. I closed it for one-week inactivity.
