### ISSUE TITLE
Users can use a deleted tokens

### ISSUE THREAD

**Issue by abbasalpha** [vpnhood/VpnHood#238]
Hello dear coding team
at first, thank you for this brilliant product
there are some important problems with the web base console that ill list them.
1. when we limit a token(user) by traffic after first connecting and disconnection it's not able to connect again with the error "all traffic consumed" until I remove traffic limitation.
2. if I create a new access token and delete it, it still works on the device that the token has been set.
3. user will not disconnect after reach limitation of time or traffic  until directly click on disconnect on client app. even it works after disconnection of internet (long time DC)
4. changes (disable or enable, traffic limitation, time limitation, ...) will not take effect until DC by user it means user is unlimited because it wont be DC after dc of internet and vpn is still working.
Thanks

**Comment by roozbehsat** [comment]
"2.if I create a new access token and delete it, it still works on the device that the token has been set."
I test it, it is very bad bug. 
please help.

**Comment by trudyhood** [comment]
hi,

> when we limit a token(user) by traffic after first connecting and disconnection it's not able to connect again with the error "all traffic consumed" until I remove traffic limitation.

I created an issue for it. 

> if I create a new access token and delete it, it still works on the device that the token has been set.
user will not disconnect after reach limitation of time or traffic until directly click on disconnect on client app. even it works after disconnection of internet (long time DC)
changes (disable or enable, traffic limitation, time limitation, ...) will not take effect until DC by user it means user is unlimited because it wont be DC after dc of internet and vpn is still working.
Thanks

It happens if you change the token while the user is connected due to our caching system. This will not happen if you set the limitation on token creation time. in the worst case, they can use a little more than you expect. Let us not be so greedy, he/she will be disconnected sooner or later :)

**Comment by roozbehsat** [comment]
I delet the token, but the deleted token still work!!!

**Comment by trudyhood** [comment]
Ok, it remains in our access server's cache due to performance considerations. We will fix this issue.

**Comment by abbasalpha** [comment]
> hi,
> 
> > when we limit a token(user) by traffic after first connecting and disconnection it's not able to connect again with the error "all traffic consumed" until I remove traffic limitation.
> 
> I created an issue for it.
> 
> > if I create a new access token and delete it, it still works on the device that the token has been set.
> > user will not disconnect after reach limitation of time or traffic until directly click on disconnect on client app. even it works after disconnection of internet (long time DC)
> > changes (disable or enable, traffic limitation, time limitation, ...) will not take effect until DC by user it means user is unlimited because it wont be DC after dc of internet and vpn is still working.
> > Thanks
> 
> It happens if you change the token while the user is connected due to our caching system. This will not happen if you set the limitation on token creation time. in the worst case, they can use a little more than you expect. Let us not be so greedy, he/she will be disconnected sooner or later :)

I Am not greedy but i have users that arent disconnected for a week even i disabled and limited him.
Iam sure he slept but his phone i don't think so :D
btw iam so grateful for support.

**Comment by abbasalpha** [comment]
> Ok, it remains in our access server's cache due to performance considerations. We will fix this issue.

Thank's trudyhood.

**Comment by sohratjana** [comment]
Good

**Comment by trudyhood** [comment]
This issue should be solved now. However, if you delete or update a token, it will not affect already connected users until they get disconnected. Please feel free to add comments to this issue if the problem continues. Again, thank you for reporting this.

**Comment by roozbehsat** [comment]
Another error: I can not connect to cpnhood!
