### ISSUE TITLE
"all traffic consumed" Error traffic limit

### ISSUE THREAD

**Issue by trudyhood** [vpnhood/VpnHood#240]
When we limit a token by traffic after first connecting and disconnection it's not able to connect again with the error "all traffic consumed" until I remove traffic limitation.
#238

**Comment by abbasalpha** [comment]
> When we limit a token by traffic after first connecting and disconnection it's not able to connect again with the error "all traffic consumed" until I remove traffic limitation.
> #238 

Thank you so much for Following up this issue.

**Comment by trudyhood** [comment]
Duplicate of #267 
It has been fixed. Both Client and Server must have version 360 or upper otherwise client will be disconnected but may see invalid traffic in its UI.
