### ISSUE TITLE
installing on arm architecture

### ISSUE THREAD

**Issue by rezarms** [vpnhood/VpnHood#244]
It seems it's not supported on arm arc.

I tried to run and got below error
`/opt/VpnHoodServer/v2.6.336/VpnHoodServer: 1: Syntax error: ")" unexpected`

**Comment by trudyhood** [comment]
Hi, Yes, we don't compile it for arm, just for easier deployment maintenance and also there was no demand.

**Comment by rezarms** [comment]
Is there any way to have release in arm as well?

**Comment by trudyhood** [comment]
It would be easy. actually it is just a flag. I will look at it.

**Comment by abolfazl6** [comment]
Hello
How to place your domain?

**Comment by kimmko** [comment]
> I have added arm64 for you, but we have yet to test it on a real arm machine.
> 
> ```
> sudo su -c "bash <( wget -qO- https://github.com/vpnhood/VpnHood/releases/latest/download/VpnHoodServer-linux-arm64.sh)"
> ```
> 
> I would be grateful if you let me know if it works. Thank you

@trudyhood I'm trying to run this on my arm64 VPS but that link now gives a 404. Any updates on how to run this no ARM?

**Comment by trudyhood** [comment]
@kimmko The address has been changed. plesae look at here:
https://github.com/vpnhood/VpnHood/wiki/How-to-run-VpnHood-Server-on-Linux
