### ISSUE TITLE
Multi-hop routing

### ISSUE THREAD

**Issue by joephalex** [vpnhood/VpnHood#246]
Hi, 

I was wondering in android whether we have this feature. Also,  would it be possible to disconnect from the first server and keep the last one it's connected to or we can make both open.

I have tried to create another _vpnHoodClient and named it _vpnHoodClient2 and I tried to connect to it after the _vpnHoodClient was connected. _vpnHoodClient returns the accurate endpoint IP based on the access token same goes to _vpnHoodClient2 but when I run to check the public IP it returns the first one eventhough _vpnHoodClient2 is connected successfully

**Comment by trudyhood** [comment]
Hi, It is possible in theory, but we haven't designed it like that. 
First, what's the benefit of having multiple IPs on the same machine?
Second, you can't do that with VpnHoodClient. VpnHoodClient uses a shared packet capture, and you can not run multiple packet capture on android. I think there would be some conflict on Windows, too, unless we design it to work with multiple servers. 

in short:
I am afraid to say that VpnHood does not support it.
