### ISSUE TITLE
Update breaks configuration

### ISSUE THREAD

**Issue by Kompas9** [vpnhood/VpnHood#247]
Running server on Windows 10, after automatic update, configuration lost user set port settings and reverted to default. Shouldn't it be kept between updates ?

**Comment by trudyhood** [comment]
Oh! It has to keep and uses previous data. 
what was your last version?
please check the VpnHood server folder. maybe your server was too old and your data exists outside of storage folder. there is no code in installation they delete anything.  i thing your tokens still exist there. That's important to us.

**Comment by Kompas9** [comment]
appsettings.json has the port settings, and it's in /VpnHoodServer/v2.xxxx/, while the storage folder only holds last-congif.json that also got overwritten.

Updated from v2.6329 to v2.6337

**Comment by trudyhood** [comment]
You need to create appsettings.json in the storage folder; other locations are counted as binary. The old configuration should exist, so copy it to the storage folder
![image](https://user-images.githubusercontent.com/72891124/213550372-003b38c5-bda5-423e-942a-be9450296dcd.png)

storage folder
![image](https://user-images.githubusercontent.com/72891124/213550500-51372cc4-080b-4c63-81dd-e9d7b81327ba.png)
