### ISSUE TITLE
VpnHoodClient-win-x64.exeFailed - Virus detected

### ISSUE THREAD

**Issue by demon740** [vpnhood/VpnHood#249]
each time the file is downloaded, it is deleted by Kaspersky antivirus.

**Comment by trudyhood** [comment]
It is the same issue. We have to publish as MSI to get rid of this problem. Also, we will sign the exe file soon, and we hope it solves this issue.
#194
#250

**Comment by trudyhood** [comment]
Hi, We have released an MSI version. It doesn't have the false virus detection issue:
https://github.com/vpnhood/VpnHood/releases/latest/download/VpnHoodClient-win-x64.msi
