### ISSUE TITLE
Virus detected in new version

### ISSUE THREAD

**Issue by SMARTSEEU** [vpnhood/VpnHood#250]
again virus

Kaspersky

HEUR:Trojan.Win32.Agentb.gen
ZoneAlarm by Check Point

HEUR:Trojan.Win32.Agentb.gen

**Comment by trudyhood** [comment]
It is the same issue. We have to publish as MSI to get rid of this problem. Also, we will sign the exe file soon, and we hope it solves this issue.
#194

**Comment by B-andi-T** [comment]
I still can't update. Kaspersky immediately deletes the installation file

**Comment by B-andi-T** [comment]
v2.6.341-prerelease / I still can't update. Kaspersky deletes the installation file.

**Comment by trudyhood** [comment]
Hi, We have released an MSI version. It doesn't have the false virus detection issue:
https://github.com/vpnhood/VpnHood/releases/latest/download/VpnHoodClient-win-x64.msi
