### ISSUE TITLE
Connecting to proxy server

### ISSUE THREAD

**Issue by joephalex** [vpnhood/VpnHood#251]
I would to check whether it's possible to connect to a proxy server first which rotates the IP address just to conceal the VPN server IP then disconnecting from the proxy server in android once the vpn is connected successfully. 

So we pass the proxy host, port, username and password  and we connect to the VPN will be connected through the proxy first. Then upon successful connection then the connection will be closed.

**Comment by trudyhood** [comment]
The question is "what is the address of that proxy server"? What will be happened if that address get blocked?

**Comment by joephalex** [comment]
I have seen few proxy service providers offering the possibility of rotating the IP address upon each request or with time interval like 10 or 30 minutes. It's just a thought came to me to conceal the VPN server IP in the case of heavy filtering. I am not really sure whether it's applicable or no.

I do really appreciate your feedback

**Comment by trudyhood** [comment]
so how do you connect to the proxy servers at first step before ip rotary? what is the initial ip address or domain of the proxy server?

**Comment by joephalex** [comment]
I have seen some where the initial connection to the proxy they do offer either by domain and by IP address but if I choose their IP their  HTTP Proxy Host IP keeps changing evetime whenever I check the configuration for their rotary IP. I am still checking with other more to see if they do have the same thing.

**Comment by trudyhood** [comment]
I still believe it just makes things complicated but no gain. I can imagine the server changes its IP while some users are office, so users will not be able to connect and find the server again because the IP has changed and the domain is blocked. Users will have no way to find the new IP automatically. What do you think?
