### ISSUE TITLE
v2.6.339 Error 404 Not Found.

### ISSUE THREAD

**Issue by M3is4M** [vpnhood/VpnHood#253]
maybe following lines need correction in VpnHoodServer-linux-x64.sh:

# Default arguments
packageUrl="https://github.com/vpnhood/VpnHood/releases/download/v2.6.339/VpnHoodServer-linux-x64.tar.gz";
versionTag="v2.6.339";

**Comment by trudyhood** [comment]
Thank you for reporting. It has been fixed.
