### ISSUE TITLE
Windows 7 Client

### ISSUE THREAD

**Issue by precords** [vpnhood/VpnHood#255]
Would love to have a Windows 7 client for VPNhood.   Any way to do this??

**Comment by trudyhood** [comment]
Hi, I can understand that, but Microsoft does not support Windows 7 anymore:
https://www.microsoft.com/en-us/windows/end-of-support?r=1

VpnHood is under development every day, and keeping outdated Operating Systems costume a lot of energy from us and makes us slow.

You may find someone to download the source code and compile it for windows 7.
I am sorry for this.
