### ISSUE TITLE
Private server or other public for game "Albion Online"

### ISSUE THREAD

**Issue by Pytles** [vpnhood/VpnHood#258]
Hello, is anyone able to create a server for me to play with the lowest possible ping? Albion is located in Washington DC and I have a higher ping on a public server. My ISP location is Poland central Europe

**Comment by trudyhood** [comment]
Unfortunately, we can't support this on our free public servers. We may offer it as paid service in the future, but it is not available at the moment too. We will be happy to see you in the future.

Thank you for trying VpnHood!
