### ISSUE TITLE
users can use same account even maxClient=1 is set

### ISSUE THREAD

**Issue by free-keyboards** [vpnhood/VpnHood#262]
I made an account using `-maxClient=1` flag, then I added this account to 3 different devices and all of them were able to use the same account. 
the only difference was that the 2th and 3th devices got alert messages that they are disconnected because of using the same account BUT they didn't disconnect at all and the connection were still alive and the connected sign was active on the devices.

**Comment by trudyhood** [comment]
The message said it disconnected the other user's snot itself. It takes something about 1~10 minutes till the other user get disconnected. We may change this policy soon.
