### ISSUE TITLE
i cant login with vpnhood in new world 

### ISSUE THREAD

**Issue by RezZz13** [vpnhood/VpnHood#263]
guys help me
i cant login with vpnhood in game new world

**Comment by trudyhood** [comment]
Can you send me the log?
Are you sure the game does not block traffic from your server?

**Comment by trudyhood** [comment]
Ok, the error is apparent. The game does not accept your server IP. You need to find a server from a location that they get. VPN changes your IP to VpnServer IP and location. If the game rejects the Server IP, you can't do anything. You may also find some VPN services (not protocol) that offer servers in different locations. Some games also block famous hosting providers.

I'm sorry that the game rejects your server IP; please let us know if you have an idea so we can work on it. Feel free to add comments to this closed issue.
