### ISSUE TITLE
Access Server cannot be loaded.

### ISSUE THREAD

**Issue by AliMoal** [vpnhood/VpnHood#265]
Unfortunately, the webpage of Access Server (console.vpnhood.com) cannot be loaded perfectly in Iran.
Is there another way to add clients or servers with Access Server full feature?
For example, a command line in server.

**Comment by trudyhood** [comment]
You can use VPN to access the Access Server. Also, There are some command-lines to generate token and run without our access-server, but they will be unmanaged and have limited functionality. Check it out here:
https://github.com/vpnhood/VpnHood/wiki/How-to-run-VpnHood-Server-on-Linux

for more information, check command line help.
/opt/VpnHoodServer/vhserver /?
