### ISSUE TITLE
Max Traffic has a bug!

### ISSUE THREAD

**Issue by asoMansoury** [vpnhood/VpnHood#267]
When I define max traffic, the user connects to the server and everything is ok, but once they disconnect and try again to connect, the server shows an error message that their quota has exceeded, meanwhile their volume traffic is not exceeded.

**Comment by trudyhood** [comment]
Yes, it is a known bug and must be solved.

**Comment by trudyhood** [comment]
It has been fixed. Both Client and Server must have version 360 or upper otherwise client will be disconnected but may see invalid traffic in its UI.
