### ISSUE TITLE
Added multiple server to client application

### ISSUE THREAD

**Issue by asoMansoury** [vpnhood/VpnHood#268]
I think that would be so great if you added multiple servers to the client app. For example when I define a user and choose group 1 which has 2 servers if the access point key adds all servers to the client app and then the client app based on which server is online tries to connect it and tunneling the traffic through it.

**Comment by trudyhood** [comment]
Access Server automatically chooses the best working server if you our many servers in one group. However, the first server must be up and reliable. Vpnhood doesn't support the feature you requested.

**Comment by AmirHosseinCV** [comment]
It would be great if you could add this feature, as it exists in some VPN applications like v2ray and is quite useful, especially when you want to provide access to multiple servers in different locations for your users.

**Comment by trudyhood** [comment]
Multiple Locations feature in single token has been integrated
