### ISSUE TITLE
server status stay on Cofiguring mod !!

### ISSUE THREAD

**Issue by javad490** [vpnhood/VpnHood#271]
hi, After i uninstall vpnhood on server and reinstall new version Linux on server, then install vpnhood on Linux ubuntu 22 server, and refresh vpnhood server consol , after 1 day server status stay on " Configuring" orang propmt! also i reinstall vpnhood on server but this bug not fix !! 
in iran not client connect to server and government apply hard filtering on internet !!! 
please help me to fix it also improve vpnhood that iranian people can use and connect.
server consol prompt message is:
Status:Configuring 
Error" Address already inuse" 
thanks

**Comment by trudyhood** [comment]
Hi,
Please send us the server log located in the storage folder. You may also see an error message on the server page, so tell me what it is that if any.
support@vpnhood.com

**Comment by javad490** [comment]
Status:Configuring
Error:Address Already inuse

**Comment by javad490** [comment]
> Hi, Please send us the server log located in the storage folder. You may also see an error message on the server page, so tell me what it is that if any. [support@vpnhood.com](mailto:support@vpnhood.com)
Status:Configuring
Error:Address Already inuse
also
i update vpnhood windows and android client to latest version and install latest linux server version

**Comment by trudyhood** [comment]
> Status:Configuring Error:Address Already inuse

It means another process has already used the port (usually 443). Please restart your server; if the issue persists, try finding which service is using the port. I closed the issue; feel free to reply to this closed issue.

you can use the following command to see which application using the port:
```sh
sudo lsof -n -i :443 | grep LISTEN
```

**Comment by javad490** [comment]
> Hi, Please send us the server log located in the storage folder. You may also see an error message on the server page, so tell me what it is that if any. [support@vpnhood.com](mailto:support@vpnhood.com)

i attach error screenshot
![Screenshot_20230215-114642](https://user-images.githubusercontent.com/123890771/218972404-fe1350a8-9779-469b-afa6-b3206990f8fb.png)

**Comment by trudyhood** [comment]
You can use the following command to see which application is using the port:
```sh
sudo lsof -n -i :443 | grep LISTEN
```

**Comment by javad490** [comment]
> > Status:Configuring Error:Address Already inuse
> 
> It means another process has already used the port (usually 443). Please restart your server; if the issue persists, try finding which service is using the port. I closed the issue; feel free to reply to this closed issue.
> 
> you can use the following command to see which application using the port:
> 
> ```shell
> sudo lsof -n -i :443 | grep LISTEN
> ```

thanks, i restart server few times and not fix ...
i use this cmd command and replay yoy.
i also only v2ray vpn servise on server , maybe bug from this service...

**Comment by trudyhood** [comment]
This is not a bug. Each port can be assigned only one process, so if another app already uses it, you need to change it. For example, you can use 4443 instead 443 or stop the other process.

**Comment by javad490** [comment]
thanks, last day i restart server few times, but bug not fix, also i uninstall vpnhood on server then reinstall but not fix. i test your cmd command and replay you.on my vps server only run vpnhood server and v2ray vpn service, maybe eeror for this ?! if vpnhood client connect and work well, i remove and delete V2ray vpn service from my server.also i diagnostic and send report from vpnhood windows and android client for you at last day.big thanks 



Sent from Yahoo Mail on Android 
 
  On Wed, Feb 15, 2023 at 11:50, ***@***.***> wrote:   



Status:Configuring Error:Address Already inuse


It means another process has already used the port (usually 443). Please restart your server; if the issue persists, try finding which service is using the port. I closed the issue; feel free to reply to this closed issue.

you can use the following command to see which application using the port:
sudo lsof -n -i :443 | grep LISTEN

**Comment by trudyhood** [comment]
Ok, feel free to ask any more question you have.

**Comment by javad490** [comment]
ok. my expert on windows more,please send me linux ubuntu 22 command that i close and stop all process on port 443 temporary, then after Configuring fix on vpnhood server, i restart server.sorry for my poor english

Sent from Yahoo Mail on Android 
 
  On Wed, Feb 15, 2023 at 12:04, ***@***.***> wrote:   


This is not a bug. Each port can be assigned only one process, so if another app already uses it, you need to change it. For example, you can use 4443 instead 443 or stop the other process.

**Comment by trudyhood** [comment]
Closing the process is useless because it will start again. You need to uninstall the process or change the port.
You can easily find Linux commands on google.

**Comment by javad490** [comment]
> Closing the process is useless because it will start again. You need to uninstall the process or change the port. You can easily find Linux commands on google.

ok, i stop v2ray (xray) process on port 443 and now test vpnhood server cosol that Configuring Status is fix and client can connect to vpnhood server well, if client can use vpnhood well, i uninstall Xray vpn from server.
big thanks for your progect and help

**Comment by trudyhood** [comment]
You are welcome, I hope VpnHood works for you and your users.

**Comment by javad490** [comment]
thanks, i stop Xray vpn process and disable auto Xray start , and now fix Configuring status on vpnhood, it change to idle i make 2 client private and public for test vpnhood connection and speed is welli hope vpnhood connection work well on hard government internet filtering in iran, hare Adguard vpn,Proton vpn and most famos vpn ia not connect , only Tor and Orbot vpn work with slow speed and Geph Vpn is Work well specially Plus version that sell monthly $5 and 5 user can use on account.big thanks for update and improve vpnhood and help Freedom in the worled



Sent from Yahoo Mail on Android 
 
  On Wed, Feb 15, 2023 at 13:00, ***@***.***> wrote:   


You are welcome, I hope VpnHood works for you and your users.

**Comment by trudyhood** [comment]
I appreciate you for sharing this information with us.

**Comment by javad490** [comment]
i test client on udp and tcp protocole now, also install latest version vps server and client  but not connect in iran...! i hope you improve vpnhood protocol and can connect and use it in iran.only this Geph vpn is connect and work well in iran site:geph.iothanks
Sent from Yahoo Mail on Android 
 
  On Wed, Feb 15, 2023 at 13:20, ***@***.***> wrote:   


I appreciate you for sharing this information with us.

**Comment by trudyhood** [comment]
Please share the client diagnostic with us to find out why it doesn't work in Iran for your server. Many users are connected to VpnHood servers at this time.

**Comment by javad490** [comment]
also i send diagnostic report via vpnhood client form now, my server consol vpnhood account email ***@***.***

Sent from Yahoo Mail on Android 
 
  On Wed, Feb 15, 2023 at 13:20, ***@***.***> wrote:   


I appreciate you for sharing this information with us.

**Comment by trudyhood** [comment]
> also i send diagnostic report via vpnhood client form now, my server consol vpnhood account email ***@***.*** Sent from Yahoo Mail on Android On Wed, Feb 15, 2023 at 13:20, ***@***.***> wrote: I appreciate you for sharing this information with us. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

Please share the diagnostic reference id with us

**Comment by javad490** [comment]
in iran  , government apply hard internet filtering from 3 month ago like china, most protocole is filterd, only Tor and Orbot vpn is work with low speed, and Geph vpn is connect and speed is well, becouse developer is from china peopel and firest make it for china filtering and now make and improve it for iran, also he nake private protcol for Geph vpn.Geph vpn site:geph.ioDeveloper telegram ***@***.*** channel: https://t.me/gephannouncegeph vpn make windows,abdroid,mac client version and now make beta version for ios:nullchinchilla in Official Geph Users | 迷霧通官方用戶群  
|  
|   
|   
|   |    |

   |

  |
|  
|   |  
nullchinchilla in Official Geph Users | 迷霧通官方用戶群
 
拾� 迷雾通 iOS beta 测试再一次开始了！欢迎大家加入：https://testflight.apple.com/join/Ai6YTLmC 拾� Geph iOS beta testing has started again! You can join here: https://testflight.apple.com/join/Ai6YTLmC
  |   |

  |

  |

  
now also V2ray vpn (Xray) via config vmess+ws+Tls is connect in iran with 100 ms to 500 ms ping , but after few day government filter it and must make new config for client..big thanks

Sent from Yahoo Mail on Android 
 
  On Wed, Feb 15, 2023 at 13:39, ***@***.***> wrote:   


Please share the client diagnostic with us to find out why it doesn't work in Iran for your server. Many users are connected to VpnHood servers at this time.

**Comment by javad490** [comment]
Info 
| 13:55:24.7873 |  | AppVersion: 2.7.350.0

Info 
| 13:55:24.7878 |  | Time: 2023-02-15 10:25:24Z

Info 
| 13:55:24.7880 |  | OS: asus: ASUS_X00PD, Android: 8.0.0

Info 
| 13:55:24.7881 |  | UserAgent: Mozilla/5.0 (Linux; Android 8.0.0; ASUS_X00PD Build/OPR1.170623.032; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/109.0.5414.117 Mobile Safari/537.36

Warn 
| 13:55:31.6361 |  | HttpTest: Failed!, Url: https://www.microsoft.com/. Message: The operation was canceled.

Info 
| 13:55:35.4355 |  | Country: Iran 

Info 
| 13:55:35.4362 |  | TokenId: **-bf70-e3a0d0879fce, SupportId: **03

Trac 
| 13:55:35.4371 |  | Checking the Internet connection...

Info 
| 13:55:35.4446 |  | HttpTest: Started, Url: https://www.google.com/, Timeout: 10000...

Info 
| 13:55:35.4466 |  | HttpTest: Started, Url: https://www.quad9.net/, Timeout: 10000...

Info 
| 13:55:35.4474 |  | HttpTest: Started, Url: https://www.microsoft.com/, Timeout: 10000...

Info 
| 13:55:36.0316 |  | HttpTest: Succeeded, Url: https://www.google.com/.

Trac 
| 13:55:36.0319 |  | Checking the VpnServer ping...

Info 
| 13:55:36.0323 |  | PingTest: Started, RemoteAddress: 194.*.*.174, Timeout: 10000...

Info 
| 13:55:38.2578 |  | PingTest: Succeeded, RemoteAddress: 194.*.*.174.

Trac 
| 13:55:38.2583 |  | Pinging server is OK.

Info => Client
| 13:55:38.2619 |  | UseUdpChannel: False, MinWorkerThreads: 8, CompletionPortThreads: 8

Info => Client
| 13:55:38.2621 |  | Client Version: 2.7.350.0, ClientId: **-b085-87f5bcfa99d7

Info => Client
| 13:55:38.2621 |  | Client is Connecting

Trac => Client
| 13:55:38.2636 | Session | Connecting to Server: 194.*.*.174:443...

Info 
| 13:55:40.6853 |  | HttpTest: Succeeded, Url: https://www.microsoft.com/.

Warn 
| 13:56:05.4828 |  | HttpTest: Failed!, Url: https://www.quad9.net/. Message: The operation was canceled.

Erro => Client
| 13:56:09.3752 |  | Disposing. Error! System.Net.Sockets.SocketException (0x80004005): Connection timed out
  at System.Net.Sockets.SocketAsyncResult.CheckIfThrowDelayedException () [0x00014] in <d6ee3156d5894beab44d598d75c85840>:0 
  at System.Net.Sockets.Socket.EndConnect (System.IAsyncResult asyncResult) [0x0002c] in <d6ee3156d5894beab44d598d75c85840>:0 
  at System.Net.Sockets.TcpClient.EndConnect (System.IAsyncResult asyncResult) [0x0000c] in <d6ee3156d5894beab44d598d75c85840>:0 
  at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x00019] in <a4a637b53b634d43a7f2f33644dce7e9>:0 
--- End of stack trace from previous location where exception was thrown ---

  at VpnHood.Common.Utils.Util.RunTask (System.Threading.Tasks.Task task, System.TimeSpan timeout, System.Threading.CancellationToken cancellationToken) [0x00133] in <541d359170994ab1a632336c587e50e9>:0 
  at VpnHood.Client.VpnHoodClient.GetTlsConnectionToServer (Microsoft.Extensions.Logging.EventId eventId, System.Threading.CancellationToken cancellationToken) [0x002da] in <0da1f1b727d4461aa2d5fb57943d9053>:0 
  at VpnHood.Client.VpnHoodClient.ConnectInternal (System.Threading.CancellationToken cancellationToken, System.Boolean redirecting) [0x00086] in <0da1f1b727d4461aa2d5fb57943d9053>:0 
  at VpnHood.Client.VpnHoodClient.Connect () [0x001a5] in <0da1f1b727d4461aa2d5fb57943d9053>:0 

Trac => Client
| 13:56:09.3754 |  | Disconnecting...

Info => Client
| 13:56:09.3755 |  | Client is Disconnecting

Trac => Client
| 13:56:09.3785 |  | Shutting down...

Trac => Client
| 13:56:09.3792 |  | Disposing TcpProxyHost...

Trac => Client
| 13:56:09.3793 |  | Disposing Tunnel...

Trac => Client
| 13:56:09.3795 |  | Disposing ClientProxyManager...

Trac => Client
| 13:56:09.3796 |  | Disposing Nat...

Info => Client
| 13:56:09.3799 |  | Client is Disposed

Info => Client
| 13:56:09.3868 |  | Bye Bye!

Erro  | 13:56:09.3880 | | Connection timed outi send client diagnnostic log with report formlog is: 

Sent from Yahoo Mail on Android 
 
  On Wed, Feb 15, 2023 at 13:40, ***@***.***> wrote:   



also i send diagnostic report via vpnhood client form now, my server consol vpnhood account email @.*** Sent from Yahoo Mail on Android On Wed, Feb 15, 2023 at 13:20, @.> wrote: I appreciate you for sharing this information with us. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.>


Please share the diagnostic reference id with us

**Comment by trudyhood** [comment]
Can you share a VpnHood access key to your server with us?
support@vpnhood.com

**Comment by javad490** [comment]
diagnostic id that i send via report to you ***@***.*** my server access key is:vh://eyJuYW1lIjoidnBzMjAyMyIsInYiOjEsInNpZCI6MTAwMiwidGlkIjoiYzg1Yzg3ZjAtZTYzNi00YTRjLTk1MjItZWQ1NmVjOGEwZGUzIiwic2VjIjoiTEhNQTQyQXIrMk5CUVQ0dXJJelVYdz09IiwiaXN2IjpmYWxzZSwiaG5hbWUiOiJzby53YWVnYWVkYWVzaGUubmV0IiwiaHBvcnQiOjAsImNoIjoiOFM2eVFCdjFkcjE5bi93TSszV3JtUm9qdnpvPSIsInBiIjpmYWxzZSwidXJsIjpudWxsLCJlcCI6WyIxOTQuNjEuMTIwLjE3NDo0NDMiXX0=
i hope you fix iti attach Geph vpn screenshot that connect and speed is well in iran

thanks

Sent from Yahoo Mail on Android 
 
  On Wed, Feb 15, 2023 at 14:05, ***@***.***> wrote:   


Can you share a VpnHood access key to your server with us?
***@***.***

**Comment by javad490** [comment]
i hope you can fix connection in iran, my vpnhood server access key for test:

vh://eyJuYW1lIjoidnBzMjAyMyIsInYiOjEsInNpZCI6MTAwMiwidGlkIjoiYzg1Yzg3ZjAtZTYzNi00YTRjLTk1MjItZWQ1NmVjOGEwZGUzIiwic2VjIjoiTEhNQTQyQXIrMk5CUVQ0dXJJelVYdz09IiwiaXN2IjpmYWxzZSwiaG5hbWUiOiJzby53YWVnYWVkYWVzaGUubmV0IiwiaHBvcnQiOjAsImNoIjoiOFM2eVFCdjFkcjE5bi93TSszV3JtUm9qdnpvPSIsInBiIjpmYWxzZSwidXJsIjpudWxsLCJlcCI6WyIxOTQuNjEuMTIwLjE3NDo0NDMiXX0=


Sent from Yahoo Mail on Android 
 
  On Wed, Feb 15, 2023 at 14:05, ***@***.***> wrote:   


Can you share a VpnHood access key to your server with us?
***@***.***

**Comment by trudyhood** [comment]
Please disconnect your vpn. and browse the following address with your browser:
https://your-server-ip/

Can you see the following page?
![image](https://user-images.githubusercontent.com/72891124/219008348-6c23d7bc-9162-4111-a2b3-94021648001c.png)

**Comment by javad490** [comment]
no, i can not see witout vpn, i also attach screebshot



Sent from Yahoo Mail on Android 
 
  On Wed, Feb 15, 2023 at 14:26, ***@***.***> wrote:   


Please disconnect your vpn. and browse the following address with your browser:
https://your-server-ip/

Can you see the following page?

**Comment by javad490** [comment]
also i can not login and open vpnhood server consol without vpn

Sent from Yahoo Mail on Android 
 
  On Wed, Feb 15, 2023 at 14:26, ***@***.***> wrote:   


Please disconnect your vpn. and browse the following address with your browser:
https://your-server-ip/

Can you see the following page?

**Comment by trudyhood** [comment]
> no, i can not see witout vpn, i also attach screenshot 

I think you shared your server's access key freely with the public so your government find it and put your server IP on their blacklist so you cannot establish a very simple TCP connection. No protocol can save this situation; you need to keep your server access key private; otherwise, it will get blocked sooner or later. Buy another server and share its key with a few people.

Read this for more information:
https://github.com/vpnhood/VpnHood/wiki/Can-a-network-provider-block-VpnHood

**Comment by javad490** [comment]
no, i make vps server fo private use not public use... i not share server access private ke to any one, i run vps and vpnhood server 3 day ago and this server access private key is only have me and not have it no one..

Sent from Yahoo Mail on Android 
 
  On Wed, Feb 15, 2023 at 14:48, ***@***.***> wrote:   



no, i can not see witout vpn, i also attach screenshot


I think you shared your server's access key freely with the public so your government find it and put your server IP on their blacklist so you cannot establish a very simple TCP connection. No protocol can save this situation; you need to keep your server access key private; otherwise, it will get blocked sooner or later. Buy another server and share its key with a few people.

Read this for more information:
https://github.com/vpnhood/VpnHood/wiki/Can-a-network-provider-block-VpnHood

**Comment by trudyhood** [comment]
1) Please send me a screenshot of this to us. (hide the server IP address)
```
https://your-server-ip/
```

2) Can you connect to your server with ssh without any VPN?

**Comment by javad490** [comment]
hi, i use my vps linux server for private and personall use it, my server is not public and i setup it last week and server location is on Amesterdam not in iran.also i have only my vpnhood private key and server ip and not give to any one...only i give vpnhood public private key to you for test and improve vpnhood,then i delete this key.
yes my server ip is not ban or block in iran, i ping it without any VPN , also i set proxy domain on Cloadflare for safe my server ip.
Good news, today my vpnhood Client is Connect to my server after 20 to 30 second , but data speed is very slow and every few minutes connection is disconected !i hope you impove vpnhood that resistance on storange intenet filtering in iran and china .... iran Government Apply internet Filtering and hard limit from 3 month ago like china filtering, becouse most people is want freedom and protetst and government and police is kill more 500 young protest...if your vpn can connect and data speed is well, your vpn is best vpn in the worled like Geph vpn that now working well in iran and china and developer sell plus version to more 1,500,000,000 people on china and iran.i am computer programer, my site is: javad490.ir and karajjavad.ir i make sub domain for vps linux server  that name is: vps.javad490.ir and set proxy on clouadflare for server ip keep safe...you ask me screenshot from what?i use my vps server is only for vpn and proxy, and not use it public and html or other host...my personal site host is not on my vps server storage..Good Luck 

Sent from Yahoo Mail on Android 
 
  On Thu, Feb 16, 2023 at 7:03, ***@***.***> wrote:   

   
   - Please send me a screenshot of this to us. (hide the server IP address)
https://your-server-ip/
   
   - Can you connect to your server with ssh without any VPN?

**Comment by trudyhood** [comment]
Dear Javad,
You look so active and I appreciate what you have done. However, let's focus on one subject per issue at a time, so we don't get confused with double problems. Feel free to create more issues if you have any.

Last time you said you couldn't connect to your server via VpnHood, but fortunately, you can connect to it now. So the question is:
Can you connect to your server directly via SSH? if yes what is your download and upload speed to your server via SSH?

**Comment by trudyhood** [comment]
I am still a little confused. Do you manage your server with our access server located at the following address?
https://console.vpnhood.com/

**Comment by javad490** [comment]
hi, yes, i connect to my vps server root via ssh and run command on ssh consolbut i must connect to ssh port via vpn, becouse without vpn speed is low and repeatly disconected...also my vps compay  change ssh port from 22 to another 5 digit port
also i can login frorm your link to my server panel only with vpn on.please send linux code that i can temporary stop vpnhood proccess on linux server for test another proxy and vpn, now for temporary disable vpnhood from server, i must uninstall it.thanks

Sent from Yahoo Mail on Android 
 
  On Fri, Feb 17, 2023 at 4:32, ***@***.***> wrote:   


Dear Javad,
You look so active and I appreciate what you have done. However, let's focus on one subject per issue at a time, so we don't get confused with double problems. Feel free to create more issues if you have any.

Last time you said you couldn't connect to your server via VpnHood, but fortunately, you can connect to it now. So the question is:
Can you connect to your server directly via SSH? if yes what is your download and upload speed to your server via SSH?

**Comment by trudyhood** [comment]
Hello Javad, I regret to inform you that our servers are currently public and it appears that they may be blocked on your end. If you are able to resolve this issue, I would greatly appreciate it if you could share the outcome with me.

**Comment by javad490** [comment]
hi, becouse my vpnhood server client not can connect or connect but not can send &Recive data on iran that government apply hard filtering and limit internet, i temporary uninstall vpnhood from my server, after boost and improve Vpnhood in sensorship , please inform me to i reinstall and test it on iran.if your vpnhood connect and work well in iran, also it must work well in China...then your vpnhood is best vpn in the world and 1,500,000,000 + 100,000,000 of china and iran people use it and you can sell vpnhood pluse version, also you help freedom in iran and china...big thanks 

Sent from Yahoo Mail on Android 
 
  On Tue, Feb 21, 2023 at 3:10, ***@***.***> wrote:   


Hello Javad, I regret to inform you that our servers are currently public and it appears that they may be blocked on your end. If you are able to resolve this issue, I would greatly appreciate it if you could share the outcome with me.
