### ISSUE TITLE
How to increase TCP Buffer after setting up server

### ISSUE THREAD

**Issue by asoMansoury** [vpnhood/VpnHood#272]
is there any way to increase tcp buffer after setting up of vpnhood server?

**Comment by trudyhood** [comment]
Yes, Are you using our access server or standalone?

**Comment by asoMansoury** [comment]
hi
I have my own server on Ubuntu. I just want to increase TCP buffer size.
thanks in advance

**Comment by asoMansoury** [comment]
Hi again
I installed it by command line.
I checked appaetting.json, it is changed by server and contains
authentication and bearer token

**Comment by trudyhood** [comment]
I am still a little confused. Do you manage your server with our access server located at the following address?
https://console.vpnhood.com/

**Comment by asoMansoury** [comment]
> I am still a little confused. Do you manage your server with our access server located at the following address? https://console.vpnhood.com/

Yeah exactly, for managing servers I use this console.
I just said that for the initial configuration, I read the wiki site and implemented the server on ubuntu by the script you have uploaded. Initially, I saw that the initial TCP buffer size was 8192 in the appsetting.json file. Right now I want to increase it to 81920.

**Comment by trudyhood** [comment]
Ok, so you need to access server settings. Use this with the latest version:
```json
{
  "HttpAccessServer": {
    "BaseUrl": "https://access.vpnhood.com",
    "Authorization": "Bearer xxxxx"
  },
  "ServerConfig": {
    "Session": {
      "TcpBufferSize": 81920
    }
  }
}
```

It is for debugging. ServerConfig will override AccessServer settings. We are working on Access Server so you can set it via the Access Server panel soon.

👉 We have tried different buffer sizes. Please note that VpnHood may establish more than 30K concurrent TCP streams and can gobble up your RAM (if you have less than 8 GB ram). Please share with us if you find increasing the TCP buffer size advantageous.

**Comment by trudyhood** [comment]
I forgot to say that you need to install the pre-release version v2.7.352
https://github.com/vpnhood/VpnHood/releases/tag/v2.7.352-prerelease

**Comment by trudyhood** [comment]
Today released another pre-release version, so you have more control over TcpBuffer. Now you can explicitly set TcpClient kernel buffer size.
Check version: v2.7.353
https://github.com/vpnhood/VpnHood/releases/tag/v2.7.353-prerelease

TcpBufferSize, TcpKernelSendBufferSize,TcpKernelReceiveBufferSize
TcpBufferSize is VpnHood application buffer for CopyStream

**Comment by asoMansoury** [comment]
Thank you so so much.
I'm pretty sure about this great VPN server and it sooner will be the greatest app for setting up VPNs around the world.
I increased my buffer to 30720(4GB Ram) and I will let you know how it does work for my clients.
Do you have any documents for your code? I want to contribute and extended your great application, Just need some help to have a little bit of knowledge about your code.
Is there any book for reading about TCP?

Another question, for updating my old server to the newest version do i have to just copy the new server version files on the old version directory?

**Comment by trudyhood** [comment]
> I'm pretty sure about this great VPN server and it sooner will be the greatest app for setting up VPNs around the world.

Thank you so much. I hope we can do that.

>I increased my buffer to 30720(4GB Ram), and I will let you know how it does work for my clients. Is there any book for reading about TCP?

It is a very advanced topic. There are many articles about TCP optimization on the net, but I can't recommend any specific book.

> Do you have any documents for your code? I want to contribute and extended your great application, Just need some help to have a little bit of knowledge about your code.

It is an open-source project, and I create a bunch of documentation these days. We need help with iOS, Windows 10 UwpVpnPlugin, and UI, any bug report, advice or recommendation is welcome too.

**Comment by asoMansoury** [comment]
I increased buffer size of my own server to 16MB . after two days I can say
everything is much better than the previous which  buffer size was 8MB.
I have just 4GB RAM. I want to increase it to 32MB in the next time.

**Comment by trudyhood** [comment]
16MB? Perhaps you meant 64KB.
What about TcpKernelSendBufferSize,TcpKernelReceiveBufferSize? Did you change them?
 Can you share your config with us?
