### ISSUE TITLE
VpnHood Access Server problem 

### ISSUE THREAD

**Issue by armansoheili** [vpnhood/VpnHood#273]
Hi i add a server to VpnHood Access Server (not command line) and it says address already in use
What should i do?
It saty on Configuring
And i add another my own server and it says  No TcpEndPoint has been configured
And stay on Configuring
What should i do?

**Comment by armansoheili** [comment]
![Screenshot_20230217_132113](https://user-images.githubusercontent.com/113059160/219611414-6bd8c8b2-6455-4a0e-af85-5b5fd44a68f3.jpg)

**Comment by trudyhood** [comment]
Hi,
Please look at this page:
https://github.com/vpnhood/VpnHood/wiki/Address-Already-In-Use
