### ISSUE TITLE
Stay on Configuring

### ISSUE THREAD

**Issue by armansoheili** [vpnhood/VpnHood#277]
Hi
I add my server to console but it stay on Configuring for long time without any error
What should i do mate?
Thanks 
![Uploading Screenshot_20230218_014254.jpg…]()

**Comment by trudyhood** [comment]
Hi,
Please look at this page:
https://github.com/vpnhood/VpnHood/wiki/Address-Already-In-Use

**Comment by trudyhood** [comment]
let me know if the issue still exists.

**Comment by armansoheili** [comment]
Thanks for you help mate!
I think you are one guy
Just wanna say thanks for you works you help me a lot 🔥
