### ISSUE TITLE
NotInstalled problem 

### ISSUE THREAD

**Issue by armansoheili** [vpnhood/VpnHood#278]
Hi i add a server but it show NotInstalled on status for 10h even i add it again but it show it again

![Screenshot_20230218_115831](https://user-images.githubusercontent.com/113059160/219850868-c4a8cbba-0205-4045-bcf8-4e3f64942923.jpg)

**Comment by bobvhood** [comment]
Hi, We don't offer any servers. This panel helps you to install VpnHood on your own server. I think there might be confusion,  Unfortunately, if you don't have a server (VPS or dedicated) Access Server can't do anything for you.

**Comment by bobvhood** [comment]
Oh, sorry. So please press install and add your server credential. You can also install VpnHood on your server manually. I can do it for you too if you send us your server credential. support@vpnhood.com

**Comment by armansoheili** [comment]
Unfortunately i do that but still in status show NotInstalled! You need my
ip  address and pass for adding my server? I need to add it on site

**Comment by bobvhood** [comment]
Can you send us your server log to support@vpnhood.com
