### ISSUE TITLE
Add new features if possible

### ISSUE THREAD

**Issue by mahdaviyousefiamir378** [vpnhood/VpnHood#280]
**Greetings and courtesy

1.Allocation of volume (charging, for example 1 GB) for each user individually
2. Set the expiration date for each user individually When the expiration date is reached, the VPN will be disconnected and the VPN will start working again when the expiration date is set
3.Ability to activate or deactivate the user individually
4.Ability to delete user individually
5.In the management panel and in the Android and Windows software, the total and consumed volume (charging, for example, 1 gig) and the expiration date should be displayed.

Thanks & Regards
Amir Mahdavi Yousefi**

**Comment by bobvhood** [comment]
Hi, Are you using VpnHood Access Server or the built-in File Access Server?

**Comment by bobvhood** [comment]
These features should already exist, let me know if you can't find them. Try to edit their tokens

2. Set the expiration date for each user individually When the expiration date is reached, the VPN will be disconnected, and the VPN will start working again when the expiration date is set
3. Ability to activate or deactivate the user individually
4. Ability to delete users individually
