### ISSUE TITLE
Docker change port with configuration

### ISSUE THREAD

**Issue by parsagholipour** [vpnhood/VpnHood#281]
I changed the port in `/opt/VpnHoodServer/storage/appsettings.json`
content:
```
{
  "FileAccessServer": {
    "TcpEndPoints": [ "0.0.0.0:444", "[::]:444" ],
    "SslCertificatesPassword": null
  },
  "IsDiagnoseMode": false
}
```
but after generation using `docker run vpnhood/vpnhoodserver gen` I still get 443 port:
HostEndPoints: ip:443

I tried removing containers and installing didn't work.

**Comment by trudyhood** [comment]
Would you try this:
```sh
docker run -v "/opt/VpnHoodServer/storage:/app/storage" "vpnhood/vpnhoodserver" gen
```

**Comment by parsagholipour** [comment]
Thanks, it worked but I get this error:
[log.txt](https://github.com/vpnhood/VpnHood/files/10811141/log.txt)

**Comment by parsagholipour** [comment]
Thanks, it worked but I get this error:
[log.txt](https://github.com/vpnhood/VpnHood/files/10811167/log.txt)

**Comment by trudyhood** [comment]
I think VpnHoodServer is still not listening to 444. Try reinstalling VpnHoodServer with the installer to ensure the directory map in docker compose works.
Please send me the server.log

By default, VpnHoodServer uses a self-signed certificate, so if you type https://your-server-ip:444 you should see a certificate warning like this, meaning the server listens to the port.

So make sure you can see such a message:
![image](https://user-images.githubusercontent.com/72891124/220851071-1071c07e-b46a-4ec7-86f1-a4fba6dc074f.png)

**Comment by parsagholipour** [comment]
Sorry I forgot to open the port however I get this error now when I go with udp:
[log.txt](https://github.com/vpnhood/VpnHood/files/10825807/log.txt)
with tcp it's very slow and almost disconnected
![image](https://user-images.githubusercontent.com/57809920/221219224-6b3ffeae-0fcd-4084-8056-43580b5cbe24.png)
Currently ISPs here are blocking many types of vpn protocols.

**Comment by trudyhood** [comment]
I don't think they detect VpnHood because VpnHood completely works like a normal web server; no one, including ourself, can detect VpnHood signature or handshake because there is no signature to be found :)

However, you must ensure you have a reliable connection to your server. Try to find a way to check the download/upload speed from your location to your server. You can check that by installing a temporary web server on your server machine.

**Comment by parsagholipour** [comment]
You are right. Server ip was restricted! Thanks
