### ISSUE TITLE
error

### ISSUE THREAD

**Issue by AliHemmati79** [vpnhood/VpnHood#287]
Hello, my server config was fine last night and I shut down the server for several hours
Now, after hours, I turned on the server with an error 
(Error
Could not deserialize the response body stream as VpnHood.Server.Configurations.ServerConfig. Status: 200 Response: ) I encounter
I reinstalled but it didn't work
What should I do? please guide me.
![error](https://user-images.githubusercontent.com/99415271/222352999-2419a929-2c03-4a59-897d-057ecfdd0227.png)

**Comment by bobvhood** [comment]
Hi, it is so important for us. 
Can you send us your server log and appsettings.json to support@vpnhood.com

**Comment by AliHemmati79** [comment]
Sent via email

**Comment by bobvhood** [comment]
update to pre-release. we are working on it

sudo su -c "bash <( wget -qO- https://github.com/vpnhood/VpnHood/releases/download/v2.7.355-prerelease/VpnHoodServer-linux-x64.sh)"

**Comment by AliHemmati79** [comment]
The problem is solved, thank you very much
![2](https://user-images.githubusercontent.com/99415271/222372985-e18f1e8a-800a-4c22-8730-633f192a9236.png)

**Comment by bobvhood** [comment]
The speed depends on various factors, and very difficult to find the exact issue. This version must be faster; however, feel free to share your experience with us. We have also solved the compatibility issue too.
Thank you for reporting the issue to us.
