### ISSUE TITLE
AccessTokens Pagination and Listing

### ISSUE THREAD

**Issue by AliHemmati79** [vpnhood/VpnHood#288]
Hello, 
Thank you for your good service.
in the new update, the option to go to previous pages and view access tokens is no longer on the page! When will this feature be added again?

![1](https://user-images.githubusercontent.com/99415271/222725497-33974c06-1874-4ea1-acc9-2873c5c65273.png)

**Comment by AliHemmati79** [comment]
And how does the Locked IPs section work? Can you explain about it!

**Comment by bobvhood** [comment]
> Hello, Thank you for your good service. in the new update, the option to go to previous pages and view access tokens is no longer on the page! When will this feature be added again?
> 
> ![1](https://user-images.githubusercontent.com/99415271/222725497-33974c06-1874-4ea1-acc9-2873c5c65273.png)

Thank you for reporting. It has been fixed. Refresh the console to see the new version

**Comment by bobvhood** [comment]
> And how does the Locked IPs section work? Can you explain about it!

Just add an IP, and it won't connect to your server. Useful when you are using a public access key.

**Comment by AliHemmati79** [comment]
Hello, this section still has a bug and shows up to 100 access tokens!!!


![1](https://user-images.githubusercontent.com/99415271/222896508-86899720-d0ea-4cc4-9f4e-5e269c218534.png)

**Comment by bobvhood** [comment]
It shows maximum of 100 access tokens, the rest need to be fetched by search at the moment, Do you have more AccessTokens?

**Comment by AliHemmati79** [comment]
Yes, I have more access tokens and they were all visible in previous versions
For example, if I had 200 access tokens, I could see all of them in two pages of 100, but in the new version, 100 access tokens that were added recently can be seen.

**Comment by AliHemmati79** [comment]
When will the problem of limiting users' connection to access tokens be solved?
When I set max client to 1, other devices can connect at the same time, and this is not pleasant at all.

**Comment by bobvhood** [comment]
> Yes, I have more access tokens and they were all visible in previous versions For example, if I had 200 access tokens, I could see all of them in two pages of 100, but in the new version, 100 access tokens that were added recently can be seen.

OK, In order to gain a deeper understanding of your requirements, I was wondering if you could share with me how you typically use the platform. For example, if you have 2000 tokens, what would be your main objective in scanning through all of them manually? What are you looking for? We may add a filter or some kind of search to make it easier.

By gaining a better understanding of your specific needs and objectives, we can work towards improving our service and providing a more personalized experience for you

**Comment by bobvhood** [comment]
> When will the problem of limiting users' connection to access tokens be solved? When I set max client to 1, other devices can connect at the same time, and this is not pleasant at all.

We may change this strategy, but we think users should not share their token with others because as another one connects to VPN the other one will be dropped sooner or later.  If they have the recent version, they both see the message, while the older version just gets disconnected. However we may change this policy or make it optional.

**Comment by AliHemmati79** [comment]
To prevent users from abusing the token I had given to say 200 people and each one separately, by searching among them, those who had shared their token with others and connected to more than one device, to prevent I used to block their abuse.
It was very easy by searching the list of pages but now after updating to the new version I only have access to the last 100 tokens and if I want to access the others I have to search by name. I forgot their names and that's a problem, but in previous versions it was possible to go to the first page of generated tokens.
I hope I was able to convey my meaning to you

**Comment by AliHemmati79** [comment]
> 

When you see the message, it connects a little later, but when it connects, there is no problem and it can be used easily, and this is an important bug in my opinion.

**Comment by AliHemmati79** [comment]
And I have a suggestion that when the user is connected, the timer should be activated inside the program so that users will be informed of the duration of their connection to the vpn.

**Comment by bobvhood** [comment]
> To prevent users from abusing the token I had given to say 200 people and each one separately, by searching among them, those who had shared their token with others and connected to more than one device, to prevent I used to block their abuse. It was very easy by searching the list of pages but now after updating to the new version I only have access to the last 100 tokens and if I want to access the others I have to search by name. I forgot their names and that's a problem, but in previous versions it was possible to go to the first page of generated tokens. I hope I was able to convey my meaning to you

In this case, so we need to let you sort by device number in descent order so you won't need to look for them manually.

**Comment by bobvhood** [comment]
Thank you for your feedback. Definitely, we will affect your opinions.

**Comment by bobvhood** [comment]
What is the benefit of displaying connection time on the client, is it for debugging? We see it on many VPN apps but I am wondering what users can do with that.

**Comment by AliHemmati79** [comment]
> > To prevent users from abusing the token I had given to say 200 people and each one separately, by searching among them, those who had shared their token with others and connected to more than one device, to prevent I used to block their abuse. It was very easy by searching the list of pages but now after updating to the new version I only have access to the last 100 tokens and if I want to access the others I have to search by name. I forgot their names and that's a problem, but in previous versions it was possible to go to the first page of generated tokens. I hope I was able to convey my meaning to you
> 
> In this case, so we need to let you sort by device number in descent order so you won't need to look for them manually.

If, like the previous version, it is not limited to the last 100 tokens and the first access tokens can be seen, it will definitely be much better

**Comment by AliHemmati79** [comment]
> What is the benefit of displaying connection time on the client, is it for debugging? We see it on many VPN apps but I am wondering what users can do with that.

In my opinion, displaying the duration of the connection to the VPN helps users to understand how many hours they were connected to the VPN, and it is somehow a positive point for the program.

**Comment by AliHemmati79** [comment]
And another theory I have is that it would be much better if the names of devices attached to an access token were displayed and managed individually.
For example, in a family, 4 people are connected to an access token and the names of their devices are: phone1 - phone2 - phone3 - phone4 and we want to cut off the access of phone 2 and phone 4 with the on/off button. .
Or enable or disable per-user access checking instead of the on/off button.
I know that such a theory is very easy to say, but very hard to do, but if such a feature exists, it would be very interesting and great.
Thanks for your good service, good luck.

**Comment by bobvhood** [comment]
> And another theory I have is that it would be much better if the names of devices attached to an access token were displayed and managed individually. For example, in a family, 4 people are connected to an access token and the names of their devices are: phone1 - phone2 - phone3 - phone4 and we want to cut off the access of phone 2 and phone 4 with the on/off button. . Or enable or disable per-user access checking instead of the on/off button. I know that such a theory is very easy to say, but very hard to do, but if such a feature exists, it would be very interesting and great. Thanks for your good service, good luck.

It suggests that giving each user a unique token is a better approach than managing users solely by their device ID. This would allow users to use the same token on multiple devices, while also providing a way to monitor and manage user activity. Additionally, by not sharing their token with others, users can avoid being disconnected.
