### ISSUE TITLE
Server Farms

### ISSUE THREAD

**Issue by AliHemmati79** [vpnhood/VpnHood#289]
Hello, when will the ability to delete or edit be added to the server part of the forms?
So that we can remove unused server farms!

**Comment by bobvhood** [comment]
I hope soon :)

**Comment by AliHemmati79** [comment]
Thank you for your efforts and good luck

**Comment by bobvhood** [comment]
It is done. 

1. Refresh the console
2. Go to Server Farms
3. Select the Farm
4. Press Delete on top of the Server Farm card 

Good luck

**Comment by AliHemmati79** [comment]
When deleting the farm server, it shows this error

![1](https://user-images.githubusercontent.com/99415271/223705928-91238c23-c7ae-4a4f-b351-1352b45348fe.png)

**Comment by bobvhood** [comment]
Please recheck it; I hope it gets solved in your case. You need to refresh the console if it doesn't happen automatically.

**Comment by AliHemmati79** [comment]
I was able to remove the redundant farm server successfully
Thank you
