### ISSUE TITLE
After Disconnect, google.com stops working

### ISSUE THREAD

**Issue by Werewolfke** [vpnhood/VpnHood#295]
I have the issue when i browse the internet, everything works fine, before even also.
But as soon as i disconnect, google does not work anymore.
What does work is for example using google.be or .fr , yet using the main .com stops working, maybe because i used .com while on the vpn? also if i enable the vpn again, google.com works again.
It cant find the domain. after a browser restart it is fixed most of the time, or a computer restart, but even that are not garanteed fixes.
I work with chrome, both standard and canary have this.
This is so for the last versions of VPNHood. i only noticed this the last few months.
It could be that it was also an issue before, i am not using the vpn long enough to know.

I havent seen any other websites have this issue, they just keep working.

I don't use other vpn services exept for browser extention version of touchVPN, but only sometimes.
There the issue doesn't happen.

I don't know if im the only one with this issue.
And i don't know if this issue is something specific to VPNHood or google or not.

basic steps like DNS flushing and such don't resolve the issue either.
So is there a known fix for this? or troubleshooting steps?
any help is welcome

**Comment by trudyhood** [comment]
Hi, 
VPNHood does not make any permanent changes to the system. If you experience issues after disconnecting or exiting the VPNHood client, it is likely that you are facing a double proxy issue. There may be another proxy running, particularly in the background of Chrome, which causes the proxy to lose its connection and enter a reconnecting state when VPNHood is disconnected. This can prevent Chrome from working properly. To resolve this, ensure that you disable any other proxies in your Chrome extension or make sure that they are disconnected.
