### ISSUE TITLE
You can not have more than 4 Servers

### ISSUE THREAD

**Issue by asoMansoury** [vpnhood/VpnHood#296]
Hello I need to add another server on my VpnHood Panel, but after adding on the server, I got the below error.

{
  "Data": {
    "QuotaName": "Servers",
    "QuotaValue": "4"
  },
  "TypeName": "QuotaException",
  "TypeFullName": "VpnHood.AccessServer.Exceptions.QuotaException",
  "Message": "You can not have more than 4 Servers"
}

**Comment by bobvhood** [comment]
It is not an issue. However, we will set it to 10 soon.
