### ISSUE TITLE
Showing Checking Proxy on windows client

### ISSUE THREAD

**Issue by asoMansoury** [vpnhood/VpnHood#300]
After installing the last version on windows client I faced with below error
![image](https://user-images.githubusercontent.com/14541559/226087336-b85dc6bc-4d13-4860-b5a5-f423fa918dad.png)

**Comment by trudyhood** [comment]
Welcome back. Unfortunately, I couldn't simulate the issue in my sandbox. 

1. Would you restart your windows?
2. What happens if you select Open In Browser?
![image](https://user-images.githubusercontent.com/72891124/226091117-3ebb79bf-0032-4a15-9b0e-eca052480355.png)

**Comment by asoMansoury** [comment]
I Clicked on Open in Browser.
![image](https://user-images.githubusercontent.com/14541559/226184031-2cce7790-2d76-4d36-8d6d-8c125cbb80a8.png)

**Comment by trudyhood** [comment]
Are you sure the VpnHood client is running? Can you send me the following file to trudy@vpnhood.com
"C:\Windows\System32\drivers\etc\hosts"

also, let me know what do you see when clicking on VpnHood Icon. is it a blue screen.

**Comment by trudyhood** [comment]
Hi everyone. We have fixed it. Please check version 411.
Good luck
