### ISSUE TITLE
Wrong APK at release v2.8.361?

### ISSUE THREAD

**Issue by IzzySoft** [vpnhood/VpnHood#301]
The APK at release [v2.8.361](https://github.com/vpnhood/VpnHood/releases/tag/v2.8.361) identifies as

    package: name='com.vpnhood.client.android' versionCode='360' versionName='2.8.360'

Did something go wrong there? It's not identical to the one at the tag it suggests, so maybe you just forgot to adjust the version?

**Comment by trudyhood** [comment]
We haven't updated the version of the APK because there is no change in that. Only the server has upgraded to this version, which is common in our publishing policy.

**Comment by IzzySoft** [comment]
Problem is, as it's attached to a tag indicating a higher version, my updater now will fetch it each day just to throw it away again as it is identical to the one already in the repo:

```
com.vpnhood.client.android: looking for 'https://api.github.com/repos/vpnhood/VpnHood/releases'
com.vpnhood.client.android: checking tag 'v2.8.361'
com.vpnhood.client.android: lastRelNo set to '2.8.361', checking for files
Upstream file date (2023-03-19 07:17) is newer than ours (2023-03-12 01:00).
com.vpnhood.client.android: returning ['2.8.361','https://github.com/vpnhood/VpnHood/releases/download/v2.8.361/VpnHoodClient-android.apk']
com.vpnhood.client.android: 2.8.360/2.8.361, https://github.com/vpnhood/VpnHood/releases: https://github.com/vpnhood/VpnHood/releases/download/v2.8.361/VpnHoodClient-android.apk
- Grabbing update for com.vpnhood.client.android: OK
repo/com.vpnhood.client.android_360.apk already exists and is identical to the one we downloaded; ignoring it
```

Quite wasting resources. So do I disable updates on my end – or would it be an option to simply remove the APK from the tag it doesn't match? OK, touched the file to match the timestamp of the newer tag :man_shrugging: The version mismatch at the tag is still confusing; hope there won't be user requests to when I will update as there's a newer tag here (wouldn't be the first time)…

Thanks for clarification!

**Comment by trudyhood** [comment]
You can simply do not update it when the apk version is identical otherwise we need to create a repo per each sub module such as server, windows, android, client...
Another approach is to increase the version in every push but it sends a false update to users.

**Comment by trudyhood** [comment]
We also publish this JSON file along with each module which indicates the version separately. However, I am unsure how flexible your crawler is to parse it.
https://github.com/vpnhood/VpnHood/releases/latest/download/VpnHoodClient-android.json

**Comment by IzzySoft** [comment]
Thanks @trudyhood – for now I worked around it by touching the timestamp of the file. It's just unusual to publish something as "new" if it is not new – and sorry, I cannot make special rules for each project (we're talking about more than 1k apps in my repo), so JSON parsing is not an option here.

I might see to it to change the processing here in a way that, if the APK is identical, it will be replaced nevertheless so the timestamp is adjusted then and the file not downloaded over and again. That'd mitigate the problem, as it pops up once a month or so.
