### ISSUE TITLE
Sites not loading after connecting

### ISSUE THREAD

**Issue by AliHemmati79** [vpnhood/VpnHood#303]
Hello, in the Windows version, after connecting, no site is loaded, such as YouTube, Instagram, Twitch, etc.
What could be the problem?
But the program is connected and green.

![1](https://user-images.githubusercontent.com/99415271/226306200-5d63bcad-8a42-4cc1-8d8d-57c866d02f56.png)

**Comment by trudyhood** [comment]
What is the error message? Can you send me the browser screenshot?

**Comment by AmirHosseinCV** [comment]
I encountered a similar issue, but resolved it by ensuring that the server and client were both running the same version of VpnHood.
