### ISSUE TITLE
a reconnection loop every 1 minute in a specific situation

### ISSUE THREAD

**Issue by SSgumS** [vpnhood/VpnHood#312]
Hello

Sorry for the disturbance. In the previous log file I provided, there was another issue which I think should be separated from the previous discussion.

In the game "[The Grand Mafia](https://play.google.com/store/apps/details?id=com.yottagames.gameofmafia)" when I play it using VPNHood, I can see a reconnection loop every 1 minute (roughly). In the log file the reconnecting loop can be seen (Client is Connecting has appeared multiple times). I have no idea why this happens, but it only occurs when the game "The Grand Mafia" is opened. The game doesn't have any problems with other protocols such as the ones used in V2Ray.

[log.txt](https://github.com/vpnhood/VpnHood/files/11152236/log.txt)

**Comment by trudyhood** [comment]
The "Client is Connecting" means a TCP connection to the server has failed (while many others perhaps are still working), but it doesn't mean that you actually disconnected from the server. It just notified you that your connection to your server is not good as expected. This step has no special protocol and handshake; it is a simple HTTPS handshake. So you need to ensure that your connection to your server is reliable and your server is not too busy. It is ok As far as you can play the games. 
Make sure you use the default configuration on your server.
Does it interrupt the game despite the Connecting state?

**Comment by SSgumS** [comment]
It interrupts the game every minute. When the game interrupts, VPNHood shows the "Connecting" state on the notification bar instead of "Connected". Whatever "Client is Connecting" means in the log, it seems to match the times when I see "Connecting" on the notification bar. Just before it happens, we can see some TcpProxyChannel removals and tunnel copying errors (I don't know if they are related or not).

I have tested the situation on multiple servers. As the problem only occurs when I play the game (there is no problem in other situations with the same server using VPNHood) and other VPN protocols on the same server don't have any problem in the game, it seems the problem has something to do with VPNHood itself. I didn't configure the servers specifically and they use default settings. If you would like me to follow a specific configuration during the test, I will be glad to do so.

**Comment by trudyhood** [comment]
We have to check with that game. Feel free to share your idea meanwhile.

**Comment by SSgumS** [comment]
Hello
Has the problem been solved now?

**Comment by trudyhood** [comment]
would you test by the latest version and let us know?
