### ISSUE TITLE
Manage each user

### ISSUE THREAD

**Issue by francescovigot** [vpnhood/VpnHood#313]
hi
1. How to manage each user for creating a premium account and limit their network traffic? (For example, 5 gigabytes of traffic per month for each user)

2. is VPNhood Windows compatible with .net MAUI?

I appreciate your excellent plugin. Please Keep going.

**Comment by trudyhood** [comment]
Hi.

1. In the Access Server, you can set the maximum traffic for a token
2. It should be, but we haven't worked on MAUI.  

feel free to add comments on this closed issue.

**Comment by francescovigot** [comment]
No, I didn't mean setting maximum traffic for a token, I mean for each user. For example, in OpenVPN, you connect it IBSNG service to manage each user

**Comment by trudyhood** [comment]
At this moment, you need to give a separate private token to each user so you can manage it.

**Comment by francescovigot** [comment]
so at this moment, we can do this manually not automatically, right?

**Comment by trudyhood** [comment]
I am not sure what you mean by manually. An AccessToken is a user account. How can you automatically charge your users. What is your business plan?
