### ISSUE TITLE
IP has not changed

### ISSUE THREAD

**Issue by oOoREVOLVERoOo** [vpnhood/VpnHood#314]
In the first screenshot of VpnHood! changed IP. But the second one doesn't. Why doesn't the IP change on gosuslugi.ru?
![01](https://user-images.githubusercontent.com/130054619/230358193-8ecf1988-dc67-433f-9135-1a03521897fa.jpg)
![02](https://user-images.githubusercontent.com/130054619/230358223-c340d22b-4d21-4676-89de-f36ac6737679.jpg)

**Comment by trudyhood** [comment]
Hi, 
Are you sure you haven't selected "exclude my country" in the client?
Can you send me the diagnostic log?

**Comment by oOoREVOLVERoOo** [comment]
My bad. It`s "exclude my country". But now VpnHood! stopped visiting gosuslugi.ru altogether(
![03](https://user-images.githubusercontent.com/130054619/230376148-6991fdd5-d2de-4037-985f-3cdfb1e7b4d6.jpg)

**Comment by trudyhood** [comment]
It looks gosuslugi.ru is not available from our public server IP.  It does not relate to VpnHood protocol or app. You need to install a VpnHood server in a location where its IP does not filter by gosuslugi.ru.

**Comment by oOoREVOLVERoOo** [comment]
Do you mean this?
![2023-04-07_06-35-41](https://user-images.githubusercontent.com/130054619/230536381-95823f28-66c7-4af4-877a-f0ce3d022038.jpg)

**Comment by trudyhood** [comment]
It is not that easy. You need to buy a server and install VpnHoodServer on it. Then create an access token and add it here.

**Comment by oOoREVOLVERoOo** [comment]
OK, i got it. Thank you veru much
