### ISSUE TITLE
Log In error

### ISSUE THREAD

**Issue by roozbehsat** [vpnhood/VpnHood#315]
Hi, 
I have problem when I want to login access server, after I log to my google account, ui said this message: 

There was an error trying to log you in: ''

I check several system and browser, did u know why?
![Screenshot (168)](https://user-images.githubusercontent.com/119633123/232102382-b65a6fe6-df4c-4578-906a-1c148b107a1c.png)

**Comment by trudyhood** [comment]
check your system time zone and make sure the clock is correct
