### ISSUE TITLE
cdn cloudflare

### ISSUE THREAD

**Issue by yremac** [vpnhood/VpnHood#316]
Is it possible to set the domain to cloudflare CDN . To use their ip through a proxy .cloudflare., traffic masking is not enough for the country of Turkmenistan, here they block the ip by mask ,on vds who are seen behind the vpn server

**Comment by trudyhood** [comment]
At present, CDN is not supported by VpnHood. 
VpnHood functions as a socks proxy, and if you maintain the privacy of your server's IP address, They will not be able to detect it unless they find the IP. Furthermore, even if you use Cloudflare, it is essential to keep your domain name confidential and you just have a domain name instead of an IP.

**Comment by yremac** [comment]
I understand, it's very difficult to just find a server with an unblocked IP right now

**Comment by trudyhood** [comment]
While I hope that we can integrate CDN support, it's worth noting that according to the "Terms of Use" for CloudFlare CDN service, only an actual web server is allowed. This means that adding anything other than a web server may violate the terms of the service.

**Comment by yremac** [comment]
thanks for the info

**Comment by trudyhood** [comment]
I worked on supporting the cloud for a few weeks work. Still, unfortunately, I found out it was impossible to support Cloudflare via its free plan through HTTP 1.1, as its caching mechanism and strict rule for processing requests prevent tunneling. There may be paid plans in Cloudflare already supporting tunneling scenarios. Also, it may be possible to do that via HTTP 2 or HTTP3. However, we don't have a plan to work on them at this stage.

**Comment by yremac** [comment]
understood, thank you for the clarification

**Comment by trudyhood** [comment]
We have worked on supporting CDNs like Cloudflare, it is possible to support it, but unfortunately, it gobbles up 70% of upload performance. download could be much better so we have stopped thinking about it.

**Comment by asoMansoury** [comment]
I used 'https://raw.githubusercontent.com/opiran-club/pf-tun/main/pf-tun.sh' script and activated ipv6to4. then I gained two private ipv6 on both server. when I ping my foreign Private ipv6 on my iran server I get response  and vice versa. then I re-route traffic from iran to vpnhood by socat(tunneling ip4 to private ipv6 vpnhood), now I'm getting below error.

Received an unexpected EOF or 0 bytes from the transport stream.

**Comment by asoMansoury** [comment]
> Dear @asoMansoury Thank you for sharing the details of your setup. We appreciate the effort you've put into configuring the IPv6 tunneling. However, we understand that this method might be quite complex and fall outside the scope of our standard support.
> 
> To ensure a smoother experience, we recommend using the default configurations provided in our official documentation. If you encounter any issues or need specific features, please let us know, and we will do our best to assist you.
> 
> For the error "Received an unexpected EOF or 0 bytes from the transport stream," it typically indicates a problem with the connection or data transmission. This might require a more in-depth look.

These are my last attempts to find a way connect vpnhood from Iran, I think we aren't able to use your great vpnhood anymore.

**Comment by trudyhood** [comment]
@asoMansoury, I am sorry that VpnHood couldn't solve your problem and so sad that you left us. We did our best, but your configuration is quite complex and very difficult to reproduce. VpnHood is open-source and free for all. If you find any resolution for that, we are happy to merge your code. Thank you for trying VpnHood.

**Comment by trudyhood** [comment]
We have added support for reverse proxies such as CloudFlare to VpnHood version 725
