### ISSUE TITLE
windows forms issue

### ISSUE THREAD

**Issue by francescovigot** [vpnhood/VpnHood#317]
Hi
When I use this sample code inside the windows forms project, some websites don't open
`static void Main()
{
	Console.WriteLine("Hello VpnClient!");

	// clientId should be generated for each client
	var clientId = Guid.Parse("7BD6C156-EEA3-43D5-90AF-B118FE47ED0A");

	// accessKey must obtain from the server
	var accessKey = "Your access code";
	var token = Token.FromAccessKey(accessKey);

	var packetCapture = new WinDivertPacketCapture();
	var vpnHoodClient = new VpnHoodClient(packetCapture, clientId, token, new ClientOptions() {});

	vpnHoodClient.Connect().Wait();

	Console.WriteLine("VpnHood Client Is Running!");
	Console.WriteLine("Open your browser and browse the Internet! Press Ctrl+C to stop.");
	while (vpnHoodClient.State == ClientState.Disposed)
		Thread.Sleep(1000);
}`

 But everything works fine when I use the VPNHood source code (the VpnHood.Client.App.Win). What extra code that we have in this  VpnHood.Client.App.Win source code should I put inside my project?

**Comment by francescovigot** [comment]
Yes, It works fine with the "VpnHood.Client.App.Win," but it doesn't work correctly with the "VpnHood.Client.App.Simple" project. It seems there are some extra codes inside the "VpnHood.Client.App.Win" that aren't in the "VpnHood.Client.App.Simple" when I use "VpnHood.Client.App.Simple" as if VPN doesn't connect properly.
When I try with "VpnHood.Client.App.Simple" I have a connected internet (ping 4.2.2.4 -t )
but no websites open in the browser.

**Comment by trudyhood** [comment]
VpnHood official clients use the same Library. Make sure it uses the latest library. Also, you may have maybe some other configuration like "exclude your country" or "Use UDP".  The sample just shows how the library work.

**Comment by francescovigot** [comment]
What type of c# project have you used for the sample project? If I want to create a c# project, which should I use?

**Comment by trudyhood** [comment]
It is C#
https://github.com/vpnhood/VpnHood/tree/main/Samples

**Comment by francescovigot** [comment]
When I create a project with .net core 6 (without UI), VPN runs correctly, but when I create a project with windows forms and the target is .net 6, I have an internet connection, but all browsers don't open any websites.
Can you guess why this happens?

**Comment by trudyhood** [comment]
I am not sure. Make sure to use Task.Run(()=>vpnHoodClient.Connect());
it is not recommended to use .Result or Wait in Form applications
