### ISSUE TITLE
Add multilingual support

### ISSUE THREAD

**Issue by ghost** [vpnhood/VpnHood#318]
import Vue from 'vue'
import VueI18n from 'vue-i18n'
import langEn from 'vuetify/es5/locale/zh-cn'
Vue.use(VueI18n);

const messages = {
 zh-cn: {
        $vuetify: langEn,
        isRtl: "false",
        appName: "VpnHood!",
        settings: "设置",
        add: "添加",
        help: "帮助",
        home: '主页',
        version: "版本",
        connect: "连接",
        connecting: "正在连接...",
        connected: "已连接",
        disconnect: "断开",
        disconnected: "断开连接",
        disconnecting: "正在断开...",
        diagnosing: "正在诊断...",
        waiting: "正在等待...",
        addServer: "添加服务器",
        diagnose: "诊断",
        darkMode: "深色模式",
        clientProfile: "VPN配置文件",
        clientProfileName: "名称",
        remove: "删除",
        rename: "更改名称",
        warning: "警告",
        cancel: "取消",
        close: "关闭",
        save: "保存",
        ok: "完成",
        noname: "服务器",
        uploadSpeed: "上行",
        downloadSpeed: "下行",
        noServerSelected: "无服务器",
        selectedServer: "服务器",
        manageServers: "更改服务器",
        change: "改变",
        feedback: "发送反馈",
        openReport: "打开报告",
        sendReport: "发送报告",
        general: "一般",
        confirmRemoveServer:"您真的要删除此服务器吗？<br/><br/>{服务器名称}",
        addTestServer: "添加公共服务器",
        addTestServerSubtitle: "您已删除公共测试服务器。该服务器是免费的用于评估。",
        addAcessKeyTitle: "添加私有访问密钥",
        addAcessKeySubtitle: "复制并粘贴访问密钥以添加服务器。",
        invalidAccessKeyFormat: "访问密钥的格式无效。确保它以{prefix}开头",
        servers: "服务器",
        selectServerTitle: "选择或添加服务器",
        publicServerWarningTitle: "公共服务器提示",
        publicServerWarning: "它是为评估而创建的与公共服务器的连接 ，有时可能会很慢或无法访问。<br/><br/> 要获得可靠且快速的连接，您需要连接到私人服务器。",
        dontShowMessage: "不再显示此消息。",
        appFilter: "允许的应用程序",
        appFilterDesc: "哪些应用程序可以使用VPN？",
        appFilterStatus_title: "应用程序",
        appFilterStatus_all: "所有应用程序",
        appFilterStatus_exclude: "除以{x}个应用程序外的所有应用程序",
        appFilterStatus_include: "只有{x}个应用程序",
        appFilterAll: "所有应用程序",
        appFilterInclude: "仅选定的应用程序",
        appFilterExclude: "除所选应用程序外的所有应用程序",
        ipFilter: "允许的国家",
        ipFilterDesc: "哪些国家可以使用VPN？",
        ipFilterStatus_title: "国家",
        ipFilterStatus_all: "所有国家",
        ipFilterStatus_exclude: "除以{x}个国家外的所有国家”",
        ipFilterStatus_include: "只有{x}个国家",
        ipFilterAll: "所有国家",
        ipFilterInclude: "仅选定的国家",
        ipFilterExclude: "除所选国家外的所有国家",
        ipFilterStatus_excludeClientCountry: "排除我的国家",
        protocol: "协议",
        protocol_title: "协议",
        protocol_desc: "UDP对于大量使用它的应用程序要快得多,例如种子。但它可能不适用于某些防火墙和代理。如果禁用UDP,所有应用程序仍然有效,但他们可能会慢得多。",
        protocol_udpOn: "使用UDP（更快）",
        protocol_udpOff: "没有UDP（较慢）",
        selectedApps: "精选应用",
        selectedIpGroups: "选定的国家",
        newServerAdded: "添加了新服务器。",
        changelog: "有新消息？",
        excludeLocalNetwork: "排除本地网络 (LAN)",
        excludeLocalNetworkDesc: "不要将我的本地网络数据包发送到VPN服务器。我需要访问本地网络上的其他计算机和设备。",
        readPrivacyPolicy: "阅读隐私政策",
        privacyWarning: "这些服务器将IP活动日志保留30天 。要使用这些服务器您必须遵守美国法律特别是在使用种子。",
        createServer: "创建个人服务器",
        accept: "接受",
        tunnel_mycountry: "加密我的国家",
        tunnel_mycountry_desc: "您想通过加密传输托管在您所在国家/地区的流量吗？",
        tunnel_mycountry_on: "是的，加密所有流量，包括我的国家（较慢）。",
        tunnel_mycountry_off: "不，不要从我所在国家/地区的服务器加密传输流量（更快）。",
        sessionSuppressedToOther: "您断开了另一台设备的连接，因为您在多台设备上使用了相同的访问密钥！",
        sessionSuppressedByOther: "您已断开连接，因为另一台设备使用您的访问密钥连接！",
        versionIsDeprecated: "您的VpnHood应用程序已被弃用迟早会停止工作！ 考虑尽快升级。",
        versionIsOld: "有一个新版本可供安装。",
        install: "安装",
        ignore: "忽略",
        update: "更新",
        currentVersion: "你的版本:",
        newVersion: "新的版本:"
    },
};

// Create VueI18n instance with options
export const i18n = new VueI18n({
    locale: 'zh-cn', // set locale
    fallbackLocale: 'zh-cn',
    messages, // set locale messages
});

export default i18n;

**Comment by 99ii** [comment]
How do I compile an app that supports Chinese

**Comment by trudyhood** [comment]
I can include it so it will be available in the next version.  
Have you translated it yourself or using a translator?
Can you fork the UI project and create a merge request?

**Comment by 99ii** [comment]
I modified it through Google Translate

**Comment by 99ii** [comment]
I want to compile an application how do I do it

**Comment by 99ii** [comment]
i need to test it

**Comment by trudyhood** [comment]
> I want to compile an application how do I do it

The UI project is a separate project:
You need to compile this vue app:
https://github.com/vpnhood/VpnHood.Client.WebUI

then zip the output, copy it to VpnHood resources, and compile VpnHood
https://github.com/vpnhood/VpnHood

If you want to test it, you can ignore compiling the VpnHood app and just see the result in the browser. Just keep VpnHood app running in Windows, then run the Vue project so that you can see the result in the browser.

So you need at least to know how to compile the Vue project. I can help you after you successfully run the Vue project.

**Comment by 99ii** [comment]
compiling this vue app has this error

> vpnhood-spa@1.0.166 build
> versiony --patch && vue-cli-service build

sh: 1: versiony: not found

how to deal with

**Comment by trudyhood** [comment]
I did some changes and changed the locales file structure to make it easier to add a language. Also added what you sent me:
![image](https://user-images.githubusercontent.com/72891124/233959231-2aa98b8b-adef-4bc9-94a5-26f7a33fa6e7.png)
![image](https://user-images.githubusercontent.com/72891124/233959365-57e97594-32e2-48ee-bf55-b87f92513ecf.png)
![image](https://user-images.githubusercontent.com/72891124/233959927-a908a788-e3f6-43dc-8033-ce2154c54a5d.png)

Please merge the latest commit, as we can't understand this language, and you need to check it yourself.

**Comment by trudyhood** [comment]
> compiling this vue app has this error
> 
> > vpnhood-spa@1.0.166 build
> > versiony --patch && vue-cli-service build
> 
> sh: 1: versiony: not found
> 
> how to deal with

You can remove "versiony --patch &&" . it is for automatically increasing the UI version.

**Comment by 99ii** [comment]
VpnHood Public Servers
Here is not changed into Chinese
VpnHood 公共服务器

**Comment by 99ii** [comment]
can compile an android app for me
I will test

**Comment by trudyhood** [comment]
> VpnHood Public Servers Here is not changed into Chinese VpnHood 公共服务器

It is the name of the server and comes from the accesskey, it does not exist in-app, and if the user adds another server, they will see other servers name.

**Comment by 99ii** [comment]
Are you running it in a browser?

**Comment by trudyhood** [comment]
> VpnHood Public Servers Here is not changed into Chinese VpnHood 公共服务器

It will be much back and forth. We will not publish it officially unless you can run the Vue project it yourself. You don't need to compile the Android and VpnHood client to see the result, just run the official version VpnHood and run the Vue project and check the result:
![image](https://user-images.githubusercontent.com/72891124/233964956-d948161c-51b8-4e30-8f9f-d9af924f1b80.png)

**Comment by trudyhood** [comment]
> Are you running it in a browser?

Yes, the VpnHood core is running on windows, but we develop the UI in the browser, so we don't need to pack it every time to check the result.

**Comment by 99ii** [comment]
I get this error when I open it with a browser

TypeError: Failed to fetch
Please run the app and try again.

**Comment by trudyhood** [comment]
> I get this error when I open it with a browser
> 
> TypeError: Failed to fetch Please run the app and try again.

Are you running the VpnHood Client?

**Comment by 99ii** [comment]
Vue project

**Comment by 99ii** [comment]
I use linux system and chrome

**Comment by trudyhood** [comment]
> Vue project

Oh, You need to run the VpnHood client on your development system to connect to its local webserver. unfortunately, we don't have Linux client so you can't develop it like that on Linux.

![image](https://user-images.githubusercontent.com/72891124/233967328-1dd69544-34fd-4693-933b-0e8fb65429e9.png)

**Comment by trudyhood** [comment]
We have supported multilingual environments, including Chinese; please help us fix the translation if you see any issues. 
Check the latest version: 485
