### ISSUE TITLE
can not start via systemd

### ISSUE THREAD

**Issue by malikshi** [vpnhood/VpnHood#32]
Failed to restart VpnHoodServer.service: Unit VpnHoodServer.service is not loaded properly: Exec format error.
ubuntu 18.04

**Comment by trudyhood** [comment]
Hi,
Have you installed .NET runtime?
Can you send us VpnHood server log?
Can you run it without systemd?

**Comment by malikshi** [comment]
solved by changes `sh` with right path `/bin/sh`
add this one too
>LimitNOFILE=512000
LimitNPROC=infinity

**Comment by malikshi** [comment]
can you add a logging level? isn't too much log written at Syslog? and support ipv6 would be better.
thank you for your hard work. i found this repo accidentally at sagertnet issues [sagernet](https://github.com/SagerNet/SagerNet/issues/213)

**Comment by trudyhood** [comment]
**can you add a logging level?**
There is high customization in log level through NLog. Open **nlog.config** in app folder.
You can change loglevel in NLog.config. Set minlevel to **Warn** in the following section
```
<rules>
    <logger name="*" minlevel="Info" writeTo="logfile,logconsole" >
</rules>
```
Also make sure  **IsDiagnoseMode** is **false** in **appsettings.json**. it puts heavy load on your server when turned on.

**support ipv6**
It is much for that to be done. I hope in future.

by the way, I am wondering why do you need to set LimitNOFILE=512000, LimitNPROC=infinity

**Comment by malikshi** [comment]
> **can you add a logging level?**
> There is high customization in log level through NLog. Open **nlog.config** in app folder.
> You can change loglevel in NLog.config. Set minlevel to **Warn** in the following section
> 
> ```
> <rules>
>     <logger name="*" minlevel="Info" writeTo="logfile,logconsole" >
> </rules>
> ```
> 
> Also make sure **IsDiagnoseMode** is **false** in **appsettings.json**. it puts heavy load on your server when turned on.
> 
> **support ipv6**
> It is much for that to be done. I hope in future.
> 
> by the way, I am wondering why do you need to set LimitNOFILE=512000, LimitNPROC=infinity

Just my personal setting you may heard about v2ray/xray usually I'm set hig number for limitnofile so app not hang/stuck

**Comment by malikshi** [comment]
@trudyhood 
thank you very much. it's much better now than before
![image](https://user-images.githubusercontent.com/9080737/128647048-dddd2390-3800-41ff-8ff6-17284a0bd9c5.png)
