### ISSUE TITLE
Some clients have connected but it does not work .

### ISSUE THREAD

**Issue by asoMansoury** [vpnhood/VpnHood#320]
hi.
Some clients which has installed VPN client on windows, and it has connected to Ubuntu VPN server.
but when they are trying to connect banned sites and telegram , it does not work.
I checked the Youtube site by CMD and I got ping and worked properly, but YouTube didn't open on browsers. it was like of YouTube for Telegram.

**Comment by trudyhood** [comment]
Can you provide the client diagnostic log?

**Comment by asoMansoury** [comment]
> 

Hello.
where the diagnostic log file being saved to get from clients?
I have access to their PC by anydesk program.

**Comment by trudyhood** [comment]
use this feature, then try to simulate the issue. it will give you the report:
![image](https://user-images.githubusercontent.com/72891124/236538186-0b6fb0d6-ddcb-4466-a892-edc892ead9ff.png)
