### ISSUE TITLE
preventing user disconnecting

### ISSUE THREAD

**Issue by francescovigot** [vpnhood/VpnHood#324]
Hello
When you have 1000 users per day and 80 concurrent users, should I generate 80 tokens for 80 concurrent users? If yes, How can the server do this process automatically?

**Comment by trudyhood** [comment]
Could you please describe your business scenario in more detail? If you intend to distribute a token to a large audience, it may be more appropriate to use a public token. Alternatively, you can create a private token and allow access for a limited number of devices. However, we don't recommend using a large number of devices with a single private token.

**Comment by francescovigot** [comment]
I have a published free VPN app for public use. How to create a public token?

**Comment by trudyhood** [comment]
Do you use Access Server to manage tokens or the file access server (embedded one)? How do you create access tokens?

**Comment by mohammadrezahamedi** [comment]
I install the vpnhood server in the Ubuntu 20 Lts server then I generate several tokens.

**Comment by trudyhood** [comment]
Do you generate tokens by command line?

**Comment by francescovigot** [comment]
Yes, is there another way?

**Comment by trudyhood** [comment]
You can manage your servers and token here by HTTP access server, but you have to create the tokens there from the first step:
https://console.vpnhood.com/

Also, the embedded file access server does not support the public token. You can use the -maxClient option and set it to zero so your client will not disconnect by max client limitation and you can share a single token with all users. 

I recommend you use the VpnHood enterprise Access Server:
https://github.com/vpnhood/VpnHood/wiki/VpnHood-Access-Server
