### ISSUE TITLE
How to use vpnhood on my vps windows server 2016

### ISSUE THREAD

**Issue by Ali-YousefiTelori** [vpnhood/VpnHood#334]
I used ./vhserver.ps1 gen but it shows me fake addresses, what is this and how can I change it to my actual server IP address?
and 116.202.209.102 is not my server IP address.
my client on Android could not connect with my generated access key and showed me a connection refused error.

PS C:\Program Files\VpnHood\VpnHoodServer> ./vhserver.ps1 gen;
[01:28:58.1900] info: [0]
      Using FileAccessServer. AccessFolder: C:\Program Files\VpnHood\VpnHoodServer\storage\access
The following token has been generated:

Access Details:
{
  "Traffic": {
    "Sent": 0,
    "Received": 0
  },
  "MaxTraffic": 0,
  "ExpirationTime": null,
  "MaxClientCount": 2,
  "ActiveClientCount": 0
}

SupportId: 0
HostEndPoints: 116.202.209.102:443
HostName: fe.kasorutysha.com (Fake)
HostPort: 443
TokenUpdateUrl:

**Comment by bobvhood** [comment]
The domain is fake and does not need be valid. however, you can change the domain by creating and replacing your own certificate file here:
```
/opt/VpnhoodServer/storage/access/certificates/default.pfx
```

You can also change the IP in the access tokens. 
```
./vhserver.ps1 gen -?
```

You can also use the VpnHoodAccess Server which is much more powerful and has a control panel and API:
https://github.com/vpnhood/VpnHood/wiki/VpnHood-Access-Server
