### ISSUE TITLE
Issue in Windows output

### ISSUE THREAD

**Issue by francescovigot** [vpnhood/VpnHood#336]
Hello 
The app works fine when we test it with visual studio, but when I build the app for Windows and then install it I get an error when connecting. please find the attached. 
[](url)
![Screenshot 2023-06-02 125318](https://github.com/vpnhood/VpnHood/assets/29005428/7a78d449-f39b-4685-aca3-38899545218c)

**Comment by bobvhood** [comment]
You need to Open Visual Studio as Administrator

**Comment by francescovigot** [comment]
Please read my question again the problem is with the exported version not visual studio.
