### ISSUE TITLE
trying to install server to windows 10 via Access Server Console ...

### ISSUE THREAD

**Issue by demon740** [vpnhood/VpnHood#339]
I've tried to install server on windows 10 via Access Server Console but I get this error:
quote-->
Invoke-WebRequest : The response content cannot be parsed because the Internet Explorer engine is not available, or Internet Explorer's first-launch
configuration is not complete. Specify the UseBasicParsing parameter and try again.
At line:1 char:91
+ ... k]::Create((Invoke-WebRequest("https://github.com/vpnhood/VpnHood/rel ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotImplemented: (:) [Invoke-WebRequest], NotSupportedException
    + FullyQualifiedErrorId : WebCmdletIEDomNotSupportedException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
quote<--

as you know we can not run IE on windows 10 anymore and its replaced by EDGE and every time I run IE, it would be closed and EGDE is run instead.

thanks

**Comment by demon740** [comment]
On Monday, June 5, 2023 at 06:10:48 PM GMT+3:30, Bob ***@***.***> wrote:  
 
 


can you send me an screenshot?

**Comment by bobvhood** [comment]
> On Monday, June 5, 2023 at 06:10:48 PM GMT+3:30, Bob ***@***.***> wrote: can you send me an screenshot? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

it is empty.

**Comment by demon740** [comment]
the screenshot was attached to email.
I will send it again with this email.



    On Monday, June 5, 2023, 10:05:33 PM GMT+4:30, Bob ***@***.***> wrote:  
 
 



On Monday, June 5, 2023 at 06:10:48 PM GMT+3:30, Bob @.> wrote: can you send me an screenshot? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.>


it is empty.

**Comment by bobvhood** [comment]
Please upload it here in github issue or send it to bob@vpnhood.com

**Comment by demon740** [comment]
On Tuesday, June 6, 2023, 08:16:39 AM GMT+4:30, Bob ***@***.***> wrote:  
 
 


Please upload it here in github issue or send it to ***@***.***

**Comment by demon740** [comment]
error still exist!

![error](https://github.com/vpnhood/VpnHood/assets/54270880/34f83973-9cbd-4909-8826-0785f2439d58)
