### ISSUE TITLE
NetscanOutLevel: Netscan detected

### ISSUE THREAD

**Issue by asoMansoury** [vpnhood/VpnHood#342]
I got this error from Hetzner cloud's Datacenter. They alarmed me to solve this issue for several time on different servers.
do you have any idea for solving it?

They sent me this data to probe it.

> ##########################################################################
> #               Netscan detected from host  VpnHoodServer               #
> ##########################################################################
>
> time                protocol src_ip src_port          dest_ip dest_port
> ---------------------------------------------------------------------------
> Thu Jun 15 15:41:39 2023 TCP  VpnHoodServer 41871 =>   141.101.78.13 443 
> Thu Jun 15 15:41:40 2023 TCP  VpnHoodServer 41871 =>   141.101.78.13 443 
> Thu Jun 15 15:41:40 2023 TCP  VpnHoodServer 44091 =>   141.101.78.23 443 
> Thu Jun 15 15:41:39 2023 TCP  VpnHoodServer 43685 =>   141.101.78.24 443 
> Thu Jun 15 15:41:37 2023 TCP  VpnHoodServer 38515 =>   141.101.78.47 443 
> Thu Jun 15 15:41:38 2023 TCP  VpnHoodServer 38515 =>   141.101.78.47 443 
> Thu Jun 15 15:41:40 2023 TCP  VpnHoodServer 38515 =>   141.101.78.47 443 
> Thu Jun 15 15:41:38 2023 TCP  VpnHoodServer 37231 =>  141.101.78.108 443 
> Thu Jun 15 15:41:37 2023 TCP  VpnHoodServer 39001 =>  141.101.78.114 443 
> Thu Jun 15 15:41:38 2023 TCP  VpnHoodServer 39001 =>  141.101.78.114 443 
> Thu Jun 15 15:41:40 2023 TCP  VpnHoodServer 46025 =>  141.101.78.120 443 
> Thu Jun 15 15:41:40 2023 TCP  VpnHoodServer 33771 =>    141.101.79.6 443 
> Thu Jun 15 15:41:39 2023 TCP  VpnHoodServer 36409 =>  141.101.79.107 443 
> Thu Jun 15 15:41:40 2023 TCP  VpnHoodServer 36409 =>  141.101.79.107 443 
> Thu Jun 15 15:41:37 2023 TCP  VpnHoodServer 33549 =>  141.101.79.114 443 
> Thu Jun 15 15:41:38 2023 TCP  VpnHoodServer 33549 =>  141.101.79.114 443 
> Thu Jun 15 15:41:40 2023 TCP  VpnHoodServer 33549 =>  141.101.79.114 443 
> Thu Jun 15 15:41:38 2023 TCP  VpnHoodServer 44041 =>  141.101.79.165 443 
> Thu Jun 15 15:41:39 2023 TCP  VpnHoodServer 44041 =>  141.101.79.165 443 
> Thu Jun 15 15:41:39 2023 TCP  VpnHoodServer 37827 =>  141.101.79.192 443 
> Thu Jun 15 15:41:40 2023 TCP  VpnHoodServer 37827 =>  141.101.79.192 443 
> Thu Jun 15 15:41:38 2023 TCP  VpnHoodServer 43527 =>  141.101.79.216 443 
> Thu Jun 15 15:41:39 2023 TCP  VpnHoodServer 43527 =>  141.101.79.216 443 
> Thu Jun 15 15:41:39 2023 TCP  VpnHoodServer 39487 =>  141.101.79.226 443 
> Thu Jun 15 15:41:40 2023 TCP  VpnHoodServer 39487 =>  141.101.79.226 443 
> Thu Jun 15 15:41:39 2023 TCP  VpnHoodServer 36793 =>  141.101.79.242 443 
> Thu Jun 15 15:41:40 2023 TCP  VpnHoodServer 36793 =>  141.101.79.242 443 
> Thu Jun 15 15:41:38 2023 TCP  VpnHoodServer 36371 =>   173.245.48.51 443 
> Thu Jun 15 15:41:40 2023 TCP  VpnHoodServer 35421 =>   173.245.48.57 443 
> Thu Jun 15 15:41:37 2023 TCP  VpnHoodServer 43191 =>   173.245.48.71 443 
> Thu Jun 15 15:41:40 2023 TCP  VpnHoodServer 43191 =>   173.245.48.71 443 
> Thu Jun 15 15:41:40 2023 TCP  VpnHoodServer 35889 =>   173.245.48.93 443 
> Thu Jun 15 15:41:39 2023 TCP  VpnHoodServer 46303 =>    173.245.50.8 443 
> Thu Jun 15 15:41:40 2023 TCP  VpnHoodServer 46303 =>    173.245.50.8 443 
> Thu Jun 15 15:41:38 2023 TCP  VpnHoodServer 46431 =>   173.245.50.11 443 
> Thu Jun 15 15:41:39 2023 TCP  VpnHoodServer 46431 =>   173.245.50.11 443 
> Thu Jun 15 15:41:38 2023 TCP  VpnHoodServer 35667 =>   173.245.50.67 443 
> Thu Jun 15 15:41:40 2023 TCP  VpnHoodServer 42919 =>   173.245.50.96 443 
> Thu Jun 15 15:41:37 2023 TCP  VpnHoodServer 40929 =>  173.245.50.152 443 
> Thu Jun 15 15:41:38 2023 TCP  VpnHoodServer 40929 =>  173.245.50.152 443 
> Thu Jun 15 15:41:40 2023 TCP  VpnHoodServer 40929 =>  173.245.50.152 443 
> Thu Jun 15 15:41:40 2023 TCP  VpnHoodServer 40383 =>  173.245.50.154 443 
> Thu Jun 15 15:41:37 2023 TCP  VpnHoodServer 41393 =>  173.245.50.176 443 
> Thu Jun 15 15:41:40 2023 TCP  VpnHoodServer 41393 =>  173.245.50.176 443 
> Thu Jun 15 15:41:37 2023 TCP  VpnHoodServer 33815 =>  173.245.50.181 443 
> Thu Jun 15 15:41:38 2023 TCP  VpnHoodServer 33815 =>  173.245.50.181 443 
> Thu Jun 15 15:41:40 2023 TCP  VpnHoodServer 33815 =>  173.245.50.181 443 
> Thu Jun 15 15:41:39 2023 TCP  VpnHoodServer 37043 =>  173.245.50.187 443 
> Thu Jun 15 15:41:40 2023 TCP  VpnHoodServer 44957 =>  173.245.50.206 443 
> Thu Jun 15 15:41:40 2023 TCP  VpnHoodServer 46061 =>   173.245.51.93 443 
> Thu Jun 15 15:41:37 2023 TCP  VpnHoodServer 36405 =>  173.245.51.134 443 
> Thu Jun 15 15:41:38 2023 TCP  VpnHoodServer 36405 =>  173.245.51.134 443 
> Thu Jun 15 15:41:37 2023 TCP  VpnHoodServer 39257 =>  173.245.51.174 443 
> Thu Jun 15 15:41:38 2023 TCP  VpnHoodServer 44409 =>  173.245.51.193 443 
> Thu Jun 15 15:41:39 2023 TCP  VpnHoodServer 44409 =>  173.245.51.193 443 
> Thu Jun 15 15:41:38 2023 TCP  VpnHoodServer 39591 =>  173.245.52.117 443 
> Thu Jun 15 15:41:39 2023 TCP  VpnHoodServer 39591 =>  173.245.52.117 443 
> Thu Jun 15 15:41:38 2023 TCP  VpnHoodServer 45067 =>  173.245.52.195 443 
> Thu Jun 15 15:41:40 2023 TCP  VpnHoodServer 45067 =>  173.245.52.195 443

**Comment by trudyhood** [comment]
Hi,
Have you followed this thread?
Duplicate op #322

**Comment by asoMansoury** [comment]
> Hi, Have you followed this thread? Duplicate op #322

No, Actually I haven't followed it.
I check my console but I think you changed the panel and I do not know where I go to paste to configuration based on new Panel.

**Comment by trudyhood** [comment]
Ok. please follow it. Go to your Server Farm  > Select Server  Profile > Find Advanced Edit button.
I'm here if you have any questions.
