### ISSUE TITLE
Connection OK, but traffic not working

### ISSUE THREAD

**Issue by robsiera** [vpnhood/VpnHood#343]
I have a weird problem.
On my mobile phone I installed the newest client (2.9.370).
I can connect to my server (2.9.370 on docker).
But traffic does not work. I cannot open the vpnhood github page for example.
When I connect to your public server, traffic goes through.
When I try the Diagnose feature, no problem are found.

I have exactly the same problem on another phone.

Please advise on how I can further debug this.

**Comment by trudyhood** [comment]
Check your server fireball. Also send us your server log we may detect.
trudy@vpnhood.com
