### ISSUE TITLE
Setting up VPN Hood on the Server without Root

### ISSUE THREAD

**Issue by armin567ip** [vpnhood/VpnHood#347]
Thank you so much for checking my last case and updating the steps. But actually it's still not working. let me explain everything. I downloaded and extracted the file. I'm using x64 BTW. then after that I noticed there is actually no VpnHoodServer/launcher
directory. So after I extracted the file there was a only a folder called "v2.9.370" then inside that there was only a folder called "publish_info" and lot of other files. so then I runned this command "chmod +x VpnHoodServer" and then after that when I entered the "ls" command. the VpnHoodServer file was at green color so I guess that means that the first command was successful. But then after I runned this command "VpnHoodServer gen" it gave me "bash: VpnHoodServer: command not found".
I also wanted to use the VPN Hood access server. but it keeps giving me "There was an error trying to log you in: ''
I also used VPN but the error is still there. Please recheck and help me 🙏❤

**Comment by armin567ip** [comment]
I also tried it on another server even with root access. But it's the exact same.

**Comment by trudyhood** [comment]
Duplicate of #345 

Let's merge both issues into one
