### ISSUE TITLE
Redirects to IIS on startup

### ISSUE THREAD

**Issue by Hdfoweutgut** [vpnhood/VpnHood#349]

**Comment by trudyhood** [comment]
Hi, Would you explain it more?

**Comment by Hdfoweutgut** [comment]
Basically, when I go to "myvpnhood/", I see the IIS screen instead of VpnHood.
![image](https://github.com/vpnhood/VpnHood/assets/109148836/dd346fcb-8815-4ad2-abe6-817d6e8e49e2)

**Comment by trudyhood** [comment]
VpnHood uses 127.10.10.10 to map myvpnhood in localhost.
check "C:\Windows\System32\drivers\etc\hosts" and you should find the following line
127.10.10.10 myvpnhood

It is so weird that IIS listens to this address! Have you configured your IIS to listen to all localhost IPs?!

**Comment by Hdfoweutgut** [comment]
Idk how to do that, sorry.

**Comment by trudyhood** [comment]
> Idk how to do that, sorry.

I am sorry, but I am unsure how you configured your IIS. I would be grateful if you let us know if you solve this issue.
