### ISSUE TITLE
How to use your own domain name and certificate to build vpnhood on Linux system

### ISSUE THREAD

**Issue by 99ii** [vpnhood/VpnHood#350]
I found that building a vpnhood with a self-signed certificate can easily be blocked by the firewall。How to use your own domain name certificate to build vpnhood in Linux system.I am using ubuntu 22.04

**Comment by trudyhood** [comment]
Yes, you can use your own domain with valid certificate. Just convert your certificate to pfx file and use that. let me know if you have more questions

**Comment by 99ii** [comment]
How to operate step by step, unable to find tutorial

**Comment by trudyhood** [comment]
Are you using VpnHood Access Server or built-in File Access Server?

**Comment by 99ii** [comment]
Linux server with regular command line

**Comment by trudyhood** [comment]
Convert your certificate to pfx file, then save it as default.pfx  in the following location
\opt\VpnHoodServer\storage\access\certificates\default.pfx

Now, your certificate will be used for new tokens; if you want to use the domain in your certificate use the following command
./vpnHoodServer gen -domain

Note: Wildcard certificate is not supported

**Comment by 99ii** [comment]
How to develop a HostName

**Comment by 99ii** [comment]
How to set HostName

**Comment by 99ii** [comment]
Set HostName to its own domain name

**Comment by trudyhood** [comment]
you need to create a self signed certificate for your own domain or order an ssl from a certificate authority for your domain. After squiring the certificate, VpnHood will use that

**Comment by 99ii** [comment]
My domain's certificate is a Certificate authority Subscription SSL

**Comment by 99ii** [comment]
./VpnHoodServer gen  -domain
[10:45:39.1701] info: [0]
      Using FileAccessServer. AccessFolder: /etc/vpnhood/storage/access
The following token has been generated: 

Access Details:
{
  "Traffic": {
    "Sent": 0,
    "Received": 0
  },
  "MaxTraffic": 0,
  "ExpirationTime": null,
  "MaxClientCount": 2,
  "ActiveClientCount": 0
}

SupportId: 0
HostEndPoints: 
HostName: tae.saenypuni.net   // How is it automated here //
HostPort: 4431
TokenUpdateUrl: 
---

**Comment by trudyhood** [comment]
Have you replaced this with your SSL certificate?
\opt\VpnHoodServer\storage\access\certificates\default.pfx
