### ISSUE TITLE
Windows client that implements a network that allows only certain applications to pass through the VPN.

### ISSUE THREAD

**Issue by demooooooo** [vpnhood/VpnHood#354]
Thank you very much VpnHood, I would like to implement the feature of selecting apps for networking on the windows client like the android client, I know that the windows client doesn't have this feature right now, can you tell me how to do it if I want to implement this feature? Through what technology or documentation. Thank you very much.

**Comment by trudyhood** [comment]
We currently use WinDivert on Windows, but it is not optimized for Vpn. I recommended checking [Windows.Networking.Vpn Namespace - UWP](https://learn.microsoft.com/en-us/uwp/api/windows.networking.vpn)

Here is Microsoft Sample:
https://github.com/microsoft/UwpVpnPluginSample

It would be great if you could implement a VpnHood IPacketProvider through Windows.Networking.Vpn
https://github.com/vpnhood/VpnHood/blob/main/VpnHood.Client.Device/IPacketCapture.cs

If you just implement an IPacketProvider through Windows.Networking.Vpn, all the other jobs will be done by VpnHood. I will also merge it to VpnHood main repo. I am not sure does it support App Filtering or not, but Windows.Networking.Vpn is the latest Vpn technology on Windows.
