### ISSUE TITLE
gen key error

### ISSUE THREAD

**Issue by Onair-santa** [vpnhood/VpnHood#355]
![image](https://github.com/vpnhood/VpnHood/assets/42511409/00e6436d-65f8-48c4-b57f-70d5d20aa7d0)

**Comment by trudyhood** [comment]
I see you set to use VpnHood Access Server in your appsettings.json
So to create access tokens, you need to go to the Access Server panel 
https://github.com/vpnhood/VpnHood/wiki/VpnHood-Access-Server

if you don't want to use VpnHood Access Server, then remove HttpAccessServer and use FileAccessServer using the following configuration:
https://github.com/vpnhood/VpnHood/wiki/VpnHood-Server-Configuration

**Comment by Onair-santa** [comment]
How can I connect to my server then? There are no keys in the panel. Where can I get my connection data?

**Comment by trudyhood** [comment]
In VpnHood Access Server, you can create Key through its panel in UI. 
In File Server, you can use the "gen" command you used before, but first, you need to disconnect it from Access Server.

If you are a beginner with VpnHood, I recommend you to go to Access Server and see the Access Tokens page.
![image](https://github.com/vpnhood/VpnHood/assets/72891124/5ad3433d-1488-4cf1-82ba-ca354b1c55f8)

**Comment by Onair-santa** [comment]
![image](https://github.com/vpnhood/VpnHood/assets/42511409/4fb68dee-0951-4f22-b125-b96b4f087eda)
And how can I use this to connect on my computer?

**Comment by Onair-santa** [comment]
Without Acces server, everything works great. The client, the server is manualy installed normally and works. But they could not install through your site to another server. 10 people broke their heads, what you came up with there, nothing worked and the logic is not clear to anyone.

**Comment by trudyhood** [comment]
It looks like your server is not connected to Access Server; go to Server > Select your Server and set "Enable Automatic Configuration" to on.
![image](https://github.com/vpnhood/VpnHood/assets/72891124/66866f34-6124-486c-978d-06cce21ae4d6)

VpnHood Access Server is far more powerful than the manual, and after you get on with it, you will never use manual mode.

**Comment by Onair-santa** [comment]
![image](https://github.com/vpnhood/VpnHood/assets/42511409/322d3a0b-4c94-45b0-9757-e62fc2f61a7b)
)) ON

**Comment by trudyhood** [comment]
![image](https://github.com/vpnhood/VpnHood/assets/72891124/b2795209-e206-4459-a4a1-7fd0932c2162)

I am wondering why it is "Private"!  Refresh the page, if it doesn't fix automatically, make it off and set it to "Public In Token", make sure the IP is correct and ports and desired. then go to access tokens and get the access key.
let me know the result.

**Comment by Onair-santa** [comment]
(((

**Comment by Onair-santa** [comment]
Okay, we'll do without the panel.
Has anyone passed this quest yet?

**Comment by trudyhood** [comment]
No problem. Just disconnect it from the access server as i told you before and switch back to standalone mode.

**Comment by Onair-santa** [comment]
Second server not install too.
Acces point in clean install only in Private mode
Manualy in PubinTok
Acces Token is...
Not work install panel. Why you closed issue if Acces server not work?
![image](https://github.com/vpnhood/VpnHood/assets/42511409/e90bb100-99e0-4d92-8af0-9c9a11aa21e3)
![image](https://github.com/vpnhood/VpnHood/assets/42511409/ae92d4e8-8785-436b-9634-5bbb47a7ba25)

**Comment by Onair-santa** [comment]
1 Add pub token
2 Add server
3 Disable auto and Mode  in PubinTok
4 Acces Token and get link.
And all work fine.

**Comment by trudyhood** [comment]
Good, I hope what you have done keeps working.
