### ISSUE TITLE
Maintaining Source IP on the target system

### ISSUE THREAD

**Issue by karnilamit** [vpnhood/VpnHood#356]
Hi,

We are using VPNHood in our environment and have been loving it so far. Since VPNHood always connects to the target system we cannot get the original source IP on the target system. This becomes an issue with some of the log monitoring s/w that are running in our environment as they see the same source IP on the logs of the target application. Is there any way we could retain the source IP? This seems possible if HTTP application is used using X-Forwarded-For header, however I am not sure if TCP supports this? Our application uses TCP communication and not HTTP.

Thanks,
karnil

**Comment by trudyhood** [comment]
VpnHood is designed to protect clients from revealing client IP Addresses. If you need that, you have to save the source IP on the client side before connecting to VpnHood, then send it manually.
