### ISSUE TITLE
RedirectHost error when connecting

### ISSUE THREAD

**Issue by kmsfri** [vpnhood/VpnHood#358]
Hello. 
Sometimes, on some clients, I get a RedirectHost error and can't connect. 
This error appears in the /opt/VpnHoodServer/storage/logs/server.log file.

log detail:
2023-07-24 17:28:28.4043 | Info | Session | Server => RemoteEp: 193.*.*.101:33295 
 Exception of type 'VpnHood.Server.Exceptions.ServerSessionException' was thrown. SessionId: <null>, ClientIp: 193.*.*.101, TokenId: **-a78d-6514256b666a, SessionErrorCode: RedirectHost VpnHood.Server.Exceptions.ServerSessionException Exception of type 'VpnHood.Server.Exceptions.ServerSessionException' was thrown

Has anyone encountered this error before and solved it?

**Comment by bobvhood** [comment]
Can I have your Access Server Project id?

**Comment by kmsfri** [comment]
> Can I have your Access Server Project id?
Yes, Sure
b125a348-1b65-4ec0-8a94-efdbe49bea00

**Comment by bobvhood** [comment]
Sorry, we could find the issue. Do you still see this issue?
