### ISSUE TITLE
It's slow when I connect and watch YouTube videos, but it's fast when tested via speedtest.

### ISSUE THREAD

**Issue by do02fw** [vpnhood/VpnHood#363]
It's slow when I connect and watch YouTube videos, but it's fast when tested via speedtest.

**Comment by trudyhood** [comment]
I can help you in this case. 
1) First of all, let me know if you are using the mobile app or Windows.
2) If you are using Android,  Have you tried to open youtube in the browser instead of the app?
Please let me know before we go to the next step, so we can add a feature to help people in this case.

**Comment by do02fw** [comment]
I'm Windows and I have YouTube open in my browser and I compare to wireguard and find that vpnhood has much higher latency than wireguard.

**Comment by trudyhood** [comment]
More questions
1. Did you check the speed with VpnHood free public servers or a private one?
2. Are you sure you had selected a server in the US for checking speedtest?
3.  Wireguard may use UDP which is pretty faster but restricted in some countries. I'm so curious why are you trying VpnHood while wireguard works?

**Comment by do02fw** [comment]
I'm using a private server, I'm using a US server, I'm in China, and although wireguard works but tends to block ports, so I'm going to try other VPN protocols as well, and I'd like the vpnhood to proxy all traffic, including icmp, udp traffic, etc.

**Comment by do02fw** [comment]
I found that vpnhood is very slow to access the website, even with UDP, but openvpn's using udp is faster than vpnhood, after my test, wireguard is faster than openvpn, openvpn is faster than vpnhood.

**Comment by do02fw** [comment]
I would like vpnhood to use the quic protocol, which would be faster and more secure, and use a global proxy that can proxy all traffic like openvpn, instead of only supporting tcp and udp traffic.

**Comment by do02fw** [comment]
I ping the US server at 137ms with wireguard and 140ms with openvpn, UDP protocol.

**Comment by trudyhood** [comment]
Thank you for your feedback. I appreciate your interest in optimizing the VPN experience with VpnHood. 

We understand that VpnHood might be slightly slower than other VPNs, but it prioritizes bypassing severe firewalls and making the tunnel looks like regular traffic.

Regarding YouTube's speed, it is worth noting that YouTube utilizes UDP via QUIC whenever possible. However, it appears that VpnHood may need to be tunneling YouTube's UDP traffic via TCP, which can lead to reduced speeds. I suggest temporarily disabling YouTube's UDP, observing the results, and sharing the result with us. Please try this out and let me know how it performs. Please temporarily disable your browser QUIC protocol in Chrome by opening this page
chrome://flags#enable-quic

Regarding supporting QUIC protocol, we have already worked on it, but unfortunately, there is no library in .net to support it in Android. see #94 

However, even VpnHood support QUIC, it would not be so useful for many people who suffer from strict firewall rules that disable or disturb UDP protocol at all.

**Comment by do02fw** [comment]
Can it masquerade as another website? That would break through some whitelist blocking.

**Comment by trudyhood** [comment]
> Can it masquerade as another website? That would break through some whitelist blocking.

sorry I didn't understand that. please explain it more. also what was the result after disabling quic?

**Comment by do02fw** [comment]
I didn't disable QUIC because it's not very practical, most websites have http/2 turned on, including Chinese ones, and it would be slower if disabled, so I didn't disable it, and camouflaging a website means making it look like it's accessing a specified website, like www.baidu.com or apple.com, to bypass firewall detection.

**Comment by do02fw** [comment]
The spoofed site also breaks the QOS speed limit, which limits the speed for specific traffic.

**Comment by do02fw** [comment]
I'm currently using openvpn+UDP with chacha20-poly1305 encryption, UDP is very fast and also proxies all traffic and doesn't require a proxy server to be set up in the application.

**Comment by do02fw** [comment]
There is a downside though, you can't reach the maximum speed of the server.

**Comment by trudyhood** [comment]
i meant disable QUIC temporary for a few minutes to just check youtube speed with VpnHood so we can diagnose the issue then turn it on again

**Comment by do02fw** [comment]
I have removed the vpnhood

**Comment by trudyhood** [comment]
oh ok. thank you for trying it. so i close the issue. feel free to post another issue or continue posting to this closed issue.
