### ISSUE TITLE
Can you tell me how to use Win's packaging tool?

### ISSUE THREAD

**Issue by demooooooo** [vpnhood/VpnHood#364]
The official packaging implements the runtime environment determination, what is the packaging tool used? Is there a tutorial on how to do this? Thank you for your help!

**Comment by trudyhood** [comment]
Sorry, I didn't understand that. What do you mean by packaging tool? Did you mean advanced installer?

**Comment by demooooooo** [comment]
> Sorry, I didn't understand that. What do you mean by packaging tool? Did you mean advanced installer?
It's how to package and generate VpnHoodClient-win-x64.msi. 
![msi](https://github.com/vpnhood/VpnHood/assets/40201400/a3da1879-0573-4053-ac36-f37dd7cbeef9)

**Comment by trudyhood** [comment]
Sorry for our delay. It is Advanced Installer  as I mentioned earlier
