### ISSUE TITLE
Does not work in Centos 7

### ISSUE THREAD

**Issue by asoMansoury** [vpnhood/VpnHood#370]
Hello I have centos 7 and I isntalled vpnHood via console. 
the VpnHood is installed but as you can see in the below pic, the vpnHood console cannot configure the server properly, I have turned off my firewalld in cnetos.
do you have any suggestion for this issue?

![image](https://github.com/vpnhood/VpnHood/assets/14541559/fb75d32a-6d0d-44f7-9a4e-6c39c8fa86f6)

Once the panel shows me that nothing is installed on my centos, but I can see the vpnhood has been installed on my centos, by looking the below path

![image](https://github.com/vpnhood/VpnHood/assets/14541559/50b03db1-1a39-4f1d-8d29-bda1bdff2b15)

**Comment by trudyhood** [comment]
Unfortunately, we haven't tested to installation script on Centos, we just test it on Ubuntu. If you insist to run it over cents os you need to install it manually. however, the docker version may work too.

**Comment by asoMansoury** [comment]
and if I install VpnHood by docker or manually, can I use your console to
change server of users which is really important to me?
I really need it to install it on centos

**Comment by trudyhood** [comment]
The installation is not easy as automatic installation, but you can still use the VpnHood access server.  Use the following option.
![image](https://github.com/vpnhood/VpnHood/assets/72891124/3dc4169b-54b6-421b-9a04-0f3009ee8e63)

Use the following link, then replace its appsettings.json,
https://github.com/vpnhood/VpnHood/wiki/How-to-run-VpnHood-Server-on-Linux-using-docker
