### ISSUE TITLE
after change ssh port 

### ISSUE THREAD

**Issue by delshad1522** [vpnhood/VpnHood#372]
I would like to change the ssh port, I tried once, but I could not add the server through your panel!
Is there a way to change the port and add a server in your console and it will work?

**Comment by trudyhood** [comment]
Yes, just run this command on your server. Access Server does not need to connect to your server after installation.
![image](https://github.com/vpnhood/VpnHood/assets/72891124/bb76b0a8-151e-472a-b281-20d314eb42c8)
