### ISSUE TITLE
Address already in use !!!

### ISSUE THREAD

**Issue by delshad1522** [vpnhood/VpnHood#374]
I installed the server and now Ubuntu version 20.4
But this message appears during installation
Is there a special reason?

Address already in use !!!

<img width="368" alt="Screenshot 2023-08-23 203802" src="https://github.com/vpnhood/VpnHood/assets/131557066/78f56ccb-1b0c-4f3e-babe-9168d498bfba">

**Comment by trudyhood** [comment]
Please check this:
https://github.com/vpnhood/VpnHood/wiki/Address-Already-In-Use
