### ISSUE TITLE
Android client build

### ISSUE THREAD

**Issue by mrbluecoat** [vpnhood/VpnHood#376]
Sorry for the noob question, but I followed https://github.com/vpnhood/VpnHood/wiki/Create-a-simple-VPN-Client-for-Android thinking it would produce an *.apk file but it produced a *.dll file. In https://github.com/vpnhood/VpnHood/issues/166#issuecomment-1322617613 @trudyhood makes a distinction between _VpnHood.Samples.SimpleClient.Droid_ and _VpnHood.Client.App_ is there a guide for building the latter or _VpnHood.Client.App.Android_ to produce an *.apk ?

**Comment by trudyhood** [comment]
Hi, you built it but you need to deploy it to get the apk. Search for how to create an apk from Xamarin Project.

Good Luck
