### ISSUE TITLE
Can't generate access token

### ISSUE THREAD

**Issue by vKayroNv** [vpnhood/VpnHood#377]
![image](https://github.com/vpnhood/VpnHood/assets/36284611/ac94313b-595c-4106-8007-92c2ab41fc59)
![image](https://github.com/vpnhood/VpnHood/assets/36284611/bdaa02eb-e713-4d8f-b015-dbe84a867cac)

**Comment by trudyhood** [comment]
Hi, 
Sorry, I missed this issue. To solve this issue, you need to go to the servers page. Make sure you have at least a server for your farm, Also make sure there is at least one IP with PublicInToken in your server access points.

Also, if your domain is fake and is not registered, you need to set it as 
![image](https://github.com/vpnhood/VpnHood/assets/72891124/16943afe-c04b-4da2-8dd5-b1613f31574c)

Good luck
