### ISSUE TITLE
Deleted Token still connect 

### ISSUE THREAD

**Issue by roozbehsat** [vpnhood/VpnHood#379]
Hi guys,
I deleted one of my access token from panel and restart my server but it still connected...
Please help me...

**Comment by trudyhood** [comment]
Don't worry, the Access Manager has cached the token. Restarting the server will not help in this case. If it doesn't stop working soon, please let me know.

**Comment by roozbehsat** [comment]
It's worked after a week, is it normal?

**Comment by trudyhood** [comment]
Nope, it is not normal. It is supposed to stop working after a maximum of 1 hour. Please send me the access key. trudy@vpnhood.com

**Comment by trudyhood** [comment]
I checked it; the access key does not work. The user doesn't reconnect and perhaps keeps its connection open for a week, which is weird and rarely happens. However, we will update the VpnHood access manager to disconnect online users by 20 minutes.
