### ISSUE TITLE
428 arm64 is invalid file

### ISSUE THREAD

**Issue by mcbelisle** [vpnhood/VpnHood#389]

**Comment by SSgumS** [comment]
also the apk of 428 is for 423 instead of 427.

**Comment by bobvhood** [comment]
The latest arm version should work. The issue is with our latest update. Please update again and let me know if there are any more issues.

**Comment by bobvhood** [comment]
> also the apk of 428 is for 423 instead of 427. It is also true for 427 github released apk.

Yes, we only update the updated module in the GitHub release to prevent unnecessary updates. For example, Server or Windows Client may get updated, but Android does not change.
