### ISSUE TITLE
Update server not work and all servers down

### ISSUE THREAD

**Issue by Onair-santa** [vpnhood/VpnHood#390]
WTF 150 servers down
Autoupdate is - dog shit.
Remove from server and client.

**Comment by trudyhood** [comment]
Sorry for that. We know it was a very awful problem. However, auto-update is critical to our users. We have also fixed that issue. I hope we don't fix that issue again.

**Comment by trudyhood** [comment]
The  auto-update should fix the issue after a day by installing a new update. Please update the servers If you still have problems,
