### ISSUE TITLE
App selection list of split tunneling not loading

### ISSUE THREAD

**Issue by SSgumS** [vpnhood/VpnHood#391]
Hello
In recent versions (>=423) app selection list doesn't be populated by apps' name; no matter how much I waited.

![image](https://github.com/vpnhood/VpnHood/assets/25867589/92cb71ce-44b5-4083-97c2-de41e2764d73)

Device: Xiaomi Redmi Note 9S
Android: 12
MIUI: 14

**Comment by trudyhood** [comment]
Thank you for reporting. We have fixed and published it on Google Play. You need to wait until Google Play publishes it.

**Comment by SSgumS** [comment]
Thanks. It seems that the apk of release 429 doesn't include the fix. Only the google play version includes this fix?

**Comment by trudyhood** [comment]
> Thanks. It seems that the apk of release 429 doesn't include the fix. Only the google play version includes this fix?

Please update it again. We need to download it from Google and upload it to the repo. it must be automatic but required tons of work :(
