### ISSUE TITLE
error :   "TypeName": "SocketException

### ISSUE THREAD

**Issue by delshad1522** [vpnhood/VpnHood#394]
When installing with my username and password, I have this error, what is the reason?

  "Data": {},
  "TypeName": "SocketException",
  "TypeFullName": "System.Net.Sockets.SocketException",
  "Message": "Connection refused"
}

**Comment by trudyhood** [comment]
Hi. What do you mean by User Name and Password? Send us a screenshot or more information.

**Comment by delshad1522** [comment]
It gives this error from the part that I specified

**Comment by delshad1522** [comment]
> Hi. What do you mean by User Name and Password? Send us a screenshot or more information.

It gives this error from the part that I specified

**Comment by trudyhood** [comment]
Connection refused means the server does not listen to the SSH port (22). Maybe you run SSH on a different port, a firewall blocks it or you have not installed ssh at all.

Try to install the VpnHood server  Manually by running the command line.
