### ISSUE TITLE
max client not work

### ISSUE THREAD

**Issue by masihnazari** [vpnhood/VpnHood#395]
hi. I created a new access token and set the max client to 1.
when I connect different devices simultaneously, the client program says: "You have been disconnected because another device connected with your access key!" but it is still connected and both devices can use VPN at the same time.
I use the last server and last client update.

**Comment by trudyhood** [comment]
Hi,
It may take about 20 min for other clients to get disconnected. However, we have a plant to make it immediately when other clients are connected to the same server.
