### ISSUE TITLE
The latest version of the code is not able to connect to the server, which has a vpnhood service installed via access server.

### ISSUE THREAD

**Issue by demooooooo** [vpnhood/VpnHood#403]
I just updated the latest code and running debugging through the compiled version of the code won't connect to the server anymore. It shows Failed to open Access Denied Error Code:5. And I can connect to the server by downloading the Releases VpnHoodClient-win-x64.msi local install file. Both ways use the same access key. so I  think there is something wrong with the latest code
**Local code debugging runs, can't connect**
![error](https://github.com/vpnhood/VpnHood/assets/40201400/7a6edf4d-53eb-4d08-b51e-e458444d05cd)
**.By downloading Release VpnHoodClient-win-x64.msi and installing it, you can successfully connect to the**
![success](https://github.com/vpnhood/VpnHood/assets/40201400/b82a417f-04dc-4d89-b670-ff79f5aea894)

**Comment by demooooooo** [comment]
Additional note: The vpnhood service on the server has also just been updated with the latest version after this issue.

**Comment by trudyhood** [comment]
Hi, You need to run Visual Studio or other debugger you use as Administrator
