### ISSUE TITLE
Path to main activity for adb

### ISSUE THREAD

**Issue by Tentoshka** [vpnhood/VpnHood#405]
I'm trying start app using adb: `adb shell am start com.vpnhood.client.android/.MainActivity`
But i have error:
`Error type 3 Error: Activity class {com.vpnhood.client.android/com.vpnhood.client.android.MainActivity} does not exist.`

What is path to MainActivity for adb start?

**Comment by trudyhood** [comment]
Make sure Xamarin has been installed properly with your Visual Studio 2022. it is a regular Xamarin project and I have no idea why you get this error. Sorry that I couldn't help.
