### ISSUE TITLE
Install older version on ubuntu server

### ISSUE THREAD

**Issue by Milad305** [vpnhood/VpnHood#408]
Hi as i know vh gets updates on server by itself and when i reboot server old version replaces by new version.
Yesterday i rebooted server but when it runned again vh crashed and didnt work any more the vpnhood.status command and all othere commands was not work .
I rest the server and installed from scratch but it didnt work and gave me errors .
Is it possible to install older version ?
And make its updates manually not automatic? Because of bugs that may happen

**Comment by trudyhood** [comment]
Hi, Always use the latest version on VpnHood server, as we update it frequently. The downtime of your servers will be more by our client update than server update failure.

Instead of returning to the older version, share the installation error or the error log so we can work on it.
