### ISSUE TITLE
Installing on Centos 

### ISSUE THREAD

**Issue by asoMansoury** [vpnhood/VpnHood#409]
Hi, Hope you are doing very well and thanks for your great vpn server.
Do you have any plan to write a script for intallling this VPN server on Cent OS servers, which  as you might know most of people are using centos for managing and securing their network. I hope you are going to do asap.

Regards.

**Comment by trudyhood** [comment]
I'm afraid to say that we don't have the any plan for it as Cent OS is deprecated on 2020 and no longer maintained.
