### ISSUE TITLE
Could not find any public access point for the ServerFarm. Please configure a server for this AccessToken.

### ISSUE THREAD

**Issue by Keivan-S** [vpnhood/VpnHood#410]
when i want to generate token i get this message
no token works
i use VpnHood Access Server
server and server farm is configured.

{
  "Data": {},
  "TypeName": "InvalidOperationException",
  "TypeFullName": "System.InvalidOperationException",
  "Message": "Could not find any public access point for the ServerFarm. Please configure a server for this AccessToken."
}

**Comment by Keivan-S** [comment]
reinstalled server
no success

**Comment by trudyhood** [comment]
Hi,
Feel free to comment on this closed issue if the problem persists.
https://github.com/vpnhood/VpnHood/wiki/Could-not-find-any-public-access-point-for-the-ServerFarm

**Comment by Keivan-S** [comment]
problem still persists.
I didn't change any thing
but clients suddenly stop work

I set fake domain 
and re installed server
but ip is private again and there is only 1 ip
there is no option to change it

my friend also have this problem

**Comment by trudyhood** [comment]
You need to turn off "Automatic Configuration"

![image](https://github.com/vpnhood/VpnHood/assets/72891124/108c2359-fd56-4cff-b402-d5319d784346)

**Comment by Keivan-S** [comment]
worked
thanks
