### ISSUE TITLE
Attempted to perform an unauthorized operation.

### ISSUE THREAD

**Issue by amir-shabani12** [vpnhood/VpnHood#411]
I got the following error this morning . 
Attempted to perform an unauthorized operation.
I have not done anything and this error appears automatically. 

my server Status : active  
I can create a new user, but I can't get the tokken 
I have the following error when receiving the tokken : 
Could not find any public access point for the ServerFarm. Please configure a server for this AccessToken.
{
  "Data": {},
  "TypeName": "InvalidOperationException",
  "TypeFullName": "System.InvalidOperationException",
  "Message": "Could not find any public access point for the ServerFarm. Please configure a server for this AccessToken."
}

**Comment by trudyhood** [comment]
This service https://www.my-ip.io/api-usage has changed its endpoint, causing VpnHoodServer to apply the configuration on restart. We have fixed it and uploaded a new version (433). Just go to your server and update it. It also should be fixed automatically after a few hours.
/opt/VpnHoodServer/vhupdate

Thank you for using VpnHood
