### ISSUE TITLE
Killswitch not work

### ISSUE THREAD

**Issue by Onair-santa** [vpnhood/VpnHood#415]
Only 1 m.
Need killswitch w/o ISP traffic

**Comment by trudyhood** [comment]
What's that? would you explain more?

**Comment by Onair-santa** [comment]
Killswitch function - if the server fails, traffic does not go through the provider until you disable the program.
A very useful feature.
Now the traffic does not go through the provider while the program is trying to connect, but after a minute or two it disconnects when the attempt to connect to the server fails.

**Comment by trudyhood** [comment]
Android has already have the always on feature and VpnHood supports it. It would be better than custom implementation in the app because if the app crash, the "always on" still protects the client. However we may need to implement it for Windows, but it will still not so reliable in case of crashing.

**Comment by Onair-santa** [comment]
I'm sorry. I forgot to specify the system. Windows
For our purposes, it is very important that traffic never bypasses the VPN. Even if the server goes down or the Internet fails. Permanent network blocking is necessary, even if the server is not running. If you do this, it will be very good.
Thank you

**Comment by Onair-santa** [comment]
Ups. The issue is resolved, there is this feature in the settings
"MaxReconnectCount": 20,
How to put an infinite number?

**Comment by trudyhood** [comment]
We've made significant progress, but it's not quite ready yet. We're hoping to implement additional options to improve reliability. Currently, using MaxReconnectCount can be unreliable as it may reinitialize the adapter and lead to leaks. Additionally, relying on a kill switch in the app can be risky, as app crashes are always a possibility.

**Comment by Onair-santa** [comment]
I understand. But if I leave it at 10 for now, for example, isn’t it very critical?
Leaks are not at all important in my work, but loss of connection is critical

**Comment by trudyhood** [comment]
If so, try the latest version; it won't even reconnect and will keep establishing the connection for up to 3 days unless your server rejects the connection, such as when your access token expires.
If not, please report it to us.

We will also release a new version soon.

**Comment by trudyhood** [comment]
I am wondering if the recent version solves the issue you had?
