### ISSUE TITLE
Connecting to VPN through domain

### ISSUE THREAD

**Issue by armin567ip** [vpnhood/VpnHood#418]
Hi, I have a feature request which is super vital to make the VPN more undetectable from the firewall systems.
Using domain.
That's right, Connecting through a domain on port 443 makes it much harder for the firewall and ISPs to detect that we are using a VPN and it makes it like we are viewing a web page, Iran has really developed it's GFW and it can easily detect and block the server if we are connecting through an IP address.

**Comment by trudyhood** [comment]
It has already been implemented. You can go to the server farm to specify a domain or even your valid certificate.

![image](https://github.com/vpnhood/VpnHood/assets/72891124/9a5a71b4-3f49-4548-b3da-9cb47f850535)

If you don't use Access Server, then follow this: #350
