### ISSUE TITLE
How to try HttpAccess

### ISSUE THREAD

**Issue by demooooooo** [vpnhood/VpnHood#419]
I would like to realize my own https://access.vpnhood.com
function of the vpnhood. I noticed that the server service of vpnhood, needs to be implemented using HttpAccessManager, I didn't find any documentation related to HttpAccessManager, can you tell me how to implement it, by accessing the server API to manage Access? This in order to achieve the functionality effect of access.vpnhood.com.

**Comment by trudyhood** [comment]
I apologize, but there is currently no documentation available. However, you can refer to the source code which can be found here:
https://github.com/vpnhood/VpnHood/tree/main/VpnHood.Server.Access/Managers

You can also get some idea from the swagger:
https://access.vpnhood.com/swagger/index.html

**Comment by demooooooo** [comment]
Thank you very much, I would also like to ask if you allow me to use this program to sell my own server services? For example, putting the client on the Google store after my secondary development and allowing users to pay for my services.

> I apologize, but there is currently no documentation available. However, you can refer to the source code which can be found here: https://github.com/vpnhood/VpnHood/tree/main/VpnHood.Server.Access/Managers
> 
> You can also get some idea from the swagger: https://access.vpnhood.com/swagger/index.html

**Comment by trudyhood** [comment]
Yes, you can.
