### ISSUE TITLE
Could not protect socket error

### ISSUE THREAD

**Issue by SalimiHabib** [vpnhood/VpnHood#421]
i try client nugget and also compiled from source in MAUI last version and vs 2022 17.7.6

but getting Exception "Could not protect socket"

server already tested on port  443 using provided android client and working  .

my calling method is as below 

```
    
  private async Task ConnectTask()
        {
            try
            {
        
                if (IsConnectingOrConnected)
                    Disconnect();

#if ANDROID
       
              
                var accessKey = "------------------";
                var token = Token.FromAccessKey(accessKey);
    
                var clientId = Guid.Parse("-------------------------");


                // accessKey must obtain from the server


                AndroidPacketCapture packetCapture = new()
                {
                     
                };

                vpnHoodClient = new VpnHoodClient(packetCapture, clientId, token, new ClientOptions()
                {
                     ExcludeLocalNetwork = true,
                      UseUdpChannel=true,
                     
                  
                });


                vpnHoodClient.StateChanged += VpnHoodClient_StateChanged;
                await vpnHoodClient.Connect();
#endif

            }
            catch (Exception ex)
            {
                var str = ex.Message;
            }
        }

```

thank you

**Comment by trudyhood** [comment]
Please postpone MAUI till .NET 8 arrives officially, as we had a severe issue that has been solved in .NET 8. 
We hope we can support MAUI after .NET 8 official release, which means the next few days.

**Comment by SalimiHabib** [comment]
It will be great.

Thank you

**Comment by SalimiHabib** [comment]
is there any news for MAUI ?

**Comment by trudyhood** [comment]
> is there any news for MAUI ?

There is much progress and it is already done. However, we may just release a sample for Maui. VpnHood official app uses SPA not Maui. 

You will be able to build your Maui app. please note that just Window and iOS are supported at the moment.

**Comment by 23080803973** [comment]
is it possible to use  SPA (using MAUI Blazor) for android platform in new release ?

**Comment by trudyhood** [comment]
> is it possible to use SPA (using MAUI Blazor) for android platform in new release ?

Do you mean "Blazor WebAssembly"?

**Comment by 23080803973** [comment]
yes 
As you said native is not ready for android yet in new release (for MAUI) and i am trying to find a way to fill gap in my project .

**Comment by trudyhood** [comment]
> MAUI Blazor

VpnHood built on .Net Standard 2.1 means using .NET for Android, Windows, MAUI, MAUI Blazor, and iOS. However, the PacketCapture module only exists on .Net for Android and Windows, so you can not run it over iOS. 
Overall, you can integrate it into any .net platform.

**Comment by trudyhood** [comment]
> yes As you said native is not ready for android yet in new release (for MAUI) and i am trying to find a way to fill gap in my project .

The problem was that the previous version was using Xamarin for PacketCaptrue, so we couldn't integrate it into MAUI but now we are migrating to ".Net for Android" which makes it compatible with MAUI. The PacketCapture protect is just two small files, but it is our main bottleneck that implies some restrictions as it hugely depends on the device's OS.

**Comment by 23080803973** [comment]
sorry  , may be your answer need small correction 
 **please note that just Window and iOS are supported at the moment.**
 IOS can be replaced by android

**Comment by trudyhood** [comment]
This issue must be solved in the recent version.
