### ISSUE TITLE
Vpnhood Access Server Unable to install

### ISSUE THREAD

**Issue by demooooooo** [vpnhood/VpnHood#423]
I am currently managing my server through Vpnhood Access Server on a Cenos 7 system. I used super administrator root for the installation. But the status is always NotInstalled.I do this by Install on Linux by UserName & Password , providing the super administrator's account and password.

**Comment by trudyhood** [comment]
Hi, Unfortunately, the installation script does not support cents OS as cents OS has been deprecated since 2021.

**Comment by demooooooo** [comment]
So what operating system do you recommend

> Hi, Unfortunately, the installation script does not support cents OS as cents OS has been deprecated since 2021.

**Comment by demooooooo** [comment]
> Hi, Unfortunately, the installation script does not support cents OS as cents OS has been deprecated since 2021.
My other server is also centos 7, and it installs fine, which is strange.

**Comment by trudyhood** [comment]
> So what operating system do you recommend
> 
> > Hi, Unfortunately, the installation script does not support cents OS as cents OS has been deprecated since 2021.

We test the VpnHood Server on Ubuntu.

**Comment by demooooooo** [comment]
> > So what operating system do you recommend
> > > Hi, Unfortunately, the installation script does not support cents OS as cents OS has been deprecated since 2021.
> 
> We test the VpnHood Server on Ubuntu.

![ser](https://github.com/vpnhood/VpnHood/assets/40201400/7b60b4a0-1e20-4c88-ac6b-1cbb8e2dd875)
Two other servers and it will be installed successfully

**Comment by trudyhood** [comment]
> My other server is also centos 7, and it installs fine, which is strange.

It is important to note that VpnHood Server is designed to work on all Linux systems. However, it should be noted that the installation script may run some commands or packages not that compatible with every Linux distribution. We do not have the resources to ensure compatibility with every distribution. Therefore, it is possible that you may not be able to update the software in the future if you choose to install it on an incompatible distribution.

You may be able to install in on CentOS, but unfortunately, we can not help you with that.

**Comment by demooooooo** [comment]
> > My other server is also centos 7, and it installs fine, which is strange.
> 
> It is important to note that VpnHood Server is designed to work on all Linux systems. However, it should be noted that the installation script may run some commands or packages not that compatible with every Linux distribution. We do not have the resources to ensure compatibility with every distribution. Therefore, it is possible that you may not be able to update the software in the future if you choose to install it on an incompatible distribution.
> 
> You may be able to install in on CentOS, but unfortunately, we can not help you with that.

I'm changing my OS to Ubuntu now to try it out. Thank you!

**Comment by demooooooo** [comment]
> > > My other server is also centos 7, and it installs fine, which is strange.
> > 
> > 
> > It is important to note that VpnHood Server is designed to work on all Linux systems. However, it should be noted that the installation script may run some commands or packages not that compatible with every Linux distribution. We do not have the resources to ensure compatibility with every distribution. Therefore, it is possible that you may not be able to update the software in the future if you choose to install it on an incompatible distribution.
> > You may be able to install in on CentOS, but unfortunately, we can not help you with that.
> 
> I'm changing my OS to Ubuntu now to try it out. Thank you!

Unfortunately, I changed the operating system to Ubuntu 18.04.6 and the problem is still the same, I can't install the Server service

**Comment by trudyhood** [comment]
Why don't you install Ubuntu 22.04?

**Comment by demooooooo** [comment]
> Why don't you install Ubuntu 22.04?

The server vendor's mirrors, only 18.04 and 16.04 versions are available. So I'm stuck with this one
![1](https://github.com/vpnhood/VpnHood/assets/40201400/40a7f621-08d4-43d4-96a6-e36fe5b1464f)

**Comment by trudyhood** [comment]
oops! Kindly run the VpnHood installation script and share the output with me for further assistance. You can find the installation script command line in the panel by choosing Manual Installation.

**Comment by demooooooo** [comment]
> oops! Kindly run the VpnHood installation script and share the output with me for further assistance. You can find the installation script command line in the panel by choosing Manual Installation.

![2](https://github.com/vpnhood/VpnHood/assets/40201400/1e07cae1-bdc0-4493-a9e3-e4ad60a39844)

**Comment by trudyhood** [comment]
ok, type 
```sh
systemctl status VpnHoodServer
```

also go to /opt/VpnHoodServer/storage/ and share me the server log.

**Comment by demooooooo** [comment]
As you did, there is no server log file generated in the /opt/VpnHoodServer/storage/ directory, only the appsetting.json file. The status of executing the command is as follows
![32](https://github.com/vpnhood/VpnHood/assets/40201400/9565a188-7074-4fd1-9ab5-57eb81ff3ced)

**Comment by trudyhood** [comment]
Can you find any system log describing the error. Does it show anything more at the bottom your snapshot?

**Comment by demooooooo** [comment]
Can I send the server info to your email? Would it be convenient for you to help me troubleshoot the cause?

**Comment by trudyhood** [comment]
send to trudy@vpnhood.com

**Comment by demooooooo** [comment]
> Sorry, your Linux is 32-bit. We do not support it at all. That may be why you can't install the newer version of Ubuntu as the latest 32 bit version is 18.04 LTS. VpnHoodServer requires 64 bit OS

I have now upgraded my server to Ubuntu 20.04 64 bit OS
It's possible to build the service normally.
But now there is another problem that occurs when the client connects to the server, the
 The SSL connection could not be established, see inner exception.
The remote host forced an existing connection to close

**Comment by trudyhood** [comment]
> The remote host forced an existing connection to close

It means the server doesn't listen to that IP or that port. double check your IP and generate the token again if your server IP has changed

**Comment by demooooooo** [comment]
The server IP has not been changed, the client can connect to the server normally and show successful connection, but the debugging logs will show anomalies, and the client is disconnected from the server very frequently during the connection process. Frequent disconnections and reconnections

**Comment by trudyhood** [comment]
give me an access key please. trudy@vpnhood.com

**Comment by trudyhood** [comment]
![image](https://github.com/vpnhood/VpnHood/assets/72891124/1f4ffe07-7d3e-4cab-902f-0412a17ffe26)

I'm sorry to hear that you're experiencing an issue, but I am unable to replicate it on my end. It seems my VPN on windows is operating at an impressive speed of 150Mb/s, which is the limit of VpnHood on Windows client. Based on this, I believe your server has a much higher speed that can be shared with multiple users.

Please send me a diagnose info form your end:
see this:
https://github.com/vpnhood/VpnHood/wiki/How-to-send-the-VpnHood-Client-diagnosis-report
