### ISSUE TITLE
status lost after some minutes

### ISSUE THREAD

**Issue by Keivan-S** [vpnhood/VpnHood#425]
hi
i have a problem in accees server
my connection status canges to lost after some minutes
and i need to re install server to work again.
any idea?

**Comment by trudyhood** [comment]
Please send me the server log and your Access Server Project Id
trudy@gmail.com

**Comment by Keivan-S** [comment]
please check the address. goth this error on gmail:
The email account that you tried to reach does not exist. Please try double-checking the recipient's email address for typos or unnecessary spaces.

**Comment by Keivan-S** [comment]
sent to this address:
trudy@vpnhood.com

**Comment by Keivan-S** [comment]
Could not send server status. VpnHood.Common.Client.ApiException The HTTP status code of the response was not expected (401).

**Comment by trudyhood** [comment]
> Could not send server status. VpnHood.Common.Client.ApiException The HTTP status code of the response was not expected (401).
> 
> Status: 401 Response:

It can be a very important issue and must be solved as soon as possible. We are working on it now.
Thank you for reporting it

**Comment by bobvhood** [comment]
Hey everyone, I'm not entirely certain what was causing the issue with the server, but I managed to fix it by replacing the app settings. It seems that the initial problem was related to an incorrect authorization key. I'm curious to know how that key was generated in the first place. I also tried to setup the server with automatic username & password and i couldn't find any issue.

@trudyhood I am concerned that our new authentication system is generating invalid keys; we need to monitor it closely.

@Keivan-S Are you sure you did not accidentally change the key? What was the last time you change the server appsettings.json and how did you do that? did you use automatic installation or manual?
![image](https://github.com/vpnhood/VpnHood/assets/92276967/3b85d1d1-6198-40e0-9154-c2b322cfb06d)

Your server is now working and I can't see any issue on it.
I am closing the issue, but please feel free to leave your comments if you have any ideas or suggestions.

**Comment by trudyhood** [comment]
> sent to this address: [trudy@vpnhood.com](mailto:trudy@vpnhood.com)

Thank you @Keivan-S , sorry for my mistake. Please change the server password as soon as possible.
Good luck

**Comment by Keivan-S** [comment]
The problem is that I did not change anything and even deleted and reinstalled the server app several times. But after some minutes status was "lost" again

**Comment by Keivan-S** [comment]
@bobvhood 
installed several times, manualy by generated code and by user name and password too.

**Comment by trudyhood** [comment]
Has it been solved now?

**Comment by bobvhood** [comment]
We found the issue. VpnHood Access Manager generated short life (less than an hour) server access key recently. We fixed it.
@Keivan-S  Please reinstall your server again. It shouldn't go to lost state after an hour now.
