### ISSUE TITLE
The vpnhood service won't start on the server

### ISSUE THREAD

**Issue by demooooooo** [vpnhood/VpnHood#430]
My OS version is Ubuntu 22.04 LTS - and with the install command on the server, it starts the vpnhood server normally.The server logs are as follows
`2023-12-03 04:54:17.8637 | Info |  | Server 
 Module: VpnHood.Server, Version=3.1.433.0, Culture=neutral, PublicKeyToken=null  

2023-12-03 04:54:17.9170 | Info |  | Server 
 OS: Ubuntu 22.04.3 LTS, X64, TotalMemory: 61 GB, Logical Cores: 40  

2023-12-03 04:54:17.9214 | Info |  | Server 
 DefaultTcpKernelSentBufferSize: 16384, DefaultTcpKernelReceiveBufferSize: 131072  

2023-12-03 04:54:17.9844 | Info |  | Server 
 Configuring by the Access Server...  

2023-12-03 04:54:27.5489 | Info |  | Server 
 Public IPv4: 185.*.*.238, Public IPv6: <null>, IsV6Supported: False  

2023-12-03 04:56:07.6728 | Error |  | Server 
 Could not configure server! Retrying after 60 seconds. System.Threading.Tasks.TaskCanceledException The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing. 

`

**Comment by demooooooo** [comment]
I went through the troubleshooting and tried the trial server trying to ping access.vpnhood.com, and found that the network was not available. I don't know if this is the cause of this.
![3](https://github.com/vpnhood/VpnHood/assets/40201400/818b219a-8d94-4c5b-9bf7-cc32e3a349a0)

**Comment by demooooooo** [comment]
Still not working. I use the server Ping console.vpnhood.com just fine. I think that's what's preventing the server from installing vpnhood.
![4](https://github.com/vpnhood/VpnHood/assets/40201400/1d2606cc-922a-4105-841d-cdd27fb12cb0)

**Comment by demooooooo** [comment]
> Does it work now on your end?

On my server, I still can't install the vpnhood service.

**Comment by trudyhood** [comment]
I see you can ping the server, I need the error message. you can send it here or to my email. By the way we are going to update the access manager and we have about 1 hour downtime
trudy@vpnhood.com
