### ISSUE TITLE
reconnect sometimes

### ISSUE THREAD

**Issue by b14aa178** [vpnhood/VpnHood#432]
It's reconnect every 1-3 mintues, and while it's show 'Connecting', seems take long time. in this log, the disconnect and connect happend at 19:38:20 - 19:38:30.

i test gta5 while it's reconnect. the game it's ok, it's never disconnect. but i think it's base on UDP. so i will test some game use TCP later.

windows 11
vpnhood v448

[log.txt](https://github.com/vpnhood/VpnHood/files/13684812/log.txt)

**Comment by JiJi85p** [comment]
i how the same problem
We use tunneling in Iran to establish the Connection, But my clients encounter with such issue : " Connecting !"
Whats the problem ?

**Comment by trudyhood** [comment]
The connecting status should be improved. VpnHood uses multiple connections, and when one connection fails, the status goes into connecting state while the other connection still works. If you see the client frequently going into the "Connecting" state while it is working, it means that the client network is unreliable or your server is overwhelmed.

@b14aa178 The log file you sent is empty
