### ISSUE TITLE
Adding logs.

### ISSUE THREAD

**Issue by mohnishsiyodia** [vpnhood/VpnHood#435]
After authentication and connected to the VPN I want to add logs in the following VpnHood code;

- VpnHood.Client
- VpnHood.Client.Device
- VpnHood.Client.Device.Android
- VpnHood.Common
- VpnHood.Tunneling

Currently after the connection the internet access has been interrupted and I need to check the logs after the connection when the web apps are being browsed.

**Comment by trudyhood** [comment]
You can see the log by starting the diagnostic. If you need to add a specific log somewhere that we didn't trace any log, you need to fork the project and add it by yourself. 
We would appreciate you sharing any issue you may found so we can improve VpnHood together.
