### ISSUE TITLE
Lost DNS service.

### ISSUE THREAD

**Issue by rainwolfchen** [vpnhood/VpnHood#436]
Version 3.2.448 will lose DNS service after a period of time, sometimes half a day and sometimes several days. After restarting the VPNHood server, the client reconnects and the DNS service becomes normal again.

**Comment by trudyhood** [comment]
Hi,
Do you use udp protocol?

**Comment by rainwolfchen** [comment]
Yes, I use udp protocol.

**Comment by trudyhood** [comment]
can you turn it off and let me know the result?

**Comment by rainwolfchen** [comment]
Okay, I'll try using the tcp protocol, because it only happens occasionally, and I need to observe it for a while to know the result.

**Comment by rainwolfchen** [comment]
DNS loss also occurs when using TCP mode, but after refreshing the browser, the DNS service can return to normal by itself. However, refreshing in UDP mode cannot restore it. You need to restart the VPNHood server and restart the client to regain the DNS. Serve.

**Comment by trudyhood** [comment]
Please check with the latest version 553
