### ISSUE TITLE
Hi Ipv4 on VPN hood

### ISSUE THREAD

**Issue by asoMansoury** [vpnhood/VpnHood#440]
In my country foreig IPv4s are being inspected by government so whenever some people connect to a specific IPV4 the server will be filtered but they aren't able to discover IPV6. I used tunneling to connect my vpnhood via Iranian's server, so I need to hide my IPv4 completely.
Do you have any feature for hiding IPV4?

**Comment by trudyhood** [comment]
Hi, There is no magic to hiding IP. However, VpnHood tried to look like regular website traffic. We have many reports that servers get blocked from Iran. If you have any idea who they mark a server as VpnServer, please share it with us so we can work on that concept.

Now, we are working on a mechanism that allows you to update all of your clients' tokens when the server's IP gets blocked. It is 50% done.

**Comment by asoMansoury** [comment]
> Hi, There is no magic to hiding IP. However, VpnHood tried to look like regular website traffic. We have many reports that servers get blocked from Iran. If you have any idea who they mark a server as VpnServer, please share it with us so we can work on that concept.
> 
> Now, we are working on a mechanism that allows you to update all of your clients' tokens when the server's IP gets blocked. It is 50% done.

I think they already recognized your pattern for sending and receiving data , so I think they just set your pattern onto their inspecting filtering devices, so once they recognize these patterns which is being sent to another foreign IP, they will block that pattern and IP.
So I think by making a way to make dynamic your send/receive data pattern between client app and server and make changeable in console.vpnhood.com by Admin then that would be really hard to recognize VpnHood servers.
I think per each ServerFarm, you have to set a key to be configurable by admin to change your encryption/pattern/protocol/algorithm which you are using to send/receive data between servers and clients.
I hope get a good clue to you for avoiding your servers being blocked.

Another way to avoid from being detected is about making a tunneling way to make a tunnel between Iranian server and original Vpnhood server, and sending data to VpnHood server through Iranian server.
In case of Iran having tunneling feature is really crucial.

**Comment by trudyhood** [comment]
VpnHood does not have any pattern, but of course, it may have a flaw. VpnHood Server behaves 100% like a traditional web server. 

Please check this issue and see what I recommended for double IP #444

> Another way to avoid from being detected is about making a tunneling way to make a tunnel between Iranian server and original Vpnhood server, and sending data to VpnHood server through Iranian server.
In case of Iran having tunneling feature is really crucial.

You can already do that by configuring VpnHood. I can remember you have already created a document for that.
