### ISSUE TITLE
how to Hidden IP in Vpnhood Server ?

### ISSUE THREAD

**Issue by JiJi85p** [vpnhood/VpnHood#444]
Hi Trudy.
 I hope you're doing well. 

I'm having trouble using vpnhood service in Iran. The issue is that the Iranian government quickly identifies and blocks the IP server as soon as it's detected. 
Do you have any suggestions on how to prevent the identification of the IP server?
Is it possible to use IPv6 instead of IPv4? 

Thank you.

**Comment by trudyhood** [comment]
We have some reports that IPv6 is not supported in Iran.
"I believe they utilize their own services to identify VPN servers. To avoid detection, I suggest implementing double IP on your server. Ensure that the gateway IP is not the same as the public IP of your server that users connect to. Your server should have two IP addresses, with users connecting to IP1. However, when they search for "My IP", they should see second IP2 (your server gateway)."

ow, we are working on a mechanism that allows you to update all of your clients' tokens when the server's IP gets blocked. It is 50% done.

**Comment by trudyhood** [comment]
VpnHood is an HTTPS proxy server using TLS 1.2, which is a new version of SSL. SSL is deprecated and no longer used; however, people still call TLS protocol SSL; these days, all websites are HTTPS via TLS 1.2 or 1.3.

Using a VPN can hide a client's IP address from a site publisher, but it cannot conceal the destination IP address from the network provider.

We strive to make improvements, but recent changes won't solve blocking. However, the new feature that will come in the following weeks help you update all your client IPs and eliminate the need to share new keys with all of them,

**Comment by JiJi85p** [comment]
Thank you very much Trudy !
Can you tell me if you have any program to prevent the identification of the "destination IP"?
Is there any way we can use to keep the "destination IP" hidden from the internet provider's view? 

Fighting against filtering becomes a humanitarian issue in many countries, doubling the value and importance of combating filtering.

**Comment by trudyhood** [comment]
We are unsure how they may detect the IP; however, soon, you can automatically update your server IP and domain by uploading shared secrets via any third-party site, so you can change the server IP when they detect it, which is transparent to your clients.

Also, as I told you before, make sure your server has two IPs and don't use the gateway IP as PublicInToken

**Comment by trudyhood** [comment]
We have updated the VpnHood server, client, and access manager. Now, you can update all tokens via a third-party external link in case your server IP gets blocked.
