### ISSUE TITLE
Android logs location after VpnHood connection.

### ISSUE THREAD

**Issue by mohnishsiyodia** [vpnhood/VpnHood#448]
I have been using VpnHood version 2.1.276 and while connecting i need to verify the logs.

**VhLogger.Instance.LogTrace($"Starting {VhLogger.FormatTypeName<TcpProxyHost>()}...");**

I need to know the location on the device where I can find the above logs or the path were they are stored so I can check for success & failure logs.

Kindly guide me where I can find these logs on the device where the application is running.

![vpnhood](https://github.com/vpnhood/VpnHood/assets/53507901/780a6fc1-4d0b-42a0-804f-4400a099b24a)

**Comment by trudyhood** [comment]
I don't know about 2.1.276, it is drastically old.
But you can start the connection using diagnose mode or see how we create the logger in the latest version AppLogService
You need to initialize VhLogger.Instance
