### ISSUE TITLE
All of my users have disconnected after the last update!

### ISSUE THREAD

**Issue by AmirHosseinCV** [vpnhood/VpnHood#450]
Thanks to your last update, without considering the backward compatibility, my vpnhood servers are not functioning anymore and about 2000 of my users have disconnected! The vpnhood server keeps crashing because some of tokens have converted to the new format and some of them have not. 
Is there any way to revert everything to the previous version? I have developed my own control panel on the previous version and now EVERYTHING is corrupted!

**Comment by trudyhood** [comment]
Hi,
We are so sorry for that. We are considering backward compatibility and have tested it with many servers.
The conversation was part of considering backward compatibility, but it doesn't work on your server as expected. The server created a backup for old tokens before overriding them. So you can restore it, and we are here to help you if the new server can not covert the old tokens.

With the new token format, you can change your server address without sending a new token for each client. This feature is useful when your server IP is blocked.

Let us know how we can help you.
Sorry for this inconvenience.

**Comment by AmirHosseinCV** [comment]
Thanks for your reply. The backup helped me to solve the problem. I restored the backup and reinstalled the version v3.2.448. Now everything looks fine.
To make the version v3.3.454 work, I had to manually edit the version file (replace 4 with 3) in the access folder and remove the backup directory. After that, with a restart, it converted all of the tokens to version 4 successfully. 
Using `ServerTokenUrl` instead of update url (the previous method) is a good change.

I wish you the best with your great project.

**Comment by SalimiHabib** [comment]
it seems  server automatic update cannot transfer appsetting.json , our instance use  " `"PublicEndPoints": ["1*.248.45.*:443" ],"`   and is in windows ,  but it mess  up every thing .

please consider to set it to manual .

thank you

**Comment by trudyhood** [comment]
I added it to the enhancement #509

**Comment by trudyhood** [comment]
What was your server version before the update? Can you share the error?

**Comment by SalimiHabib** [comment]
sure 
it was   v3.3.470

and error  is about  `PublicEndPoints `that i use in `appsetting.json` , new version  don't have that section , it seems in update  `appsetting.json`  file will be generate as new default setting , without adding previous setting .

**Comment by trudyhood** [comment]
Please use TcpEndPoints instead. 
If the PublicEndPoints and TcpEndPoints are not the same, then make use of the PublicEndPoints, otherwise just delete PublicEndPoints.
Check https://github.com/vpnhood/VpnHood/wiki/VpnHood-Server-Configuration

**Comment by Onair-santa** [comment]
new appsettings.json not work.
Auto-updates are evil. Same problems all the time. Auto-update comes out and hundreds of servers stop working. You write an error, restore the old version and a month later everything is new. The best solution for us was to simply remove the updater and never update either the server or the application again.

**Comment by trudyhood** [comment]
Dear @Onair-santa
I think you need to disable auto-update if you are not using VpnHood Access Manager, as we do not extensively test File Access Manager compatibility. Additionally, you should fork the app, as VpnHood undergoes rapid modifications and deprecates old code every few months to support new features and maintain clean code.

You can easily stop the auto-update service or just delete vhupdate file after installation.

**Comment by Onair-santa** [comment]
new appsettings.json not work
The server does not start. Neither with the default configuration nor with specified endpoints and addresses.
Everything has been checked dozens of times, this is an old error for you and I already wrote about it

**Comment by trudyhood** [comment]
@Onair-santa 
We didn't have to change it recently; maybe your server was too old. However, if you let me know the error message and the log file I may be able to help.

**Comment by Onair-santa** [comment]
![image](https://github.com/vpnhood/VpnHood/assets/42511409/5cc6ddab-e18a-42c8-9c12-2d2a4ecca2d0)

**Comment by trudyhood** [comment]
CAn you restart the VpnHoodServer service and share me the log?
```
systemctl restart VpnHoodServer
```
You can find the log in /opt/VpnHoodServer/storage/logs/server/log
