### ISSUE TITLE
Cohabitate Nginx https server and Vpnhood (:443)

### ISSUE THREAD

**Issue by Jeje292** [vpnhood/VpnHood#452]
Hello,

Do you know how to cohabitate Nginx https server and VpnHood (sharing the same port : 443) on the same Linux server ?

I found SSLH with OpenVPN / Nginx, but I don't know how configure it with VpnHood.

Thank you for create this great app and for your help :)

**Comment by trudyhood** [comment]
I am unsure if it is possible to share the same port with VpnHood and Nginx . But you can consider two options:
1. Buy another IP and use port 443
2. Change the port to 8443, which is the common port when 443 is not available
