### ISSUE TITLE
use VPN hood behind Reverse proxy 

### ISSUE THREAD

**Issue by SalimiHabib** [vpnhood/VpnHood#453]
Hello

How we can use VPNhood behind YARP proxy , is there any consideration about SSL termination ?

Thank you

**Comment by trudyhood** [comment]
Hi,

VpnHood does not support reverse proxies such as CloudFlare or YARP proxy. We have done some work on it but left it, and now it is not on our table. It will drastically decrease the performance.

**Comment by trudyhood** [comment]
We have added support to reverse proxies such as CloudFlare to VpnHood version 725
