### ISSUE TITLE
client zip

### ISSUE THREAD

**Issue by 3052** [vpnhood/VpnHood#455]
I see a server zip:

VpnHoodServer-win-x64.zip

but not a client zip:

VpnHoodClient-win-x64.msi

**Comment by trudyhood** [comment]
Your sentence could be clarified as follows:

"We previously had it, but it was discontinued because there was no demand for it. What are the advantages of using a ZIP file compared to an MSI installer?"

**Comment by 3052** [comment]
typically an installer will do several things:

- add files to program folder
- add files to user folder
- add registry keys
- add shortcuts

these are bad on their own, but many times an uninstaller is either non existing, or crappy in that is removes only some or none of the above items. so Zip is usually preferred, in that it usually keeps any changes confined to the same folder as the extracted executable

**Comment by trudyhood** [comment]
In that case, our MSI installer is cleaner than the client app, as it stores user data in the User LocalData folder. The app requires admin privileges to initiate the packet driver, and the app is not yet digitally signed. Therefore, if a user distrusts the MSI installer, they should also be cautious with the app too. Also the update would be tricky and VpnHood development is so active.

**Comment by 3052** [comment]
still, I prefer Zip because I do not want an app adding files to User LocalData folder. if its an old trusted app thats OK, but not a new app I never used before.

**Comment by trudyhood** [comment]
I understand your point. However, as I mentioned earlier, even the ZIP file adds files to the LocalData folder. Therefore, if we decide to release the client in a ZIP format, we need to configure its default working directory beforehand. 

For app evaluation, I suggest using Windows Sandbox or a virtual machine instead of solely depending on the installation method.
