### ISSUE TITLE
change Server by Customer

### ISSUE THREAD

**Issue by JiJi85p** [vpnhood/VpnHood#461]
Hello Trudy. 
I hope you are doing well!
In the new version, has the option to change the server connection been added by the user themselves? If yes, please explain to us how to set up and use it in this please.

**Comment by trudyhood** [comment]
Hi, you can always give them different tokens, and they can easily change between servers by pressing the server section. This feature has existed since the first day. Perhaps you are looking for something else. Would you explain more?

**Comment by asoMansoury** [comment]
Hi Trudy, I think having this feature is really critical , you can design a public page to make users able to change their servers .
For example you can design a new button on client app and labeled it as change user, then user should be redirected to another page and from there they should be able to pick available servers and change their servers if they need.
I already rerouted your VPNHOOD via ipv6 and it's been working  but right now for having a better VPN Experience I think having this feature is really crucial.

**Comment by trudyhood** [comment]
I'm sorry, but I still can't seem to understand your idea. Which server are you referring to? Do you mean a repository for public servers? How do you plan to define these servers? Could you give me more details and a clearer flow to understand what you're suggesting?

At this moment, users can select their servers from their server list; what is the difference between your idea and the current situation?

**Comment by trudyhood** [comment]
Sorry that i close this issue because we haven't heard anything from your side. Feel free to add your comment in this closed issue.

**Comment by JiJi85p** [comment]
Imagine that I have 5 differents Server set On Console. If I gave my Client a Access Token, They can share them with Others and more than 5 Clients can connect to my Network !
So giving any Client a Access Token for all servers is not my mean !

actually My Mean is giving an ability to Clients to Select and connect a Server between Available Server (Finland, Germany, USA , ... ) in anytime and by themselves

thanks a lot

**Comment by trudyhood** [comment]
We are working on implementing Ads interfaces. After that, our priority is to add the ability to select a region for a farm (Finland, Germany, USA, etc.).
