### ISSUE TITLE
how client can update server endpoint from a URL

### ISSUE THREAD

**Issue by SalimiHabib** [vpnhood/VpnHood#467]
hi

1. How can it possible to generate key that have new endpoint and remaining time for user ?
2. Also i want to know more about "G**enerate encrypted server token to client update server endpoint from a URL**"  it is an enhancement but i didn't know how to use it .

Thank you

**Comment by trudyhood** [comment]
Hi,
Do you use the Enterprise Access Manager or Built In  File Access Manager (command line)?
It would be easy via https://console.vpnhood.com/

**Comment by SalimiHabib** [comment]
It is  File Access Manager (command line) .

Also i have a question not related to this issue (sorry about it just time saving) ,  it seems MAUI is abandoned , does any plan to complete the project .

 thank you

**Comment by trudyhood** [comment]
To update the server endpoint from
1) Set ServerTokenUrl in the following link: 
https://github.com/vpnhood/VpnHood/wiki/VpnHood-Server-Configuration
2) Find the token from "storage\access\server-token\enc-server-token" and upload it to that URL. 

Now, every time you configure a new endpoint, the token will get updated, and you just need to upload the new token. Your clients will be updated automatically.

**Maui**
Feel free to open a new issue or discussion. By the way, VpnHood is the default UI, and Maui does nothing except its UI. So, it does help in this case; it just overhead and creates complexity. But still, it is not a big deal; the recent version is now compatible with Maui; you can just add the required nuggets and build the app via Maui. Let me if it doesn't work.

**Comment by SalimiHabib** [comment]
you are very fast 

thank you
