### ISSUE TITLE
after 1h server not work

### ISSUE THREAD

**Issue by RezZz13** [vpnhood/VpnHood#468]
hi why after 1 hour my server not work after connect
after install good work for 1h now after reconnect active but not data here ??

**Comment by trudyhood** [comment]
Hi, that's so weird. I can not remember we have anything regarding of 1 hour.
Do you use Enterprise access manage or File Access Manager?
Can you simulate the issue and give me an access to your server?
trudy@vpnhood.com

**Comment by RezZz13** [comment]
hi i send too you information
with this title (after 1h server not work)
