### ISSUE TITLE
How i connect to mi vpn? 

### ISSUE THREAD

**Issue by Keiser04** [vpnhood/VpnHood#475]
I open the server vpn in terminal, is give my public ip and port. now, i open the port but idk how i conecct

**Comment by trudyhood** [comment]
Do you use console.vpnhood.com?

**Comment by trudyhood** [comment]
You need to create accesskey using "gen" command.  
```sh
sudo /opt/VpnHoodServer/vhserver gen
```
Copy the access key and add it to the client configuration in the server section.

If you have already done this and are still experiencing issues, I will need more detailed information to assist you further. Please provide server and client logs. Let me know the steps you've taken and describe the specific problem you're encountering

**Comment by Keiser04** [comment]
> You need to create accesskey using "gen" command.
> 
> ```shell
> sudo /opt/VpnHoodServer/vhserver gen
> ```
> 
> Copy the access key and add it to the client configuration in the server section.
> 
> If you have already done this and are still experiencing issues, I will need more detailed information to assist you further. Please provide server and client logs. Let me know the steps you've taken and describe the specific problem you're encountering

in windows how?

**Comment by trudyhood** [comment]
> in windows how?

check this:
https://github.com/vpnhood/VpnHood/wiki/How-to-run-VpnHood-Server-on-Windows

**Comment by Keiser04** [comment]
> > in windows how?
> 
> check this: https://github.com/vpnhood/VpnHood/wiki/How-to-run-VpnHood-Server-on-Windows
I try whit the console but it not conects

"An error occurred during the connection attempt as the connected party did not respond properly after a period of time, or an error occurred in the established connection as the connected host has not been able to respond."
![image](https://github.com/vpnhood/VpnHood/assets/146493916/15ba8eb7-26f4-49d4-a14a-b1000c9d352b)

**Comment by Keiser04** [comment]
This are my ports open
![image](https://github.com/vpnhood/VpnHood/assets/146493916/e7862432-f06e-49b6-a133-f8e96b753855)

**Comment by Keiser04** [comment]
{"TypeName":"SocketException","TypeFullName":"System.Net.Sockets.SocketException","Message":"Intento de acceso a un socket no permitido por sus permisos de acceso.","Data":{"TcpEndPoint":"192.168.1.121:443","SocketErrorCode":"AccessDenied"}}

**Comment by trudyhood** [comment]
Socket Access Denied. You need to run VpnHoodServer as sudo or root access because you are trying to use port 443 which only sudo users can listen on them. Let me know if you solve this problem

**Comment by Keiser04** [comment]
> Socket Access Denied. You need to run VpnHoodServer as sudo or root access because you are trying to use port 443 which only sudo users can listen on them. Let me know if you solve this problem

ok so better i install on a virtualbox linux? because i dont have linux or i need to start somthign? because i install but nothing more on windows

**Comment by Keiser04** [comment]
> Socket Access Denied. You need to run VpnHoodServer as sudo or root access because you are trying to use port 443 which only sudo users can listen on them. Let me know if you solve this problem

Perfect whit ubuntu linux it works fine :)

**Comment by Keiser04** [comment]
nvm y try to reboot the ubuntu and now is not working. i need to reinstall everytime i open the server¿

**Comment by Keiser04** [comment]
![image](https://github.com/vpnhood/VpnHood/assets/146493916/750893a7-cc15-4de5-aa34-a98355dc6b7c)
@trudyhood but is active whitout problems

**Comment by Keiser04** [comment]
{"TypeName":"SocketException","TypeFullName":"System.Net.Sockets.SocketException","Message":"Invalid argument","Data":{"UdpEndPoint":"[fe80::a00:27ff:fe4d:5ced]:7533","SocketErrorCode":"InvalidArgument"}}

**Comment by trudyhood** [comment]
could you manage to solve the issue?
