### ISSUE TITLE
VpnHood.Client.Samples.MauiAppForm have problems

### ISSUE THREAD

**Issue by SalimiHabib** [vpnhood/VpnHood#479]
hi
as you remember in last issue you kindly updated samples to be compatible with MAUI platform .
fortunately core version works very good and fast and about form version we found 2 issue .
below nugets package all installed by nuget manager (no manual )

1. as below image shows it is not compatible with windows .
```

<TargetFrameworks>net8.0-android34.0</TargetFrameworks>
<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net8.0-windows10.0.22621.0</TargetFrameworks>

``` 
```

<PackageReference Include="VpnHood.Client.App" Version="3.3.475" />
<PackageReference Include="VpnHood.Client.App.Resources" Version="3.3.475" />


```
```

<ItemGroup Condition="'$(TargetFramework)' == 'net8.0-android34.0'">
<PackageReference Include="VpnHood.Client.App.Android.GooglePlay.Core">
<Version>3.3.475</Version>
</PackageReference>
<PackageReference Include="VpnHood.Client.App.Maui.Common">
<Version>3.3.475</Version>
</PackageReference>
</ItemGroup>

```

![image](https://github.com/vpnhood/VpnHood/assets/23046553/da8f324a-74cf-4754-8e96-185847241a61)7

2. in android , after getting permission (for first time only)  ,  client start to made a connection but takes to long and no connection can be made .
we also trying to connect to our server by below code after it not connected to vpnhood public service ,  but at the end it was same result and no connection .

```
var AccessKey = "vh://......."
var token = VpnHood.Common.Token.FromAccessKey( AccessKey );
var t = VpnHoodApp.Instance.ClientProfileService.ImportAccessKey(AccessKey); 
   if (VpnHoodApp.Instance.State.CanConnect)
       await VpnHoodApp.Instance.Connect(t.ClientProfileId);
```
thank you

**Comment by trudyhood** [comment]
I am not sure what went wrong with your Windows client, as it compiles and works on our Windows machines. Make sure you have installed latest Vistual Studio and SDK. 

> in android , after getting permission (for first time only) , client start to made a connection but takes to long and no connection can be made .

An application is attempting to extract a database of countries' IP addresses, which is approximately 10 MB in size. When attempting to initialize the database on an Android Virtual Machine for the first time, we have noticed that the process is quite slow especially in debug mode. However, we have not observed such a delay on a real Android device.

Let me know if you find any other reasons.
