### ISSUE TITLE
Get error when run gen command on commandline

### ISSUE THREAD

**Issue by asoMansoury** [vpnhood/VpnHood#485]
After  executing below command I got error.
I tunneled my server and I need to create a new token by command line based on the server I've  tunneled to redirect my traffic onto my original server.

sudo /opt/VpnHoodServer/vhserver gen
[22:23:29.7679] info: [0]
      Initializing ResetAccessManager. BaseUrl: https://access.vpnhood.com/
System.InvalidOperationException: Enumeration already finished.
   at System.SZGenericArrayEnumerator`1.get_Current()
   at McMaster.Extensions.CommandLineUtils.CommandLineProcessor.CommandArgumentEnumerator.get_Current()
   at McMaster.Extensions.CommandLineUtils.CommandLineProcessor.CommandArgumentEnumerator.MoveNext()
   at McMaster.Extensions.CommandLineUtils.CommandLineProcessor.ProcessCommandOrParameter(CommandOrParameterArgument arg)
   at McMaster.Extensions.CommandLineUtils.CommandLineProcessor.ProcessNext()
   at McMaster.Extensions.CommandLineUtils.CommandLineProcessor.Process()
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Parse(String[] args)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at VpnHood.Server.App.ServerApp.Start(String[] args) in C:\Users\Developer\source\repos\Vh\VpnHood\VpnHood.Server.App.Net\ServerApp.cs:line 290
   at VpnHood.Server.App.Program.Main(String[] args) in C:\Users\Developer\source\repos\Vh\VpnHood\VpnHood.Server.App.Net\Program.cs:line 10

**Comment by trudyhood** [comment]
It seems that you have set up VpnHoodServer with enterprise VpnHood Access Manager. If that's the case, you won't be able to use the "gen" command. Instead, you can create the token visually through the web UI by visiting https://console.vpnhood.com. There's also an API you can use.

![image](https://github.com/vpnhood/VpnHood/assets/72891124/c1f12f66-b8b0-45b2-ac7e-9035e8897c70)

**Comment by asoMansoury** [comment]
> It seems that you have set up VpnHoodServer with enterprise VpnHood Access Manager. If that's the case, you won't be able to use the "gen" command. Instead, you can create the token visually through the web UI by visiting https://console.vpnhood.com. There's also an API you can use.
> 
> ![image](https://private-user-images.githubusercontent.com/72891124/314759357-c1f12f66-b8b0-45b2-ac7e-9035e8897c70.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5NzY0NjEsIm5iZiI6MTcxMDk3NjE2MSwicGF0aCI6Ii83Mjg5MTEyNC8zMTQ3NTkzNTctYzFmMTJmNjYtYjhiMC00NWIyLWFjN2UtOTAzNWU4ODk3YzcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIwVDIzMDkyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxMmRlYzVkYmVhODMzN2MxZjU0ZWI4YjJiNmE5ZjBlYzZkYjczNTQ4YjNjNzc0OTk5N2ZkY2UxMWRiOTBkNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KSDEh2ShR3s1m1_Wd9An5l9-3O0Kvzc2k18PraNRhQw)

Do you have any documents for getting accesa through the Api?
I need to connect my access manager to create and remove account theough it?

**Comment by trudyhood** [comment]
I understand that you need some guidance on accessing a document. Unfortunately, there is no document available, but it can be easily accessed through Swagger or by using the AccessServer Nuget. To do this, please go to the team item in Access Manager and create a bot. This will provide you with an API key that you can use to call the AccessTokens API. The naming convention is straightforward, so I'm sure that you won't have any trouble accessing what you need. Just ask me if you have any issue.

here is the nugget:
https://www.nuget.org/packages/VpnHood.AccessServer.Api/

Here is the swagger:
https://api.vpnhood.com/swagger/index.html

**Comment by asoMansoury** [comment]
> I understand that you need some guidance on accessing a document. Unfortunately, there is no document available, but it can be easily accessed through Swagger or by using the AccessServer Nuget. To do this, please go to the team item in Access Manager and create a bot. This will provide you with an API key that you can use to call the AccessTokens API. The naming convention is straightforward, so I'm sure that you won't have any trouble accessing what you need. Just ask me if you have any issue.
> 
> here is the nugget: https://www.nuget.org/packages/VpnHood.AccessServer.Api/
> 
> Here is the swagger: https://api.vpnhood.com/swagger/index.html

Its so interesting, so I can use that nugget library to connect my access server and manage my clients by C#?
Can I use those apis in node.js too?

**Comment by trudyhood** [comment]
> Its so interesting, so I can use that nugget library to connect my access server and manage my clients by C#?
Can I use those apis in node.js too?

Yes, indeed.

> Can I use those apis in node.js too?

I understand that you are looking for a NodeJS module for our APIs, but unfortunately, we have not yet created one. However, you can still use the swagger and generate the http request manually in NodeJS. We can generate the TS stub for you if you prefer a TS file.

⚠️  I want you to be aware that we regularly update these APIs without ensuring backward compatibility, so you need to monitor the updates to avoid any issues.

**Comment by asoMansoury** [comment]
> I understand that you need some guidance on accessing a document. Unfortunately, there is no document available, but it can be easily accessed through Swagger or by using the AccessServer Nuget. To do this, please go to the team item in Access Manager and create a bot. This will provide you with an API key that you can use to call the AccessTokens API. The naming convention is straightforward, so I'm sure that you won't have any trouble accessing what you need. Just ask me if you have any issue.
> 
> here is the nugget: https://www.nuget.org/packages/VpnHood.AccessServer.Api/
> 
> Here is the swagger: https://api.vpnhood.com/swagger/index.html

Its so interesting, so I can use that nugget library to connect my access server and manage my clients by C#?
Can I use those apis in node.js too?

> > Its so interesting, so I can use that nugget library to connect my access server and manage my clients by C#?
> > Can I use those apis in node.js too?
> 
> Yes, indeed.
> 
> > Can I use those apis in node.js too?
> 
> I understand that you are looking for a NodeJS module for our APIs, but unfortunately, we have not yet created one. However, you can still use the swagger and generate the http request manually in NodeJS. We can generate the TS stub for you if you prefer a TS file.
> 
> ⚠️ I want you to be aware that we regularly update these APIs without ensuring backward compatibility, so you need to monitor the updates to avoid any issues.

Yes, actually by providing ts file it would be a great favor to me . Thanks in advance.

**Comment by bobvhood** [comment]
@asoMansoury Hi. I have generated the Access Server API TS file using NSWAG. please not that this API are subject to change.
@trudyhood We need to find the best solution to keep it update such as npm modules or yarn. I am not familiar with nodeJS modules.

[VpnHood.AccessServer.Api.zip](https://github.com/vpnhood/VpnHood/files/14692286/VpnHood.AccessServer.Api.zip)
