### ISSUE TITLE
Setup the  PublicEndPoints 

### ISSUE THREAD

**Issue by SalimiHabib** [vpnhood/VpnHood#487]
hi
what is the point of having collection on `"PublicEndPoints": [ "x,x,x,x :443" ,"y,y,y,y:443" ]` , it just connect to last one .

**Comment by trudyhood** [comment]
One of the PublicEndPoints is selected at random. Make sure the client version is up to date. 
If you use Enterprise Access Manager, the user will be redirected to the server with the least load, regardless of the public endpoint specified in the token.

**Comment by SalimiHabib** [comment]
It seems by trying all of them from client side ,  there will be resiliency  for connection  , or may be i misunderstood the workflow  .

**Comment by trudyhood** [comment]
> It seems by trying all of them from client side , there will be resiliency for connection , or may be i misunderstood the workflow .

Sorry I couldn't understand that. Would you explain it more.

**Comment by SalimiHabib** [comment]
server can have multiple ip(s) to be use by client to connect , access token can have all of ip(s) included and client will try all of them until one of them will be connected  , in this form censorship will be weakening  and client side will have kind of load balancing .

**Comment by trudyhood** [comment]
I know that policy. It may put stress to the rest of servers. However I think we need to implement it. #490

**Comment by trudyhood** [comment]
it is done by version 456
