### ISSUE TITLE
Add flag for installing to a different port than 443

### ISSUE THREAD

**Issue by mfat** [vpnhood/VpnHood#494]
The configuration file is too complicated. Please add a switch in the install script so that i can install to another port.

**Comment by trudyhood** [comment]
It is not in the install script. You need to use appsettings.json 
I recommend you check the VpnHood Access Server, too, for more enterprise features.
[http](https://github.com/vpnhood/VpnHood/wiki/VpnHood-Access-Server)

duplicate of #495
