### ISSUE TITLE
Which lines should I change to run server on port 8443?

### ISSUE THREAD

**Issue by mfat** [vpnhood/VpnHood#495]
Which parts in appsettings.json should be edited to change port to 8443?

**Comment by trudyhood** [comment]
Hi,
Please check this: https://github.com/vpnhood/VpnHood/wiki/VpnHood-Server-Configuration
![image](https://github.com/vpnhood/VpnHood/assets/72891124/41c3e824-24ec-45d5-b439-be37298944ea)

You can also configure using VpnHood Access Manager through UI and get much more:
[http](https://github.com/vpnhood/VpnHood/wiki/VpnHood-Access-Server)
