### ISSUE TITLE
Change IP to DomainName

### ISSUE THREAD

**Issue by asoMansoury** [vpnhood/VpnHood#499]
Hey Trudy,
Hope you are doing very well.
Are you able to enable instead of using IP address in below section let us to enter our server domain name. As you surely know for bypassing filtering this is another critical feature, specially when we want to tunneling traffic from inside of blocking countries.
Thanks.

![image](https://github.com/vpnhood/VpnHood/assets/14541559/1de9e9ff-7eb3-4fca-ba4d-37fa54d65264)

**Comment by trudyhood** [comment]
Hi,
Any servers need an IP address to listen; they cannot listen to a domain. If you need to connect via a domain, go to your Server Farm, select "Own Domain," and choose your domain for a certificate. Just so you know, changing the certificate will cause all previous tokens to be lost.

In this case, you can leave the IP in the server section in Autoconfigure.

![image](https://github.com/vpnhood/VpnHood/assets/72891124/a8dd3ba3-c253-4798-b5f9-80e7d41802b2)

Let me know if it is not what you need.
