### ISSUE TITLE
We couldn't create the data directory Error in running VpnHood

### ISSUE THREAD

**Issue by JiJi85p** [vpnhood/VpnHood#500]
hey everyone
I got this error message when I Tried Run VpnHood App in Windows 10 whith 3nd level Of UAC (User Account Countrol) :

_> We couldn't create the data directory  Microsoft Edge can't read and write to its data directory_

How Can I Handel it, please help me

**Comment by trudyhood** [comment]
Unfortunately, I couldn't reproduce this issue. Do you know if the UAC prompts before running VpnHood? Have you installed VpnHppd by the official installer?

**Comment by JiJi85p** [comment]
Yes, I've done.
I fixed it by reducing security level of UAC.

**Comment by trudyhood** [comment]
I couldn't find any issues on Windows 11 after increasing UAC. What is your Client Version?

**Comment by JiJi85p** [comment]
Actually the problem was login into windows by guest user and not administrator.
I said to my client to login by Administrator instead of guest user and it fixed.

**Comment by trudyhood** [comment]
Good. VpnHood on windows need the admin privilege.
