### ISSUE TITLE
Error when calling PATCH for update a token

### ISSUE THREAD

**Issue by asoMansoury** [vpnhood/VpnHood#504]
https://api.vpnhood.com/api/v1/projects/{projectID}/access-tokens/{tokenId}
{
    "expirationTime": { "value": "2026-12-06T09:29:10" },
    "isEnabled": { "value": true }
}

I called above method for update my token expiration date to below date, after it returns me below result: 
{
    "projectId": "{projectId}",
    "accessTokenId": "{accessTokenId}",
    "accessTokenName": "agnt102",
    "supportCode": 1077,
    "serverFarmId": "{serverFarmId}",
    "serverFarmName": "V1",
    "maxTraffic": 0,
    "lifetime": 0,
    "maxDevice": 1,
    "firstUsedTime": "2024-04-05T03:35:51",
    "lastUsedTime": "2024-04-05T03:41:55",
    "url": "string",
    "isPublic": true,
    "isEnabled": true,
    "expirationTime": "2026-12-06T09:29:10",
    "createdTime": "2024-04-05T03:34:42",
    "modifiedTime": "2024-04-05T03:42:09.595843Z"
}

It says my update has been succeed but when I connect to the user, in client application I saw now changes has been happened.

Best Regards

**Comment by trudyhood** [comment]
Sorry, I can't understand the issue! Please let me know what did happen and what did you expect.

**Comment by asoMansoury** [comment]
> Sorry, I can't understand the issue! Please let me know what did happen and what did you expect.

The problem is that in above example I wanted to change token expiration date, after calling PATCH method the API returned me back that operation was successful and showed me the new expiration date has been changed.
but when I connect to that user via Vpnhood client app, I saw, the expiration date hasn't been changed.

**Comment by trudyhood** [comment]
Please send me your console project ID and the access key, so I can check it out
trudy@vpnhood.com

**Comment by asoMansoury** [comment]
Hello Trudy
ProjectID : c750b322-ee70-424e-9f5e-5bd257fd14e7
access key 3f175ff1-4a0a-4975-962c-c1dd3cf4b19f

Best regards.

**Comment by trudyhood** [comment]
I can see you set isPublic property to true; you need to set it to false. create a new  one and let me know if the problem persists

**Comment by petervhood** [comment]
I have noticed the problem, I will notify you in the same way when the problem is resolved.

**Comment by asoMansoury** [comment]
> I have noticed the problem, I will notify you in the same way when the problem is resolved.

Thank you so much, do you have any updates in regard of this issue?

**Comment by trudyhood** [comment]
we will soon

**Comment by bobvhood** [comment]
We have resolved the issue you reported. Please check it out and let us know if you encounter any further problems.

**Comment by trudyhood** [comment]
Hi @asoMansoury 
We resolved this issue last week; please check it out and let us know if the problem persists. Please add to this issue if the problem persists.

**Comment by asoMansoury** [comment]
> Hi @asoMansoury We resolved this issue last week; please check it out and let us know if the problem persists. Please add to this issue if the problem persists.

It is been resolved, thanks a lot.
