### ISSUE TITLE
Forced update is evil

### ISSUE THREAD

**Issue by Onair-santa** [vpnhood/VpnHood#506]
![zqeiJqtxSm](https://github.com/vpnhood/VpnHood/assets/42511409/114ac642-6e22-471e-86c7-f2b6de5ce33d)

I have already written about this many times; with your forced update, you completely break the operation of all computers on the network for a long time. We use 448 server and 316 application in our work; these are the most reliable and acceptable options for us. Everything newer is much worse and we are not satisfied. We are grateful for your work and are ready to donate. But why force constant updates and try to stop our work? How to make sure there are NEVER updates. We have everything set up and we don’t need updates, and the application version in a window, not like 316, also doesn’t suit us because everywhere in the system this window is registered in processes as vpnhood and everyone around knows that we have a VPN running, and this is prohibited. There is no such thing in 316. Please tell me how to make it in the settings so that there are never forced updates to the 316th version and there is no yellow window and shutdowns? Thank you. I'll send a donation soon

**Comment by Onair-santa** [comment]
In many countries, VPN is prohibited and a private network exists to have its own independent network. And we don’t need everyone to know that our office works via VPN. Ideally, there should be no opening windows at all and just one tray icon with the ability to connect. Tell me, can you make an option without the blue application window and just one icon near the clock? One Connect button is enough, the rest of the settings are in the config. Then we can update everything everywhere and without warning. Is this possible? Write your USDT address for donation and I will pay for your work. Much appreciated if you can help with this

**Comment by trudyhood** [comment]
Hi Onair,

I understand your concerns, but I am afraid to let you know that you will need a custom solution. It's unclear which features of version 316 appealed to you, as it is now outdated and unsupported. While I acknowledge your considerations, you will need to compile your own version of VpnHood, as the current mainstream release does not fulfill your requirements.

VpnHood is an open-source software distributed under the LGPL license. You can download and recompile it with your own branding. Our team can create a custom app for you however you need to contact support@vpnhood.com
