### ISSUE TITLE
 I have received the stop command!

### ISSUE THREAD

**Issue by rkarimabadi** [vpnhood/VpnHood#519]
i have client ver 4.3.485.109 and server ver 4.3.485.0.
when client attempts to connect, these writes to server terminal:
2024/04/21 00:57:12.744 | Info |  | Server 
 MinWorkerThreads: 1, MinCompletionPortThreads: 30  

2024/04/21 00:57:12.744 | Info |  | Server 
 MaxWorkerThreads: 32767, MaxCompletionPortThreads: 65535  

2024/04/21 00:57:12.764 | Info |  | Server 
 Starting ServerHost...  

2024/04/21 00:57:12.765 | Info |  | Server 
 Start listening on UdpEndPoint: 0.0.0.0:4258  

2024/04/21 00:57:12.770 | Info |  | Server 
 Start listening on UdpEndPoint: :::4258  

2024/04/21 00:57:12.770 | Info |  | Server 
 Start listening on TcpEndPoint: 0.0.0.0:443  

2024/04/21 00:57:12.773 | Info |  | Server 
 Start listening on TcpEndPoint: :::443  

2024/04/21 00:57:12.773 | Info |  | Server 
 Server is ready!  

2024/04/21 00:57:18.994 | Info |  |  
 I have received the stop command!  

2024/04/21 00:57:19.010 | Info |  | Server 
 Shutting down...  

2024/04/21 00:57:19.018 | Info |  | Server 
 TCP Listener has been stopped. LocalEp: 0.0.0.0:443  

2024/04/21 00:57:19.018 | Info |  | Server 
 TCP Listener has been stopped. LocalEp: :::443  

2024/04/21 00:57:19.020 | Info |  | Server 
 Bye Bye!

**Comment by trudyhood** [comment]
Hi, 
Please go to installation dir and find and delete "appcommand" file. It is in "storage" folder such as
/opt/VpnHoodServer/storage

Let me know if the issue persists.
