### ISSUE TITLE
How i install the server using the zip in windows?

### ISSUE THREAD

**Issue by Keiser04** [vpnhood/VpnHood#520]
because ubuntu sometimes is working and anothers not

**Comment by Keiser04** [comment]
![image](https://github.com/vpnhood/VpnHood/assets/146493916/c4bbde6b-b6e3-429e-bb47-9f23691e4c13)
i try to intall on ubuntu and i dont have public ip idk

**Comment by trudyhood** [comment]
please give me the server log
/opt/VpnHoodServer/storage/logs/server.log

**Comment by Keiser04** [comment]
a@a:~$ cat /opt/VpnHoodServer/storage/logs/server.log
2024-04-22 20:05:15.0294 | Info |  | Server
 Module: VpnHood.Server, Version=4.3.485.0, Culture=neutral, PublicKeyToken=null

2024-04-22 20:05:15.0569 | Info |  | Server
 OS: Ubuntu 22.04.4 LTS, X64, TotalMemory: 1 GB, Logical Cores: 2

2024-04-22 20:05:15.0606 | Info |  | Server
 DefaultTcpKernelSentBufferSize: 16384, DefaultTcpKernelReceiveBufferSize: 131072

2024-04-22 20:05:15.0983 | Info |  | Server
 Configuring by the Access Manager...

2024-04-22 20:05:16.2349 | Info |  | Server
 Public IPv4: <null>, Public IPv6: 2a01:***:0007, IsV6Supported: True

2024-04-22 20:05:17.1674 | Info |  | Server
 RemoteConfig: {
  "Tracking": {
    "TrackClientIp": true,
    "TrackLocalPort": true,
    "TrackDestinationIp": true,
    "TrackDestinationPort": true,
    "TrackUdp": true,
    "TrackTcp": true,
    "TrackIcmp": true
  },
  "Session": {
    "Timeout": "01:00:00",
    "UdpTimeout": "00:01:00",
    "TcpTimeout": "00:15:00",
    "IcmpTimeout": "00:00:30",
    "SyncInterval": "00:20:00",
    "SyncCacheSize": 200000000,
    "MaxDatagramChannelCount": 8,
    "MaxUdpClientCount": 500,
    "MaxIcmpClientCount": 20,
    "TcpBufferSize": 8192,
    "TcpKernelSendBufferSize": null,
    "TcpKernelReceiveBufferSize": null,
    "TcpConnectTimeout": "00:00:30",
    "TcpReuseTimeout": "00:00:40",
    "MaxTcpConnectWaitCount": 500,
    "MaxTcpChannelCount": 1000,
    "NetScanLimit": null,
    "NetScanTimeout": null,
    "UseUdpProxy2": false
  },
  "NetFilter": {
    "IncludeLocalNetwork": false,
    "PacketCaptureIncludeIpRanges": null,
    "PacketCaptureExcludeIpRanges": null,
    "IncludeIpRanges": null,
    "ExcludeIpRanges": null,
    "BlockIpV6": false
  },
  "TcpEndPoints": ["***"]:443"
  ],
  "UdpEndPoints": ["***"]:3626"
  ],
  "DnsServers": [
    "8.8.8.8",
    "8.4.4.8",
    "1:4860:4860::8888",
    "2001:4860:4860::8844"
  ],
  "UpdateStatusInterval": "00:01:00",
  "LogAnonymizer": true,
  "ServerSecret": "***",
  "ConfigCode": "30cbddaf-c1e1-4b02-8fb8-3a7883aac870",
  "MinCompletionPortThreads": null,
  "MaxCompletionPortThreads": null,
  "DnsChallenge": null,
  "Certificates": [
    {
      "CommonName": "my.qowaecoqe.com",
      "RawData": "***"}
  ]
}

2024-04-22 20:05:17.1674 | Info |  | Server
 MinWorkerThreads: 2, MinCompletionPortThreads: 30

2024-04-22 20:05:17.1674 | Info |  | Server
 MaxWorkerThreads: 32767, MaxCompletionPortThreads: 65535

2024-04-22 20:05:17.2039 | Info |  | Server
 Starting ServerHost...

2024-04-22 20:05:17.2060 | Info |  | Server
 Start listening on UdpEndPoint: 192.*.*.174:3626

2024-04-22 20:05:17.2103 | Info |  | Server
 Start listening on UdpEndPoint: 2a01:***:0007:3626

2024-04-22 20:05:17.2103 | Info |  | Server
 Start listening on TcpEndPoint: 192.*.*.174:443

2024-04-22 20:05:17.2144 | Info |  | Server
 Start listening on TcpEndPoint: 2a01:***:0007:443

2024-04-22 20:05:17.2144 | Info |  | Server
 Server is ready!

2024-04-22 20:16:38.0142 | Info | Session | Server => RemoteEp: 2a01:***:633a:56930
 New session has been created. SessionId: 14476032

2024-04-22 20:16:38.0142 | Info | Session | Server => RemoteEp: 2a01:***:633a:56930
 New Session. SessionId: 14476032, Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 Edg/122.0.0.0

2024-04-22 20:16:38.0142 | Info | SessionTrack | Server => RemoteEp: 2a01:***:633a:56930
 SessionId: 14476032    New     TokenId: **-ac15-02322315f2c1   ClientCount: 0  ClientId: **-9bfa-a041726c7ffc  ClientIp: 2a01:***:633a Version: 3.3.470       OS: Windows NT 10.0

2024-04-22 20:17:24.9823 | Info | SessionTrack | Server => RemoteEp: 2a01:***:633a:57060 => SessionId: 14476032
 SessionId: 14476032    Close   Actor: Cleanup  SuppressBy: None        ErrorCode: Ok                   Message: None

**Comment by trudyhood** [comment]
It looks like it is working; Please describe the issue on this server.

**Comment by Keiser04** [comment]
I'll try again tomorrow. I remember something about not having a connection or something like that. something with the network.

**Comment by trudyhood** [comment]
okay please reopen this issue if you find that

**Comment by Keiser04** [comment]
in my lan it works but out not

**Comment by Keiser04** [comment]
weit i open the issue

**Comment by trudyhood** [comment]
If you have additional information to add to a closed issue, please continue to comment on it. I will reopen the issue.
