### ISSUE TITLE
Android build signature changed?

### ISSUE THREAD

**Issue by JonnyTech** [vpnhood/VpnHood#521]
I am trying to update using `VpnHoodClient-android-web.apk` and am getting an error. Has the build signature changed between v4.3.485 and v4.3.492 or is there another build that I should be installing? Note that I do not use any Google services and always download from the website or fdroid.

**Comment by trudyhood** [comment]
Unfortunately, we discovered that the previous build was using the wrong certificate, and we had to change it. We apologize for the inconvenience. Please uninstall the previous build before installing the new one. 😞
