### ISSUE TITLE
token for older clients

### ISSUE THREAD

**Issue by rkarimabadi** [vpnhood/VpnHood#528]
I installed vpnhood server that managed with console.vpnhood.com, but token that generate with console panel only work with newer client.
i use vpnhood client ver 3.0.416, and token don't work on that. is any solution to generate token for old client like "gen" switch in standalone mode?

**Comment by trudyhood** [comment]
Sorry, no. It has been removed from new servers too and you will not be able to generate v3 tokens with gen on new servers. Soon new client will not be able to read v3 tokens too.

VpnHood is a very active project and  we can not let old code make us slow. Please update the clients before it get too late.
