### ISSUE TITLE
Unable to circumvent Iran smart filtering system

### ISSUE THREAD

**Issue by hamednasery** [vpnhood/VpnHood#529]
Hi guys and thanks for this great vpn solution.  I installed it on my own Netherland vps server and used it with both win and android clients inside iran for my personal use without any problem.i didn't share it with anyone, just me and two devices. But it took about 20 days that iran smart filtering system (or whatever you call it) recognised it and banned the ip address! I got really surprised. It might be kind of traffic pattern recognition or something. For servers inside iran there is a restriction on download/upload traffic proportion of 1 to 10 , but not for foreign servers.i rally love this project and I used it happily for a while. Any ideas or clues? It seems that circumventing advanced filtering systems is getting really complex.

**Comment by asoMansoury** [comment]
@trudyhood 
Hi Trudy, Have you solved the problem with patch method to revoke user expiration by Api.
Im now sure do you remember the problem or not, just for remind you, 1month ago I tried to extend expiration time of a token by your Path api, the problem was that when I call the api i got successful response but when I checked my token on my client app, I saw nothing has been changed and the expired time still is the same that was before of calling Patch Api.
It is a really critical problem.
Thanks alot

**Comment by trudyhood** [comment]
Thank you for reaching out and sharing your experience. It's surprising to hear that your server was blocked after 20 days of use, VpnHood is designed to operate like a web server and does not employ any specific patterns. We are not sure how they mark a server as a VPN, I believe they might mark many other ordinary websites as VPN server too.  

Let's take this discussion to our forum to investigate how these detections might be happening. We're eager to hear more thoughts and insights on this matter, and we’re here to tune in and apply any required changes to improve it.

moved #530

**Comment by bobvhood** [comment]
Please ensure that your server is configured with dual IP addresses. The gateway IP address must be distinct from the VPN server IP address.

**Comment by bobvhood** [comment]
I'm not certain how your server detection works, but it's important to note that some countries employ local services to identify VPN usage. For instance, when you access local services through VPN like banking, social networks, app stores, or tax systems, these platforms might detect and flag your incoming IP (server IP) as a VPN if it appears you are connecting from a foreign country

To counter this, I recommend setting up a dual IP configuration on your server. By ensuring that the IP used for the VPN is different from the gateway IP, you can prevent these services from effectively blocking your VPN connection. This strategy makes the common practice of blocking the secondary IP ineffective.

Although consider about having valid certificate and valid domain. Still I am not sure is it effective or not.

If you have more information please share it with us.
