### ISSUE TITLE
vpn-hood has restriction in some area

### ISSUE THREAD

**Issue by SalimiHabib** [vpnhood/VpnHood#539]
hi
even with vpn-hood  there is restriction on inbound connection toward Iran.
may be the same in  Russia and China  ... 

test is done using of vpn-hood server docker last version .

is there any solution for this problem ?

thank you

 
![image](https://github.com/vpnhood/VpnHood/assets/23046553/c38e2849-5d3e-4ede-b8c8-47e59bdfa8ff)

**Comment by trudyhood** [comment]
It appears that iranemp.ir has blocked your server IP. Using a VPN won't resolve this issue; you'll need to set up a VPN server from a different region. If you are in the same country (Iran), simply enable the 'Exclude my country' option so your local traffic does not use the VPN.

**Comment by SalimiHabib** [comment]
this is result of a vpnhood server(docker) that is connected from out side of iran by client .
client is not in iran.
also if you point to NetFilter:ExcludeLocalNetwork option in server it seems it block the connection for client to iran , this is explanation in wiki

"If true, the server's local network will be unreachable to clients."

**Comment by trudyhood** [comment]
OK, let me say what I got and fix myself. 

First, ExcludeLocalNetwork has been renamed to IncludeLocalNetwork now; thank you for reporting, so I fixed the document.  It is for LAN, such as home or company, not for the country you are in.

As far as I understood, if a user tries to connect to Iran from another country and just wants to use a VPN for Iranian service, he doesn't want to connect to Google or other global services via a VPN server. We already support this scenario; what you need is to select which country to include/exclude from your network, but unfortunately, we have not created an interface for it.
Here is similar issue: #310

**Comment by trudyhood** [comment]
Move to issue #540

**Comment by SalimiHabib** [comment]
Iran filtering is in both way !

1-user try to connect to Iranian service from outside of Iran 
2-user try to connect to outside of Iran service  from Iran  

our conversation is in type 1 
solution is imitate Iranian IP using vpnhood server that installed in Iran and connect to that server from outside of Iran  to get the result .

but its not works

**Comment by trudyhood** [comment]
So i got it right. if it doesn't work it means the service has blocked your iranian server and recognize it as a hosting service. try to install VpnHood server on another iranian hosting or if possible install it on a home user machine.
