### ISSUE TITLE
Needs MAUI SDK

### ISSUE THREAD

**Issue by miladxandi** [vpnhood/VpnHood#542]
What is your plan to develop an MAUI SDK instead of WInDivert & Droid ones?!

**Comment by trudyhood** [comment]
Hi and thank you for your interest in VpnHood!

MAUI has already been implemented, and you can find a variety of samples here:
https://github.com/vpnhood/VpnHood.Client.Samples

MAUI primarily facilitates the development of cross-platform apps focusing on UI and basic mobile functionalities but currently does not support VPN services across multiple platforms. If you're looking to develop a MAUI app, you will need to implement the IPacketCapture using ".net for iOS" and integrate it into your MAUI project. Please review the project linked below and let us know if you are available to create the iOS module. Your contribution would be greatly appreciated by the VpnHood community:
https://github.com/vpnhood/VpnHood/tree/main/VpnHood.Client.Device.Android

We look forward to possibly collaborating with you!
