### ISSUE TITLE
Client disconnect in random 

### ISSUE THREAD

**Issue by SalimiHabib** [vpnhood/VpnHood#545]
hi 
After checking new installed server on ubuntu with  `"IsDiagnoseMode": true`   flag    ,   below is last error on client disconnect .
how to solve it  ?
thank you 

` Exception of type 'VpnHood.Server.Exceptions.ServerSessionException' was thrown. SessionId: 1, RequestId: 14de30fa-22cb-4e0c-b926-56a8cd80ffe3:server, ClientIp: 176.*.*.196, TokenId: <null>, SessionErrorCode: SessionClosed VpnHood.Server.Exceptions.ServerSessionException Exception of type 'VpnHood.Server.Exceptions.ServerSessionException' was thrown.`

```
2024/05/16 04:25:51.524 | Info | SessionTrack | Server => SessionId: 1
 SessionId: 1   Close   Actor: Access   SuppressBy: None        ErrorCode: SessionClosed        Message: None
```

**Comment by trudyhood** [comment]
I am wondering why TokenId is null. However, this does not give much help. What is your server & client version?

**Comment by SalimiHabib** [comment]
@trudyhood thank you so much 
it is a test project and i will continue it , in next available time 
sorry 
and thank you again  for your time
