### ISSUE TITLE
Tunneling

### ISSUE THREAD

**Issue by AhmadiHosein** [vpnhood/VpnHood#547]
Hi vpnhood creators!
i have a 2 ubuntu vps and i want to tunnel between these two  i Forwarded 443 tcp port and installed vpnhood server on dest vps
but i when changing access points to origin server getting some errors!
i saw the Discussion about this Issue and i go step by step but again i get this errors ! (I am not fluent in English)
![image](https://github.com/vpnhood/VpnHood/assets/72891124/104957c3-999f-4463-b300-e75cfbea47a5)

**Comment by trudyhood** [comment]
Sorry, I think I can't understand what exactly you need to do. However, if 87.x.x.131 is your forwarder, you need set IsListen to No like this:

VpnHoodServer   Ip:**x.x.x.x**   443  Mode: **Private** IsListen:**Yes**
Forwarder            Ip:**x.x.x.x**   443  Mode: **PublicInToken** IsListen:**No**

Let me know if it is what you need.
