### ISSUE TITLE
[Question] UDP through Tunnel

### ISSUE THREAD

**Issue by karnilamit** [vpnhood/VpnHood#56]
Hi,

I was wondering how UDP traffic is handled on the Tunnel? I am currently using TcpMode which means all the UDP traffic is sent through the TcpDatagramChannel. However on the server-side how does it handle proxying of these UDP packets to the actual resource (since in UDP there is no session per see). Does the server open a random port on which the data is sent to the actual server and closes it after a specific timeout? Appreciate some more details on this.

Same for ICMP, how is it handled.

Thanks.

**Comment by trudyhood** [comment]
**Does the server open a random port on which the data is sent to the actual server and closes it after a specific timeout?** Yes.
The internal VpnHood NAT, assigns a UDP and delegates the data to and back like a proxy.
Same for ICMP Ping, a proxy assigned for each session that does the delegation. Please note that only ICMP echo (PING) is supported by VpnHood and it discards other ICMP packets.
Feel free to ask your questions in Discussion section
https://github.com/vpnhood/VpnHood/discussions
