### ISSUE TITLE
0 Up/Down after Being Connected for a While

### ISSUE THREAD

**Issue by AmirHosseinCV** [vpnhood/VpnHood#575]
Recently, some of my users have been facing an issue where they experience 0 up/down while connected to the VPN. This problem occurs after a random amount of time being connected to the server, ranging from a few minutes to an hour. What could be the cause of this behavior? I have been unable to reproduce the issue myself.

**Comment by trudyhood** [comment]
It is very difficult to diagnose. We can not find the issue as we are unable to  produce problem too. let us know if you find a way how to reproduce problem.

**Comment by trudyhood** [comment]
I think we have fixed this issue (Atleast same issue for many users), and we hope it will be solved by our next release
