### ISSUE TITLE
Can't connect to self-hosted VPN

### ISSUE THREAD

**Issue by Reviver2116** [vpnhood/VpnHood#578]
So I have to add a disclaimer, I'm not very good at this. I can follow guides to create VPNs, but I have not found anything on why I can no longer connect to my server now. I have attached the log.

The log seems to indicate that everything is fine up until some IOException. 

The server is working and the IP is not blocked, I can SSH into it and access it via other means as well.

Any help is appreciated.
[log.txt](https://github.com/user-attachments/files/16041799/log.txt)

**Comment by trudyhood** [comment]
It sounds like your IP address in the generated token points to a port or an IP address to which no server is listening.
You can send me a token if you are interested: trudy@vpnhood.com
