### ISSUE TITLE
Questions about store-api

### ISSUE THREAD

**Issue by demooooooo** [vpnhood/VpnHood#585]
I noticed that the interface requested by the **VpnHood.Client.App.Android.Connect** app is store-api.vpnhood.com, and I understand that the content of this interface satisfies independent operation. But I have a question now.
**1: If my paid package is purchased based on the length of service, like a month, a quarter or a year. will the store-api interface fulfill that?
2: store-api I didn't find a place where I can write to my own private server AccessTokens. Can this interface interoperate with my server AccessTokens data in VpnHood Access Manager.
3: Or my above idea can't be realized by store-api, I have to implement the corresponding interface logic by myself to run my own app.**

**Comment by trudyhood** [comment]
Hi, The VpnHood Store is a service that performs all the required User Accounting tasks. It uses VpnHood Access Manager to create access tokens and provides User Service and billing services, such as payment and subscription, including Google Play Billing. 
We currently use it for VpnHood CONNECT, and we plan to host third parties in the future; it supports all the features you requested, but unfortunately, it is not ready for public use. @petervhood may provide you with more information.

Indeed, you can follow the interface and build your own accounting service.

**Comment by petervhood** [comment]
Hi @demooooooo , I can prepare a preliminary version tailored to your specific needs. If you're interested, please feel free to contact me at peter@vpnhood.com.
