### ISSUE TITLE
json length

### ISSUE THREAD

**Issue by alonelove7** [vpnhood/VpnHood#586]
Hello
issues/323
i used the last version but i got this error
json length is too big!It should be less than 65535 bytes ut was 1347703880

**Comment by trudyhood** [comment]
What is the client version and the server version you connect to?

**Comment by alonelove7** [comment]
Windows
v4.5.535

**Comment by alonelove7** [comment]
server version is 4.5.522
but it choose by console.vpnhood.com

**Comment by trudyhood** [comment]
Can you send me your VpnHood access key? trudy@vpnhood.com

**Comment by alonelove7** [comment]
i created  a new server with new farm it's worked now
thanks

**Comment by trudyhood** [comment]
Perhaps you just needed to get a new access token
