### ISSUE TITLE
Hide the server behind a web page

### ISSUE THREAD

**Issue by StSav012** [vpnhood/VpnHood#596]
Hello. Is there a way to show a web page at port 443 when a browser accesses the server? This would hide the server application from active probing.

**Comment by trudyhood** [comment]
I understand what you're asking for, but these days it's not standard practice for many common websites to operate the way you're suggesting. Websites typically have separate domains or even IP addresses for their member accounts. For example, 

- www.website.com
- admin.website.com
- api.mywebsite.com

Sites like api.mywebsite.com and admin.website.com always return 401 (User not authenticated), which is the same behavior that VpnHood exhibits. admin.website.com might have a URL that redirects to the login page. If you want to make your site look legitimate to human eyes, simply publish a few web pages on your www subdomain (www.yourwebsite.com). Let VpnHood operate on another subdomain and return 401 for unknown requests, as I described above. This approach makes your site appear and function 100% like a normal website.
