### ISSUE TITLE
Multiple Server

### ISSUE THREAD

**Issue by Gj4meZ** [vpnhood/VpnHood#598]
Hi i just installed vpnhood now and im just testing it 
i add Two Different servers 
and when i want to add user to Specific Server 
For Example 

Server 1 - 20 User 
Server 2 - 20 User 

when im Creating my User I dont see Anything for it 
To Select my User Server its just use the First Server i Added 
im using Your Web Manager for users

**Comment by trudyhood** [comment]
## Built-in File Access Manager**
If you use the built-in file access manager, you must create 20 tokens for each user on each server. The tokens are not managed and are isolated from each other.

## VpnHood Access Manager
To set up multiple servers, you need to create two separate server farms. Each farm can have many servers, but in your case, each farm has only one server. Then, go to the Access Tokens menu and create 20 tokens for each server farm.
![image](https://github.com/user-attachments/assets/7e2931e4-af7e-4061-b5bc-abfb9c52a54f)
![image](https://github.com/user-attachments/assets/eb9bb995-2aa8-443c-8687-fb039f394e5e)

**Comment by Gj4meZ** [comment]
Thanks Sir For Help
now i get it
both of my servers was on the same farm
