### ISSUE TITLE
vhserver gen FAILS

### ISSUE THREAD

**Issue by netsupcloud** [vpnhood/VpnHood#603]
./vhserver gen FAILS

error seems that on linux it will refrence to some path in WINDOWS DIR like C:\users\..... for finding somethings so it will fail because host is linux

**Comment by trudyhood** [comment]
Can you share us the error message or an image of the console.

**Comment by netsupcloud** [comment]
![Capture](https://github.com/user-attachments/assets/c7bc5289-979c-4bec-86f3-5121da070e03)
this error is for version 2 i will put for version for in next comment

**Comment by netsupcloud** [comment]
new version is ok now

**Comment by netsupcloud** [comment]
fail to pass IPS im forced to turn off IPS on my network because it will capture malformed TLS so:
if an IPS can detect connection type so DPI will find it later


[Drop] [**] [1:2230009:1] SURICATA TLS error message encountered [**] [Classification: Generic Protocol Command Decode] [Priority: 3] {TCP} 46.4.114.241:443 -> 5.201.249.192:3621

**Comment by trudyhood** [comment]
That's so weird, VpnHood does not manipulate TLS, it is standard connection created by standard library using the most recent TLS version. Make sure both client and server using the recent version. 
If you have any idea please share us with us.

**Comment by trudyhood** [comment]
Hi,
Did you find anything or do you have any idea on this matter?
