### ISSUE TITLE
India server in not connecting 

### ISSUE THREAD

**Issue by Svm0075** [vpnhood/VpnHood#604]
Indian server is not connecting and other servers are working fine.

**Comment by Svm0075** [comment]
> Indian server is not connecting and other servers are working fine.


12:56:02.2155 | Info | 
AppVersion: 4.6.553.0

12:56:02.2157 | Info | 
Time: 2024-09-08 07:26:02Z

12:56:02.2158 | Info | 
OS: Xiaomi: 2107113SI, Android: 14

12:56:02.2159 | Info | 
UserAgent: Mozilla/5.0 (Linux; Android 14; 2107113SI Build/UKQ1.231207.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/127.0.6533.103 Mobile Safari/537.36

12:56:02.2296 | Info | 
UserSettings: {
  "Logging": {
    "LogToConsole": true,
    "LogToFile": false,
    "LogAnonymous": true,
    "LogEventNames": [],
    "LogLevel": "Information"
  },
  "CultureCode": null,
  "ClientProfileId": "a7d7fe03-604e-4215-b72b-e94fb79f19b5",
  "ServerLocation": "IN/Maharashtra",
  "MaxDatagramChannelCount": 4,
  "TunnelClientCountry": true,
  "AppFilters": [],
  "AppFiltersMode": "All",
  "UseUdpChannel": true,
  "DropUdpPackets": false,
  "IncludeLocalNetwork": true,
  "IncludeIpRanges": [
    "0.0.0.0-255.255.255.255",
    "::-ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff"
  ],
  "ExcludeIpRanges": [],
  "PacketCaptureIncludeIpRanges": [
    "0.0.0.0-255.255.255.255",
    "::-ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff"
  ],
  "PacketCaptureExcludeIpRanges": [],
  "AllowAnonymousTracker": true,
  "DnsServers": null,
  "DomainFilter": {
    "Blocks": [],
    "Excludes": [],
    "Includes": []
  },
  "DebugData1": null,
  "DebugData2": null
}

12:56:02.2365 | Info | 
Country: IN

12:56:02.2366 | Info | 
VpnHood Client is Connecting ...

12:56:02.2367 | Info | 
TokenId: **-bcf7-38e3e155f561, SupportId: **95

12:56:02.2370 | Trac | 
Preparing VpnService...

12:56:02.2476 | Trac | 
Checking the Internet connection...

12:56:02.2497 | Info | 
PingTest: Started, RemoteAddress: 8.8.8.8, Timeout: 10000...

12:56:02.2515 | Info | 
PingTest: Started, RemoteAddress: 1.1.1.1, Timeout: 10000...

12:56:02.2531 | Info | 
UdpTest: Started, DnsName: www.google.com, NsServer: 8.8.8.8:53, Timeout: 10000...

12:56:02.2542 | Info | 
UdpTest: Started, DnsName: www.google.com, NsServer: 1.1.1.1:53, Timeout: 10000...

12:56:02.2546 | Info | 
HttpTest: Started, Url: https://www.google.com/, Timeout: 10000...

12:56:02.2553 | Info | 
HttpTest: Started, Url: https://www.quad9.net/, Timeout: 10000...

12:56:02.2557 | Info | 
HttpTest: Started, Url: https://www.microsoft.com/, Timeout: 10000...

12:56:02.3187 | Info | 
UdpTest: Succeeded, DnsName: www.google.com, NsServer: 8.8.8.8:53.

12:56:02.3669 | Info | 
HttpTest: Succeeded, Url: https://www.microsoft.com/.

12:56:03.1580 | Info | 
HttpTest: Succeeded, Url: https://www.google.com/.

12:56:03.8754 | Info | 
HttpTest: Succeeded, Url: https://www.quad9.net/.

12:56:12.2543 | Warn | 
PingTest: Failed!, RemoteAddress: 8.8.8.8. Message: Status: TimedOut
Exception: System.Exception: Status: TimedOut
   at VpnHood.Client.Diagnosing.DiagnoseUtil.CheckPing(IPAddress ipAddress, Int32 timeout, Boolean anonymize)

12:56:12.2555 | Warn | 
PingTest: Failed!, RemoteAddress: 1.1.1.1. Message: Status: TimedOut
Exception: System.Exception: Status: TimedOut
   at VpnHood.Client.Diagnosing.DiagnoseUtil.CheckPing(IPAddress ipAddress, Int32 timeout, Boolean anonymize)

12:56:12.2592 | Warn | 
UdpTest: Failed!, DnsName: www.google.com, NsServer: 1.1.1.1:53, Message: Arg_TimeoutException.
Exception: System.TimeoutException: Arg_TimeoutException
   at VpnHood.Common.Utils.VhUtil.RunTask(Task task, TimeSpan timeout, CancellationToken cancellationToken)
   at VpnHood.Common.Utils.VhUtil.<RunTask>d__8`1[[System.Net.Sockets.UdpReceiveResult, System.Net.Sockets, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a]].MoveNext()
   at VpnHood.Client.Diagnosing.DiagnoseUtil.GetHostEntry(String host, IPEndPoint dnsEndPoint, UdpClient udpClient, Int32 timeout)
   at VpnHood.Client.Diagnosing.DiagnoseUtil.GetHostEntry(String host, IPEndPoint dnsEndPoint, UdpClient udpClient, Int32 timeout)
   at VpnHood.Client.Diagnosing.DiagnoseUtil.CheckUdp(IPEndPoint nsIpEndPoint, Int32 timeout)

12:56:12.2662 | Trac | 
Shutting down...

12:56:12.2663 | Info | 
Client state is changed. NewState: Disconnecting

12:56:12.2664 | Trac | 
Disposing the PacketCapture...

12:56:12.2709 | Trac | 
Disposing ClientHost...

12:56:12.2709 | Trac | 
Disposing Tunnel...

12:56:12.2710 | Trac | 
Disposing ProxyManager...

12:56:12.2711 | Trac | 
Disposing Nat...

12:56:12.2712 | Trac | 
Disposing ConnectorService...

12:56:12.2725 | Info | 
Trying to get a new ServerToken from url. Url: ht***.txt

12:56:12.2727 | Trac | 
VpnService has been destroyed!

12:56:12.2981 | Info | 
The remote ServerToken is not new and has not been updated.

12:56:12.3024 | Erro | 
Could not connect.
Exception: VpnHood.Client.Exceptions.NoInternetException: It looks like your device is not connected to the Internet or the connection is too slow.
   at VpnHood.Client.Diagnosing.Diagnoser.Diagnose(VpnHoodClient vpnHoodClient, CancellationToken cancellationToken)
   at VpnHood.Client.App.VpnHoodApp.ConnectInternal(Token token, String serverLocationInfo, String userAgent, Boolean allowUpdateToken, CancellationToken cancellationToken)
   at VpnHood.Client.App.VpnHoodApp.ConnectInternal(Token token, String serverLocationInfo, String userAgent, Boolean allowUpdateToken, CancellationToken cancellationToken)
   at VpnHood.Client.App.VpnHoodApp.Connect(Nullable`1 clientProfileId, String serverLocation, Boolean diagnose, String userAgent, Boolean throwException, CancellationToken cancellationToken)

**Comment by bobvhood** [comment]
Thank you for reporting. The India datacenter is down. We are working on it,

**Comment by Svm0075** [comment]
> Thank you for reporting. The India datacenter is down. We are working on it,

Can you just tell me tentative time roughly? I am in need of Indian server. 

Vpnhood has the fastest India server. Are there any alternatives?

**Comment by bobvhood** [comment]
We are working on it. Still need time to find out is it a serious issue or can be solved by 1 hour. I can understand you rely on that server at this time, but that the best we can do at the moment.

**Comment by bobvhood** [comment]
It is done
