### ISSUE TITLE
Raspberry?

### ISSUE THREAD

**Issue by Kaiser42** [vpnhood/VpnHood#606]
is it possible to install it on a raspberry?

**Comment by trudyhood** [comment]
Perhaps the server, but we have yet to work on installing the client on Raspberry. It is not planned, either.

**Comment by Kaiser42** [comment]
> Perhaps the server, but we have yet to work on installing the client on Raspberry. It is not planned, either.
> 

Yeh just the server

**Comment by trudyhood** [comment]
The severer is built in pure .NET. I think you can the linux arm built in one of the latest raspberry. Let us we know if you try that.

**Comment by Kaiser42** [comment]
> The severer is built in pure .NET. I think you can the linux arm built in one of the latest raspberry. Let us we know if you try that.

It says it is not installed, any suggestions?
![image](https://github.com/user-attachments/assets/a9981fc4-31bd-42a7-a47c-f0033ebbc652)

**Comment by Kaiser42** [comment]
![image](https://github.com/user-attachments/assets/edef05ab-0ac9-4bd0-9779-cdb9df27e73c)
![image](https://github.com/user-attachments/assets/90d4579d-6c2c-4a4f-96d9-7dae5ccf37b6)
![image](https://github.com/user-attachments/assets/035af15d-9f98-4840-bfb0-85ab47d16cd9)
![image](https://github.com/user-attachments/assets/353cd99d-5572-4414-88cd-5941c6ccb0f2)

**Comment by Kaiser42** [comment]
> The severer is built in pure .NET. I think you can the linux arm built in one of the latest raspberry. Let us we know if you try that.

![image](https://github.com/user-attachments/assets/b1488507-4eca-4ffe-8164-b503350fca24)

**Comment by trudyhood** [comment]
Please login to your server and go to /opt/VpnHoodServer/
You can run ./vhserver and see what's wrong; please send me the error message.
Also, there is log file in /storage/logs/server.log, which may be helpful, but it looks the server didn't run at all.
Make sure you have installed the correct binary.  As far as I know, the Raspberry is arm.

Let me know the result ./vhserver

**Comment by Kaiser42** [comment]
> Please login to your server and go to /opt/VpnHoodServer/ You can run ./vhserver and see what's wrong; please send me the error message. Also, there is log file in /storage/logs/server.log, which may be helpful, but it looks the server didn't run at all. Make sure you have installed the correct binary. As far as I know, the Raspberry is arm.
> 
> Let me know the result ./vhserver

I got it to work using VpnHoodServer-linux-arm64.sh but it won't connect.

[log.txt](https://github.com/user-attachments/files/17007428/log.txt)

**Comment by trudyhood** [comment]
Good, let me know what the problem was in the previous step.

For the last issue, ensure you have an IPv4 "PublicInToken" in your server, then get the token again.
Also, please ensure the IP from the device you are trying to connect is reachable.
Let m e know the result, i am here for you to help if it does not work

**Comment by trudyhood** [comment]
please note the IPv4 is not mandatory if you are sure that you client have IP6

**Comment by Kaiser42** [comment]
> Good, let me know what the problem was in the previous step.
> 
> For the last issue, ensure you have an IPv4 "PublicInToken" in your server, then get the token again. Also, please ensure the IP from the device you are trying to connect is reachable. Let m e know the result, i am here for you to help if it does not work

wdym whit " ensure you have an IPv4 "PublicInToken" in your server, then get the token again."?

**Comment by Kaiser42** [comment]
this?
![image](https://github.com/user-attachments/assets/d4908b7d-1c26-436a-99d0-7fccce2836ab)

**Comment by Kaiser42** [comment]
done, it works.

**Comment by trudyhood** [comment]
That's great. Is it Raspberry?
If it is:

1. Have you managed to use it? 
2. What about the speed and your experience?
3. Did you need to manually configure your server, or it was easy?

**Comment by Kaiser42** [comment]
> That's great. Is it Raspberry? If it is:
> 
> 1. Have you managed to use it?
Only in hause, right now in class I have tried it but it does not connect, I attach the log
> 2. What about the speed and your experience?
It was fine, it didn't make much difference using my pc as a server but the test was local so outside I don't know.
> 3. Did you need to manually configure your server, or it was easy?
I just changed the installation instruction by changing the link to reference the one in arch.

**Comment by Kaiser42** [comment]
I think the machine does not hold and shuts down or there is a problem.

**Comment by Kaiser42** [comment]
![image](https://github.com/user-attachments/assets/456f9fd5-c074-4c35-bb91-d9c71e73a79b)

**Comment by Kaiser42** [comment]
I already saw that I have to log in to the machine to go. is there any way that is without? is that I can not connect via ssh, I tried everything but outside the network is impossible for me
