### ISSUE TITLE
VPN blockd in student wifi

### ISSUE THREAD

**Issue by Kaiser42** [vpnhood/VpnHood#608]
What the title says. I tried it from my cell phone with data and it worked perfectly. From the pc no. When I connect the pc to the mobile network allows the vpn.

**Comment by trudyhood** [comment]
Hi, Can you tell me which country you are located in? Are you using VpnHood Client or VpnHood CONNECT?

**Comment by Kaiser42** [comment]
Client for android and pc. I am located in  Spain

**Comment by trudyhood** [comment]
Can you give me a snapshot or recording? We have to fix this

**Comment by Kaiser42** [comment]
> Can you give me a snapshot or recording? We have to fix this

ok. tomorrow when i go to class i will make a video and send it to you with the diagnostic logs if you need them.

**Comment by Kaiser42** [comment]
The video and the 2 logs. The server is never turned off. The connection from home exists but not from the school wifi. I usually test before I go out and once I get there I test so I don't think there is a problem with the server itself.

https://youtu.be/e_yRj6c7_6c

**Comment by trudyhood** [comment]
PingTest: Failed!, RemoteAddress: 185.*.*.50. Message: Status: TimedOut

It means your server ip is blocked or unreachable from that network. It is not related to VPN protocol. Try changing your server ir server ip which is reachable. Also make sure you're server firewall does not block any incoming connection.

it means even if you run a web server on that server,  you can not browse that website from that student WiFi. 

Do you need specific proxy settings to connect to Internet in that WiFi?

**Comment by Kaiser42** [comment]
I will tell a friend to install it and test it at home. I honestly don't know what I can do. In the previous course there were no such problems.

I will try to reboot the router to see if it gives me another public ip. About the fireware, I have it disabled. What I don't understand is why I can connect from home and not from there. If you know what else I can do besides rebooting the router I would appreciate it.


> PingTest: Failed!, RemoteAddress: 185._._.50. Message: Status: TimedOut
> 
> It means your server ip is blocked or unreachable from that network. It is not related to VPN protocol. Try changing your server ir server ip which is reachable. Also make sure you're server firewall does not block any incoming connection.
> 
> it means even if you run a web server on that server, you can not browse that website from that student WiFi.
> 
> Do you need specific proxy settings to connect to Internet in that WiFi?

**Comment by trudyhood** [comment]
Before using any tools and VPN, please make sure your IP is reachable from the school's WiFI using some tools like Ping. Also, if the server is at home, ensure it is reachable from outside, such as your friend's WiFi or mobile network. Maybe the school WiFi has blocked your home IP. I assure you VpnHood is undetectable; however, the server IP can be blocked if there is suspicious activity such as transferring huge traffic from  a website that usually not does happen from a work environment or school
