### ISSUE TITLE
Connection Problem

### ISSUE THREAD

**Issue by Gourab-Nandi** [vpnhood/VpnHood#611]
"I've purchased a VPN server from VPN Hood to bypass online gaming restrictions in my hostel. However, today the server isn't working for India, though it functions properly for the USA and other countries. Every time I try to connect (to India server), I receive a diagnostic message saying, 'It looks like your device is not connected to the Internet or the connection is too slow.' I've confirmed that the issue is not with the hostel's network, as I've also tried using my personal internet connection and experienced the same result.

**Comment by trudyhood** [comment]
Hi,
we are really sorry for that. India Data center is down and got serious issue. We already know it and working hard to solve the issue. 
Thank you for your patience.

**Comment by bobvhood** [comment]
Hi,
We have added a few nodes to another data center to serve as a backup, as the current one has proven unreliable. Please check it now and let us know if you encounter any issues. Sorry for the inconvenience.
Thank you for being a premium user.
