### ISSUE TITLE
Unable to SSH into Server After Starting VPNhood Server, but VPN Service Works Normally

### ISSUE THREAD

**Issue by Cormac315** [vpnhood/VpnHood#617]
I am experiencing an issue where, after starting the VPNhood server, I am unable to SSH into the server. However, the VPN service itself appears to be functioning normally.

Server OS: Centos 9
VPNhood Server Version: 4.6.553
SSH Client Used: FinalShell

**Comment by trudyhood** [comment]
Hi, does it happen immediately after running VpnHood Server or after some hours?

**Comment by Cormac315** [comment]
immediately
the SSH connection to the server is immediately dropped whenever a VPNhood client connects. Sometimes, I am unable to reconnect to the server at all.

**Comment by Cormac315** [comment]
> Hi, does it happen immediately after running VpnHood Server or after some hours?

immediately
the SSH connection to the server is immediately dropped whenever a VPNhood client connects. Sometimes, I am unable to reconnect to the server at all.

**Comment by Cormac315** [comment]
I have tried reinstalling the system, but the problem persists.

**Comment by trudyhood** [comment]
Do you use the same IP to connect to your server via SSH? I mean are your VpnHood server IP and ssh ip same?

**Comment by Cormac315** [comment]
> Do you use the same IP to connect to your server via SSH? I mean are your VpnHood server IP and ssh ip same?

yes

**Comment by trudyhood** [comment]
The server IP address is permanently excluded from the VPN; otherwise, it causes an infinite loop, and nothing works, 
That sounds so weird. 

* Do you use the latest version from the main branch? 
* Have you figured out the VpnHood server manually?
* Can you try with PUTTY?
* Can I have temporary access to your server? trudy@vpnhood.com
