### ISSUE TITLE
Error on command gen

### ISSUE THREAD

**Issue by sepehr310** [vpnhood/VpnHood#646]
im trying this command: `sudo /opt/VpnHoodServer/vhserver gen`
but it give me this error : `Specify --help for a list of available options and commands.
Unhandled exception. System.Exception: Unrecognized command or argument 'gen'
   at VpnHood.App.Server.Program.Main(String[] args) in C:\Users\Developer\source\repos\Vh\VpnHood\Src\Apps\Server.Net\Program.cs:line 14
   at VpnHood.App.Server.Program.<Main>(String[] args)
/opt/VpnHoodServer/vhserver: line 31: 3849277 Aborted                 (core dumped) "$exeFile" "$@"`

**Comment by trudyhood** [comment]
Are you sure you haven't configured it for VpnHood MANAGER?
Can you send me your server credentials? trudy@vpnhood.com
