### ISSUE TITLE
VPNHood not working

### ISSUE THREAD

**Issue by NSTAdventure** [vpnhood/VpnHood#70]
Bruh seriously? VPNHood not working if i using specific country

I didn't try what if i use all country option
How do i know this VPNHood not working?
Try to find what is your devices ip ...
And it's still on my original region even after VPNHood connected
(Bruh 🗿🗿🗿🗿🗿🗿)

Realme 5i
Android 10 (Realme UI 1.0)

@trudyhood

**Comment by trudyhood** [comment]
> Bruh seriously? VPNHood not working uf i using specific country (idk about other)
> 
> Realme 5i Android 10 (Realme UI 1.0)

Hi, would you please elaborate more about this?
_"using specific country (idk about other)"_ Is about the Countries options or you just unable to connect.
![image](https://user-images.githubusercontent.com/72891124/139919059-7010667d-cd45-425b-8f61-4a6b780eda4c.png)

**Comment by NSTAdventure** [comment]
Edit:
It's turned out due to i enabled exclude from wlan setting nvm dev 🙏 it's fixed sorry for inconvenience 🙏
