### ISSUE TITLE
f-droid

### ISSUE THREAD

**Issue by res369** [vpnhood/VpnHood#76]
Hello, please add the program to f-droid

**Comment by trudyhood** [comment]
I wish we had time to publish it to different stores. VpnHood is an Open-Source project. It is welcome if anyone contributes.
Thank you for trying VpnHood!

**Comment by momobobe** [comment]
In this way @trudyhood, did you mean a non-opposition? Then @linsui do you have any interest helping here?

**Comment by trudyhood** [comment]
I don't know how does it work. Let me know if you need any modification
