### ISSUE TITLE
Unable to install Webview2 mandatory prerequisite

### ISSUE THREAD

**Issue by bizzbyster** [vpnhood/VpnHood#84]
I get this error message when I run the installer on Windows 10.

![image](https://user-images.githubusercontent.com/4001792/150372064-0a227ae6-36f7-40ab-a4d0-b4a3ba57954b.png)

I tried to install Edge Webview2 directly from Microsoft but that didn't solve the problem. Any ideas?

**Comment by bobvhood** [comment]
I may help you if you provide me with more information. What error do you get when you try to install it directly from Microsoft?

**Comment by bizzbyster** [comment]
Thanks @bobvhood. That's just it -- I get no error at all! It appears to install successfully. This is the one that I installed successfully:

![image](https://user-images.githubusercontent.com/4001792/150429878-a920eb37-acfb-4d2a-abda-f2d52c0dd665.png)

Any ideas?

**Comment by bobvhood** [comment]
Download this one please.
![image](https://user-images.githubusercontent.com/92276967/150430286-f4b4d31b-8df5-45f4-af32-bdbd7203d432.png)

Also let me know the version of your VpnHood. Make sure you have downloaded it recently from here:
https://github.com/vpnhood/VpnHood/releases/latest/download/VpnHoodClient-Win.exe

**Comment by bizzbyster** [comment]
The version you linked to installed fine and I'm good to go. We can close this issue. Thank you!!
