### ISSUE TITLE
Not Familiar With New Microsoft Edge Web View Version

### ISSUE THREAD

**Issue by hootanht** [vpnhood/VpnHood#90]
![image](https://user-images.githubusercontent.com/27281206/150651460-960caa5d-b170-432f-8272-3d33509b89e8.png)

**Comment by hootanht** [comment]
![](https://user-images.githubusercontent.com/27281206/150651532-fb17f964-7ce0-463d-90ac-6ed421b13066.png)

**Comment by bobvhood** [comment]
Hi,
Would you try to install the latest version from here and let me know the result:
https://github.com/vpnhood/VpnHood/releases/latest/download/VpnHoodClient-Win.exe

A client reported the same issue too. I will try to install in on fresh windows to see what's going wrong recently.

**Comment by bobvhood** [comment]
I couldn't find any issue on Fresh Windows 10 x64.
I would grateful if you let me know your 
1) Windows Version? (10, 11)
2) Windows Editon (home, professional)
2) Windows CPU architecture (32 bit, 64bit)
3) Where did you download VpnHood in the first place?

**Comment by hootanht** [comment]
> I couldn't find any issue on Fresh Windows 10 x64. I would grateful if you let me know your
> 
> 1.  Windows Version? (10, 11)
> 2.  Windows Editon (home, professional)
> 3.  Windows CPU architecture (32 bit, 64bit)
> 4.  Where did you download VpnHood in the first place?

1.  windows 11
2.  Pro
3.  AMD 4800H
4.  From Github Release

**Comment by bobvhood** [comment]
I couldn't simulate the issue on Windows 11. No issue detect on my Windows 11.
You can try to you install webview2 from Microsoft manually:
https://go.microsoft.com/fwlink/p/?LinkId=2124703

Let me know if it works.
